### ISSUE TITLE
config option for external storage

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#12216]
We have to make it possible to configure the behavior of externaly mounted storages in a more detailed way.
- [ ] UX improvements. See SharePoint and WND as examples (https://github.com/owncloud/core/issues/12338)
- [x] Capturing Credentials on Login (an option on a per mount basis) (https://github.com/owncloud/core/issues/12635)
- [x] UI groundwork for config options (dropdown): https://github.com/owncloud/core/issues/9663
- [x] Encryption on / off (https://github.com/owncloud/core/issues/10731)
- [ ] Sharing with link on / off (~~https://github.com/owncloud/core/issues/8631~~ https://github.com/owncloud/core/issues/19157)
- [ ] User sharing on / off (https://github.com/owncloud/core/issues/19157)
- [x] Cache refresh behavior (select option)
- [x] Previews (performance concern) (https://github.com/owncloud/core/issues/5917)
- [ ] Trash Bin (https://github.com/owncloud/core/issues/4389)
- [ ] Versions
- [ ] Broker on / off
- [ ] Search provider
- [ ] Sync Permission on / off (requires https://github.com/owncloud/core/issues/26311)
- [ ] Storage specific versions/trashbin handler: (https://github.com/owncloud/core/issues/12274)
- [x] Accomodate config to allow for multiple auth mechanisms (password, auth)

Edit: added user sharing

**Comment by Xenopathic** [comment]
Well it's not going to make oC 8, that's for sure.

**Comment by PVince81** [comment]
Setting to 8.1

**Comment by PVince81** [comment]
- [ ] make external storage config UI + endpoints work with the new storage_id: https://github.com/owncloud/core/issues/14058 (this is a prerequisite to make room for additional options)

**Comment by PVince81** [comment]
What was "cache refresh behavior" option again ? Is it to allow a "force full rescan" to detect outside changes, with a configurable interval ? (could be a solution for https://github.com/owncloud/core/issues/5036)

**Comment by PVince81** [comment]
The config option for encryption was added here: https://github.com/owncloud/core/issues/10731

Setting milestone to 8.2 to look into the other entries.

**Comment by cmonteroluque** [comment]
@PVince81 @Xenopathic update?
@karlitschek @MTRichards ping

**Comment by karlitschek** [comment]
i think this should be done as part of the external storage UI consolidation

**Comment by Xenopathic** [comment]
There are a lot of improvements listed here, they won't all come in one go, and certainly not for 8.2

**Comment by MTRichards** [comment]
Thanks @cmonteroluque 
This is the long standing list for additional configuration options for all external storage. I think iterative and incremental is just fine, and we can roll it all in as @karlitschek says. 

We do want to, however, keep it in sight and make progress against better and more complete UFA over time. I'll take any advice on implementation order, but we need to do some of this each release to get there long term or we will be here again next year.

**Comment by PVince81** [comment]
I edited the original post to split "User sharing" from "Link sharing" as discussed in https://github.com/owncloud/core/issues/19157

**Comment by PVince81** [comment]
Moving to 9.2 to continue working on the remaining items.

CC @dragotin @DeepDiver1975

**Comment by PVince81** [comment]
@pmaier1 would move to backlog or future for now when we have time to resume working on the remaining items.

**Comment by PVince81** [comment]
moving to backlog now, needs rescheduling of individual items
