### ISSUE TITLE
Checksums to Verify Up- and Download

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#12417]
Some storage backends support hash sums of files. These could be used to ensure the files integrity when up- or downloaded between sync client and server. This adds another level of security.

The basic idea is to add a hashsum as HTTP header to GET or PUT and compare on the other communication side. If the numbers do not match, the transmission has to be an error. 

@moscicki has drafted a specification: https://github.com/cernbox/smashbox/blob/master/protocol/checksum.md as discussed on a meeting with @DeepDiver1975 and @dragotin.

**Comment by bantu** [comment]
I am not sure whether this is useful in this context, but for the record: https://github.com/bantuXorg/php-stream-filter-hash allows checksumming data written to a PHP stream.

**Comment by PVince81** [comment]
Once again random data corruption has been found with up/download which could be avoided by checksums: https://github.com/owncloud/client/issues/2893

**Comment by PVince81** [comment]
Can we get this scheduled ?

**Comment by DeepDiver1975** [comment]
Let's start to add the checksums on the transport layer when putting a file from the client to the server.
In a second step we can add a getChecksum() method to the storage interface to transmit the checksum to the client on PUT.

**Comment by PVince81** [comment]
The way I see, this is what needs to be done:
#### Part 1
- [ ] client sends checksum along with the PUT operation (possibly on this branch https://github.com/owncloud/client/commits/checksum_verify)
- [ ] server part that writes the part file (either from chunks or directly) must compute the checksum on the fly (rolling checksum), then compare it with the one submitted with PUT. If mismatch: return HTTP code for error

#### Part 2
- [ ] server stores received checksum in oc_filecache (needs new column)
- [ ] on PROPFIND, return checksum in a new attribute (but only if one is available in DB)

**Comment by DeepDiver1975** [comment]
> server stores received checksum in oc_filecache (needs new column)

I'd use the checksum on filecache as fall back if the storage does not provide the checksum

**Comment by DeepDiver1975** [comment]
> on PROPFIND, return checksum in a new attribute (but only if one is available in DB)

header on GET is required as well - https://github.com/cernbox/smashbox/blob/master/protocol/checksum.md#get

**Comment by karlitschek** [comment]
Good plan. :+1:

**Comment by PVince81** [comment]
Defer to 8.2 as we're post feature freeze ?

**Comment by dragotin** [comment]
We had a discussion about this on the ownCloud contrib conf today again. It was agreed that as a first step, the server should be enhanced to **store** the checksums the client is sending along with a PUT request. The server will return the checksums in the attributes list that is returned by a PROPFIND on a certain resource by default. Also, the server will add the checksum as a custom header to GET requests. 

Even though it is completely clear that checksums will not *always* be there, we can already benefit from this first step in a couple of scenarious.

**Comment by karlitschek** [comment]
i created a new issue for that https://github.com/owncloud/core/issues/18716

**Comment by dragotin** [comment]
ok, lets track it there.
