### ISSUE TITLE
User Management - ownCloud 8.0

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#12620]
This issue is there for the purpose of keeping track of the required tasks for the planned user management in ownCloud 8.0.

- [ ] **Pre-Defined Filters** (in addition to what is already there) (https://github.com/owncloud/core/issues/12593) @LukasReschke 
 - [x] Step 1: Refactor group management (https://github.com/owncloud/core/issues/12618)
 - [ ] Step 2: Modify external user backends to store users in the DB (https://github.com/owncloud/core/pull/12799)
 - [x] Step 3: Add user backend type to REST API (https://github.com/owncloud/core/pull/12711)
 - [x] Step 4: Create filter for backend type to REST API (https://github.com/owncloud/core/pull/12726)
 - [ ] Step 5: Create filter for internal and external users in GUI
 - [ ] Step 6: Create filter for users without groups in GUI
- [x] **Add / update users email**  (https://github.com/owncloud/core/issues/12595) @MorrisJobke
 - [x] Step 1: Refactor group management (https://github.com/owncloud/core/issues/12618)
 - [x] Step 2: Add user backend type to REST API (https://github.com/owncloud/core/pull/12711)
 - [x] Step 3: Load users only via JS - remove first rendering via PHP (#12790)
 - [x] Step 4: Add field for updating end editing email into UX and the REST routes (#12921)
- [x] **Send new users an email** (https://github.com/owncloud/core/issues/12603) @MorrisJobke
 - [x] Step 1: Refactor group management (https://github.com/owncloud/core/issues/12618)
 - [x] Step 2: Add input field for user mail (#12870)
 - [x] Step 3: Add checkbox "send new email", modify creation code to trigger a send email (#12870)
 - [x] Step 4: Register email template with template editor (https://github.com/owncloud/templateeditor/pull/15)
- [x] **LDAP / AD / SAML Auth Flag** (Nice to have - not a must)(https://github.com/owncloud/core/issues/12604) @LukasReschke 
 - [x] Step 1: Refactor group management (https://github.com/owncloud/core/issues/12618)
 - [x] Step 2: Add user backend type to REST API (https://github.com/owncloud/core/pull/12711)
 - [x] Step 3: Load users only via JS - remove first rendering via PHP (#12790)
 - [x] Step 4: Display backend type in the GUI (#12806)
 - [x] Step 5: Add proper display names (#12819)

Postponed topics are in #12998

**Comment by MorrisJobke** [comment]
@DeepDiver1975 #12799 is postponed to 8.1 -> close this ticket as the remaining steps are already in #12998 (user management ticket for 8.1)

**Comment by SergioBertolinSG** [comment]
Bugs related to user management:

[ ] Short textboxes #13464

**Comment by DeepDiver1975** [comment]
> Short textboxes #13464

let's add this to #12998 for OC8.1 - THX @SergioBertolinSG
