### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#12998]
This issue is there for the purpose of keeping track of the required tasks for the planned user management in ownCloud 8.2.
- [ ] Pre-Defined Filters (in addition to what is already there) (https://github.com/owncloud/core/issues/12593) @LukasReschke 
  - [x] Step 1: Refactor group management (https://github.com/owncloud/core/issues/12618)
  - [ ] Step 2: Modify external user backends to store users in the DB (https://github.com/owncloud/core/pull/12799)
  - [x] Step 3: Add user backend type to REST API (https://github.com/owncloud/core/pull/12711)
  - [x] Step 4: Create filter for backend type to REST API (https://github.com/owncloud/core/pull/12726)
  - [ ] Step 5: Create filter for internal and external users in GUI
  - [ ] Step 6: Create filter for users without groups in GUI
- [ ] User quota usage (https://github.com/owncloud/core/issues/12602) @MorrisJobke
  - [x] Step 1: Refactor group management (https://github.com/owncloud/core/issues/12618)
  - [ ] Step 2: According to @icewind1991 there is no fast way to retrieve the quota per user without recalculating it - therefore it needs to get stored somewhere. According to @icewind1991 there _should_ be a way ready with ownCloud 8.
  - [x] Step 4: Load users only via JS - remove first rendering via PHP (#12790)
  - [ ] Step 5: Add used quota to response from REST API
  - [ ] Step 5: Display quota in the UI
- [ ] Sorting (https://github.com/owncloud/core/issues/12597)
- [ ] User Sorting (https://github.com/owncloud/core/issues/12598)
- [ ] Multi select (https://github.com/owncloud/core/issues/12599)
- [ ] Rename groups (https://github.com/owncloud/core/issues/12600) 
  - [x] Step 1: Refactor group management (https://github.com/owncloud/core/issues/12618)
  - [ ] Step 2: Add index to table
  - [ ] Step 3: Modify ownCloud code-base to use the displayname instead the ID
  - [ ] Step 4: Migrate all existing references to the gid with the ID - this requires going through every single app that uses sharing in any way
- [ ] Disable a user (https://github.com/owncloud/core/issues/12601)
  - [ ] Step 1: Add OCC command and GUI option to disable and enable users
  - [x] Step 2: Load users only via JS - remove first rendering via PHP (#12790)
  - [ ] Step 3: Verify all usages of the login method to check the disabled and enabled status
  - [ ] Step 4: Implement filter for https://github.com/owncloud/core/issues/12593
- [ ] filtering and groups (#8516)

cc @LukasReschke @DeepDiver1975

**Comment by MorrisJobke** [comment]
I added #8516

**Comment by MorrisJobke** [comment]
Bugs related to user management:

- [ ] Short textboxes #13464

**Comment by SergioBertolinSG** [comment]
Bugs related to user management:

- [ ] Short textboxes #13464 
- [ ] Username is erased while entering a wrong email address #13500 
- [ ] Invalid email address keeps in textfield and no alert is shown #13503

**Comment by MorrisJobke** [comment]
Maybe something we can take care of if we touch it:

* [ ] Use IDs instead of names for groups #4972

**Comment by MorrisJobke** [comment]
* [ ] save settings of user management #13859

**Comment by MorrisJobke** [comment]
* [ ] change email even if password change isn't allowed #10005

**Comment by MorrisJobke** [comment]
* [ ] users are added to the list even if it's filtered list #14186

**Comment by MorrisJobke** [comment]
* [ ] User count gives wrong number / adds up all group members #14921

**Comment by PVince81** [comment]
- [ ] scroll to newly created user https://github.com/owncloud/core/issues/21508
