### ISSUE TITLE
L10N epic ticket

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#14663]
There are several things wrong with our L10N classes/methods.

- [x] The `OC\L10N\Factory` has no public interface and there for can not be used by apps: https://github.com/owncloud/core/pull/18620
- [x] The public interface is missing a stub for some of the methods
- [x] The OC_L10N class should be using a namespace
- [x] The methods related to guessing the language, should be moved to the factory,
same applies to all find, exists and force methods aswell
- [x] the L10N class should not have a static method `get()`, instead the factory should be used
- [x] `t()` should return a string, instead of a OC_L10N_String object by default, for saver usage: https://github.com/owncloud/activity/pull/215#issuecomment-69944160

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
let's take care of this in 8.2

**Comment by nickvergessen** [comment]
Factory interface is being added in https://github.com/owncloud/core/pull/18620

**Comment by PVince81** [comment]
Did we make any epic progress ? :wink: 

Moving to 9.0 to continue
