### ISSUE TITLE
Smashbox tests running against master+encryption

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#15781]
### Without Encryption

- [x] `test_scrapeLogFile.py` :white_check_mark: 
- [x] `test_reshareDir.py` :white_check_mark: 
- [x] `test_uploadFiles.py` :white_check_mark: 
- [x] `test_shareDir.py`: :white_check_mark:  https://github.com/owncloud/smashbox/pull/72
- [x] `test_shareFile.py`: :white_check_mark:  reported at https://github.com/owncloud/core/issues/15786, PR at https://github.com/owncloud/core/pull/16159
- [x] `test_shareGroup.py`: :white_check_mark:  https://github.com/owncloud/smashbox/pull/73
- [x] `test_sharePermissions.py`: :white_check_mark:  https://github.com/owncloud/smashbox/pull/74

### With Encryption

- [x] `test_scrapeLogFile.py` :white_check_mark: 
- [x] `test_reshareDir.py`: https://github.com/owncloud/smashbox/pull/70
- [x] `test_uploadFiles.py`: https://github.com/owncloud/smashbox/pull/70
- [x] `test_shareDir.py`:
    - [x] https://github.com/owncloud/smashbox/pull/72
    - [x] https://github.com/owncloud/smashbox/pull/70
- [x] `test_shareFile.py`: reported at https://github.com/owncloud/core/issues/15786
    - [x] https://github.com/owncloud/core/pull/16159
    - [x] https://github.com/owncloud/smashbox/pull/70
- [x] `test_shareGroup.py`: https://github.com/owncloud/smashbox/pull/73
- [x] `test_sharePermissions.py`:
    - [x] https://github.com/owncloud/smashbox/pull/74
    - [x] *known to be broken* https://github.com/owncloud/core/issues/12966

**Comment by oparoz** [comment]
Those share bugs could come from the read-only cache bug fixed in https://github.com/owncloud/core/pull/15721

**Comment by DeepDiver1975** [comment]
> #15721

was just merged - @nickvergessen please rebase and fire up the tests again please.

@oparoz THX for the hint - let's see ...

**Comment by nickvergessen** [comment]
Nop, still failing, but it might be a problem on my (old) mashine, because they seem to fail on master without encryption aswell

**Comment by oparoz** [comment]
:(

**Comment by nickvergessen** [comment]
The tests fail, because the mount point for the shared file ends with a trailing slash.
Summoning @PVince81

**Comment by PVince81** [comment]
Could be a regression due to this addition by myself: https://github.com/owncloud/core/pull/15570
It would add a trailing slash to file shares too... but now removing the fix wouldn't work too because some places in the code call `setMountPoint()` with a missing trailing slash. Maybe the fix is to fix the caller instead (which isn't ideal) but also need to take care of the file share cases...

**Comment by PVince81** [comment]
Hmmm no, this is not caused by the PR I mentioned. I ran test_shareDir.py and test_shareFile.py in much older versions in git, and I saw that:
- test_shareDir.py already failed before that version (without `-a`)
- test_shareFile.py works (without `-a`)

@jnfrmarks did test_shareDir.py ever pass before ?

@nickvergessen when running the tests don't forget to add `-a` to make sure it runs all test cases. It seems that there are more fails with it... (maybe they aren't finished)

I'll bisect the potential regression.

**Comment by PVince81** [comment]
The fail for the test_shareFile.py appears since 6a5950275993394df22b208f1126efae9e35e42b (https://github.com/owncloud/core/pull/12006) from @icewind1991 
Maybe we failed to update the etag of shared files or some hooks do not get fired.

**Comment by PVince81** [comment]
I have raised this separately as I was able to reproduce something: https://github.com/owncloud/core/issues/15786

**Comment by jnfrmarks** [comment]
I thought I fixed shareDir - it's a test issue - "shareeTwo" was creating the directory and sync'ing the same directory - causing two directories to be created locally.

**Comment by nickvergessen** [comment]
@PVince81 yes it works reliable on stable8.
The line in the code that I found out is returning wrong stuff (empty string for a given path) is https://github.com/owncloud/core/pull/12006/files#diff-2e4a54e72d495abc750a9bc445da15a0R115
So that is why it is failing since then.

**Comment by MorrisJobke** [comment]
@nickvergessen Can you retest `shareFile.py`? #15786 was merged.

**Comment by nickvergessen** [comment]
Still fails with 
```
2015-04-23 10:54:07,312 - ERROR - sharer -
md5 of modified file /home/nickv/ownCloud/Smashbox/tmpdir/test_shareFile/sharer/TEST_FILE_MODIFIED_USER_SHARE.dat did not change: expected 45b565af28a2998fa8d5dae7eb6e660e, got 45b565af28a2998fa8d5dae7eb6e660e
"md5 of modified file %s did not change: expected %s, got %s" % (fn, md5, actual_md5)) failed in expect_modified() ["/home/nickv/ownCloud/Smashbox/smashbox/python/smashbox/utilities/__init__.py" at line 670]

**Comment by DeepDiver1975** [comment]
@jnfrmarks @nickvergessen @PVince81 can you please digg into this and find out what's going wrong here? THX

**Comment by PVince81** [comment]
@nickvergessen does this test fail without encryption too ? Is it specific ? It could also be etag propagation issue.

**Comment by PVince81** [comment]
Let's make it clearer, regression-wise for test_shareFile.py:
- master without encryption: fails with https://github.com/owncloud/core/issues/15781#issuecomment-95495421
- master with encryption: fails with https://github.com/owncloud/core/issues/15781#issuecomment-95495421
- stable8 without encryption: success
- stable8 with encryption: success

So this failing is not related to encryption.
But there's another regression somewhere, I'll bisect this.

**Comment by DeepDiver1975** [comment]
> But there's another regression somewhere, I'll bisect this.

thx

**Comment by PVince81** [comment]
Wait, it's still 6a5950275993394df22b208f1126efae9e35e42b
The merged PR was not for the fix (https://github.com/owncloud/core/issues/15781#issuecomment-95152690 was a misunderstanding).
The issue is still https://github.com/owncloud/core/issues/15786

**Comment by PVince81** [comment]
WebDAV PUT fails when putting a shared file, so obviously the file didn't change and smashbox says the md5 didn't change either.

**Comment by nickvergessen** [comment]
### Without Encryption

Test | Status
---- | -------------
`test_scrapeLogFile.py` | :white_check_mark:
 | -
`test_reshareDir.py` | :white_check_mark:
 | -
`test_shareDir.py` | :x: ERROR - shareeTwo - File `.../tmpdir/test_shareDir/shareeTwo/localShareDir` exists but should not error_check(not os.path.exists(fn), "File %s exists but should not" % fn) failed in expect_does_not_exist() [`.../smashbox/python/smashbox/utilities/__init__.py` at line 690]
 | *worked before*
`test_shareFile.py` | :x: ERROR - sharer - md5 of modified file `.../tmpdir/test_shareFile/sharer/TEST_FILE_MODIFIED_USER_SHARE.dat` did not change: expected `45b565af28a2998fa8d5dae7eb6e660e`, got `45b565af28a2998fa8d5dae7eb6e660e` "md5 of modified file %s did not change: expected %s, got %s" % (fn, md5, actual_md5)) failed in expect_modified() [`.../smashbox/python/smashbox/utilities/__init__.py` at line 670]
 | *worked before*, reported at https://github.com/owncloud/core/issues/15786
`test_shareGroup.py` | :x: ERROR - shareeTwo - File `.../tmpdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_SHARE.dat` should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in shareeTwo() [`.../smashbox/lib/oc-tests/test_shareGroup.py` at line 213]
 | *known to be broken*
`test_sharePermissions.py` | :x: CRITICAL - recipient_worker - Exception occured: HTTP error: 404 -- Traceback (most recent call last): File `python/smashbox/multiprocessing_engine.py`, line 161, in worker_wrap -- f(step) -- File `.../smashbox/lib/oc-tests/test_sharePermissions.py`, line 233, in recipient_worker -- error_check(oc.file_info(SHARED_DIR_NAME) is not None, 'Recipient did not receive the shared folder')
 | *known to be broken*
`test_uploadFiles.py` | :white_check_mark:
 | -

### With Encryption

Test | Status
---- | -------------
`test_scrapeLogFile.py` | :white_check_mark:
 | -
`test_reshareDir.py` | :x: ERROR - shareeTwo - File `.../tmpdir/test_reshareDir/shareeTwo/TEST_FILE_USER_RESHARE.dat` should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in shareeTwo() [`.../smashbox/lib/oc-tests/test_reshareDir.py` at line 140]
 | **works without encryption**
`test_shareDir.py` | :x: ERROR - shareeOne - /home/nickv/ownCloud/Smashbox/tmpdir/test_shareDir/shareeOne/localShareDir/TEST_FILE_MODIFIED_USER_SHARE.dat does not exist -- ERROR - sharer - md5 of modified file `.../tmpdir/test_shareDir/sharer/localShareDir/TEST_FILE_MODIFIED_USER_SHARE.dat` did not change: expected `45b565af28a2998fa8d5dae7eb6e660e`, got `45b565af28a2998fa8d5dae7eb6e660e` "md5 of modified file %s did not change: expected %s, got %s" % (fn, md5, actual_md5)) failed in expect_modified() [`.../smashbox/python/smashbox/utilities/__init__.py` at line 670]
 | **fails earlier then without encryption**
`test_shareFile.py` | :x: ERROR - shareeOne - File `.../tmpdir/test_shareFile/shareeOne/TEST_FILE_USER_SHARE.dat` should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in shareeOne() [`.../smashbox/lib/oc-tests/test_shareFile.py` at line 162] -- ERROR - sharer - md5 of modified file `.../tmpdir/test_shareFile/sharer/TEST_FILE_MODIFIED_USER_SHARE.dat` did not change: expected `45b565af28a2998fa8d5dae7eb6e660e`, got `45b565af28a2998fa8d5dae7eb6e660e` "md5 of modified file %s did not change: expected %s, got %s" % (fn, md5, actual_md5)) failed in expect_modified() [`.../smashbox/python/smashbox/utilities/__init__.py` at line 670]
 | **fails earlier then without encryption**
`test_shareGroup.py` | :x: 
 | *known to be broken*
`test_sharePermissions.py` | :x: 
 | *known to be broken*
`test_uploadFiles.py` | :x: ERROR - sharer02 - File `.../tmpdir/test_uploadFiles/sharer02/localShareDir/TEST_FILE_NEW_USER_SHARE_1.dat` should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() [`.../smashbox/lib/oc-tests/test_uploadFiles.py` at line 213]
 | **works without encryption**

So the difference is: `test_reshareDir` and `test_uploadFiles` fail, while `test_shareDir` and `test_shareFile` fail earlier.
Not sure how much will be resolved by the fix for https://github.com/owncloud/core/issues/15786 and we are still waiting for @icewind1991 to have a look at that.

**Comment by nickvergessen** [comment]
https://github.com/owncloud/smashbox/pull/70 fixes the encryption specific fails of smashbox.
Once we log in the users after creating them, the keys get generated, so sharing etc don't fail anymore.

New encryption result is then:

Test | Status
---- | -------------
`test_scrapeLogFile.py` | :white_check_mark:
`test_reshareDir.py` | :white_check_mark:
`test_shareDir.py` | :x: same as without
`test_shareFile.py` | :x: same as without
 | :white_check_mark: with https://github.com/owncloud/core/pull/16159
`test_shareGroup.py` | :x: same as without
`test_sharePermissions.py` | :x: same as without
`test_uploadFiles.py` | :white_check_mark:

**Comment by nickvergessen** [comment]
https://github.com/owncloud/smashbox/pull/72 fixes shareDir.py (without and with encryption)
https://github.com/owncloud/smashbox/pull/73 fixes shareGroup.py (without and with encryption)
https://github.com/owncloud/smashbox/pull/74 fixes sharePermissions.py (without encryption)

**Comment by nickvergessen** [comment]
We are now back to green without encryption

**Comment by DeepDiver1975** [comment]
so  i guess we can close this now - thx @nickvergessen for taking care

**Comment by PVince81** [comment]
@nickvergessen did you run them always with `-a` ? Else it will only run the first test suite see https://github.com/cernbox/smashbox/issues/12)

**Comment by nickvergessen** [comment]
No, I run each test case individually https://github.com/owncloud/smashbox/issues/88 (because I get problems otherwise with the rundir not being empty in the beginning, fixed by https://github.com/owncloud/smashbox/pull/78 )
