### ISSUE TITLE
Support/Upgrade timeline

### ISSUE THREAD

**Issue by phsc** [owncloud/core#18864]
Owncloud is a great project, but sometimes it can be hard to keep the overview.
- [ ] IE8/9 Support (see #15567)
- [ ] PHP 5.4 Support (no issue found)
- [ ] Upgrade jQuery to 1.11(legacy stable)/2.1(current stable)/3.0(alpha) (see #14634)
- [ ] Upgrade SabreDAV to 3.0(stable)/3.1(alpha) (see #17039)

Wouldn't it be great to cut all the old pigtails (maybe with Owncloud 9.0)? ;-)

If you think, this issue is useless, please feel free to close it. Otherwise also feel free to add further topics.

**Comment by DeepDiver1975** [comment]
We will not drop PHP 5.4.
Jquery upgrade is related to ie8 death.
Sabre will probably be upgraded with oc9.

No need to track this in issues. Thx
