### ISSUE TITLE
Tracking missing shortcuts

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#19584]
1. The key to a successful interface is to provide several ways to perform specific actions in order to cater for the needs of a broad spectrum of users
2. Advanced users need shortcuts

A sample selection:
- [ ] `ctrl+a` Select all
- [ ] `ctrl+c` Copy selection
- [ ] `ctrl+v` Paste selection
- [ ] `ctrl+x` Cut selection
- [ ] `del` Delete selection
- [ ] `ctrl+f` Puts cursor in search field #18897 
- [ ] `ctrl+z` Undo (a deletion per example)

---

@PVince81 @schiesbn @jancborchardt @henni

**Comment by MorrisJobke** [comment]
cc @owncloud/designers

**Comment by schiesbn** [comment]
We should also think about how to make sure that people can discover those shortcuts. Maybe the settings menu of the files app (bottom left) should have a link "shortcuts" which opens a separate page or a pop-up (similar to the first run wizard) which explains the shortcuts.

**Comment by MorrisJobke** [comment]
> We should also think about how to make sure that people can discover those shortcuts. Maybe the settings menu of the files app (bottom left) should have a link "shortcuts" which opens a separate page or a pop-up (similar to the first run wizard) which explains the shortcuts.

Alternative: Press `?` here on github ;)

**Comment by jancborchardt** [comment]
> We should also think about how to make sure that people can discover those shortcuts.

@schiesbn yeah, but this is a second step. Educating people about common shortcuts is not necessarily our core focus.

I totally agree with @oparoz that ownCloud should support all common shortcuts for copying, pasting, selecting, undo etc like any other file manager and program. Also Ctrl+click and Shift+click for multiselection etc. Really good call!

**Comment by schiesbn** [comment]
> @schiesbn yeah, but this is a second step. Educating people about common shortcuts is not necessarily our core focus.

But a important second step! The best shortcut is useless if nobody knows it.

**Comment by jancborchardt** [comment]
I know, but seeing as very very few other systems do that it’s definitely not the core focus for now. The Gmail & Github examples which @MorrisJobke cites are good to have an overview, but they also need that because they have a bunch of custom ones defined. First goal is to make the common shortcuts (cut, copy, paste, shift-select etc) useful in ownCloud.

**Comment by MorrisJobke** [comment]
Proposed by @pellaeon :+1: 

> Proposed:
`f`: open and focus search bar
`?`: show all shortcuts and help messages

**Comment by Henni** [comment]
@MorrisJobke @pellaeon should the key `F` itself or only in combination with `Ctrl` focus the search bar?
(see the discussions in #18897 and #19212 regarding `Ctrl+F`)

Alternatively we could use the [accesskey attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey). The main problem with accesskey is, that it's inconsistent across browsers (Firefox uses `Alt + Shift + key` while IE, Chrome, Safari use `Alt + key`).

**Comment by pellaeon** [comment]
I read the discussions, I'm also against overwriting browser's built-in feature. Just the key `f` should bring up the search bar. And since `f` isn't used elsewhere as a keyboard shortcut, why not just use it instead of overwriting browser's built-in search and breaking it?

**Comment by stefan-niedermann** [comment]
agree with @pellaeon  and @Henni. Very bad example is Atlassian Confluence: They think they can do it better and what do one get? a animated search bar which tooks seconds to show, which confuses the user by overwriting default and well-known behaviour.
only `f` would be fine.

**Comment by Henni** [comment]
I see one possible issue with `f`:
For example the notes app wouldn't be able to use this shortcut, because it consists of a single large editor.

**Comment by oparoz** [comment]
F is also used in Gallery for full-screen.

**Comment by pellaeon** [comment]
I think keyboard shortcuts should be defined per-app. The `f` I'm proposing is only for Files app.
I believe the search bar is also part of the files app? because I see no search bar in Gallery app. Then there should be no interfering of `f` in Gallery (anyway, each app should define its own shortcut).

Though some global guidelines should be followed, for example `?` should always open the keyboard shortcut help box.

I understand there are currently no stable Javascript API for ownCloud, but anyway we can still implement a library for apps to:
1. easily register and hook keyboard shortcut
2. automatically generate a help screen where all shortcuts are listed

We can also discourage app developers to register certain key combinations that overrides browser behavior by not supporting them or blocking them in the library.

**Comment by pellaeon** [comment]
Oh, and for the Files app, we can add help text inside search bar's placeholder, perhaps making the search bar open by default. (so it can show the placeholder)
Help text: `Click or press f to search`

**Comment by oparoz** [comment]
> I believe the search bar is also part of the files app? because I see no search bar in Gallery app. Then there should be no interfering of f in Gallery (anyway, each app should define its own shortcut).

No, the search bar is supposed to be universal. It's disabled if the app doesn't provide the logic for it.
So it will be confusing if each app offers its own ctrl+f variant.

**Comment by MorrisJobke** [comment]
> Oh, and for the Files app, we can add help text inside search bar's placeholder, perhaps making the search bar open by default. (so it can show the placeholder)

No. It was hidden to not attract as much attention ;)

**Comment by pellaeon** [comment]
@oparoz Is there an API for apps to hook onto the search bar? Are there any apps using it?
For search, I think all apps can use the search bar (with same style) and `f` key, but apps may need their own ways to display search results, for example Music would search over album and track names and show album art as preview, Gallery may show the image as preview. That is, search bar and `f` key convention should be universal, but the search result should be customized per app.

@MorrisJobke I only proposed this to solve the "nobody knows `f` key problem" just in case someone brings it up. I'm fine with the current hidden state though. Also, could you point me to the "search bar should be hidden not to attract attention" discussions, thanks.

**Comment by MorrisJobke** [comment]
> @MorrisJobke I only proposed this to solve the "nobody knows f key problem" just in case someone brings it up. I'm fine with the current hidden state though. Also, could you point me to the "search bar should be hidden not to attract attention" discussions, thanks.

Puh...some time back...let me check if I can find it :P

**Comment by MorrisJobke** [comment]
> Puh...some time back...let me check if I can find it :P

https://github.com/owncloud/core/pull/18573 - damn ... I think it was an offline discussion at the conf and we didn't documented it :(
