### ISSUE TITLE
Meta-Issue for Unified WebDAV

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#20047]
# Resources
- [x] chunked upload - https://github.com/owncloud/core/pull/20118
- [ ] zipped folder download - https://github.com/owncloud/core/pull/24178
- [ ] avatars
- [ ] file previews
- [x] carddav - https://github.com/owncloud/core/pull/20184
- [x] caldav - #20371
- [ ] trashbin - https://github.com/owncloud/core/issues/15646
- [ ] versions - https://github.com/owncloud/core/issues/10571
- [ ] users
- [ ] groups
# General
- [x] List principals in debug mode - https://github.com/owncloud/core/pull/20066
- [x] add new dav endpoint to the capabilities api - https://github.com/owncloud/client/issues/4007#issuecomment-151436693
- [x] update well-known rules in .htaccess - https://github.com/owncloud/core/pull/20585
- [x] Switch to stable sabre before 9.0 release
# Auth
- [ ] public access to files - https://github.com/owncloud/core/pull/19949#issuecomment-150018877
- [x] add group principal to have a reference for group shares - #21540
# Testing
- [x] setup litmus test against v1
- [x] setup litmus test against v2
- [x] setup http://calendarserver.org/wiki/CalDAVTester
- [x] setup/implement additional integration tests (chunked upload etc)
# Implementation
- [ ] cache instances - https://github.com/owncloud/core/pull/19949#discussion_r42982177
- [ ] register all plugins - https://github.com/owncloud/core/pull/19949#discussion_r42982680
- [x] integrate carddav backend with OCP\ContactsManager
# CardDAV / CalDAV
- [x] pre-generate a default addressbook
- [x] pre-generate a default calendar
- [x] contact's birthday calendar
- [ ]  normalize uri's for added calendars
- [ ]  normalize uri's for added addressbooks

**Comment by georgehrke** [comment]
We also need to update the well-known references.

**Comment by georgehrke** [comment]
Another issue we should take care of is proper unicode support (or at least sending proper error responses when users try to create vcards with emojis)

**Comment by DeepDiver1975** [comment]
> Another issue we should take care of is proper unicode support (or at least sending proper error responses when users try to create vcards with emojis)

releated #15660

**Comment by georgehrke** [comment]
@DeepDiver1975 What's the state on caldav sharing and the arbitrary properties backend I suggested?

**Comment by DeepDiver1975** [comment]
> What's the state on caldav sharing

Will be added soonish ....



> arbitrary properties backend I suggested?

already there - https://github.com/owncloud/core/blob/master/apps/dav/lib/server.php#L78-L84

**Comment by PVince81** [comment]
Let's continue this great work in 9.1.

Any boxes to tick ?

**Comment by DeepDiver1975** [comment]
> Let's continue this great work in 9.1.

agreed

**Comment by DeepDiver1975** [comment]
> Any boxes to tick ?

birthday calendar has open pr - but I guess we move this to 9.1 as well

**Comment by DeepDiver1975** [comment]
move to 9.2

**Comment by PVince81** [comment]
Added trashbin, versions, users, groups to the main ticket.

Also see https://github.com/owncloud/core/issues/12543

**Comment by PVince81** [comment]
@DeepDiver1975 any further plans for 10.0 ?

The only one I see is the almost finished ZIP plugin: https://github.com/owncloud/core/pull/24178

Else I'd move to backlog for now...

**Comment by DeepDiver1975** [comment]
we can close this one ....
