### ISSUE TITLE
File Comments WebDAV adjustments

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#20266]
Contributes to #16328 

* [X] a property that holds the number of comments for a specific file. Must be requested explicitly. #21967
* [X] optional, a property that holds the number of unread comments for a specific file and user. Must be requested explicitly. #21967
* [x] ~~optional, a property that holds the number of unread comments for a specific file, user and timestamp. Must be requested explicitly.~~ cannot pass parameters (timestamp) in PROPFIND
* [X] optional, a property that links to the File Comments resource #21967

@nickvergessen @blizzz @DeepDiver1975 @jancborchardt
