### ISSUE TITLE
Code Signing for 9.0 - Meta issue with steps

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#20295]
- [x] Add verification code foundation (https://github.com/owncloud/core/pull/20285)
- [x] Add nag screen in case the code check fails to ensure that administrators are aware of this.
- [x] Add code verification also to OCC upgrade and unify display code more.
- [x] Add enforced code verification to apps shipped from the appstore with a level of "official"
- [x] Add enfocrced code verification to apps shipped from the appstore that were already signed in a previous release
- [x] Add some developer documentation on how devs can request and use their own certificate
- [x] Check when installing ownCloud
- [x] Add support for CRLs to allow revoking certificates

**Comment by karlitschek** [comment]
We need input from @jancborchardt for user and developer experience and @jospoortvliet for communication

**Comment by jancborchardt** [comment]
Yup, I’ll go through the flow and admin-facing elements of this with @LukasReschke next week.

@LukasReschke if there are any screenshots or similar already, let me know.

**Comment by LukasReschke** [comment]
Some documentation at https://github.com/owncloud/documentation/pull/1924 including some screenshots.
