### ISSUE TITLE
File Comments Interfaces and Implementations

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#20409]
Contributes to #16328 

* [x] a manager interface, with methods to take care or creating, modifying, deleting and fetching comments (https://github.com/owncloud/core/pull/20562)
* [x] a global CommentsManager implementing that interface (#20775)
* [x] a possibility to override the CommentsManager by an own implementation, configurable in config.php (#20775)
* [X] when a file gets deleted, all comments connected to shall also be deleted #22139 
* [x] when a user gets deleted, references to the user will be deleted and replaced with a "Deleted user", by using a special actor type. The comments themselves will be kept. (#20775)
* [X] background job to clean up comments referring to deleted files #22139

**Comment by blizzz** [comment]
added one todo for background cleanup job

**Comment by blizzz** [comment]
one ToDo (cleanup background job) is still open

**Comment by MorrisJobke** [comment]
#22139 is merged
