### ISSUE TITLE
Comments DAV mark as read methods

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#22010]
We need to have an WebDAV API possibility to mark comments as read. The methods to the ICommentsManager are added here https://github.com/owncloud/core/pull/21967#issuecomment-176441845

As of discussion with @PVince81 the plan is as follow:
* [X] PROPPATCH against an EntityCollection (aka specific file collection holding comments) to set the read marker to a given DateTime (#22059)
* [ ] ~~PROPPATCH against an EntityTypeCollection (aka files collection, holding EntityCollections) to set the read marker for every file to a given DateTime #22077~~ not required for 9.0, PR exists for 9.1.

Additionally a comment node should send out a property stating whether it was read or not so that a client can format it appropriately.

* [X] PROPFIND and REPORT on a CommentNode add a <ocunread/> property which is either true of false, and relative to the logged in user. (#22059)

In future we can extent with
*  PROPPATCH  against the Comments RootCollection to set everything as read
if it turns out to be useful. Currently not needed as we only do comments on files.

**Comment by PVince81** [comment]
> PROPPATCH against an EntityTypeCollection (aka files collection, holding EntityCollections) to set the read marker for every file to NOW.

to a given datetime I'd say. A PROPPATCH might always need a value to set.

**Comment by blizzz** [comment]
fine with me

**Comment by blizzz** [comment]
Will be completed solved with #22077
