### ISSUE TITLE
Sharing 2.0 internals

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#22209]
After https://github.com/owncloud/core/issues/19331 we still need to migrate some internal parts. This ticket will keep track of those tasks. After this we should be able to drop more legacy code!
#### Required
- [ ] Migrate `apps/files_share/lib` to the share manager
  - [ ] helper.php => setupfromtoken: https://github.com/owncloud/core/pull/24383
  - [x] maintainer.php => kill: https://github.com/owncloud/core/pull/26612
  - [x] mountprovider.php
  - [x] sharedmount.php
  - [x] sharedstorage.php (https://github.com/owncloud/core/pull/23919)
  - [x] updater.php
- [x] Migrate hooks from \OC\Share\Hooks (lib/private/share/hooks.php) (https://github.com/owncloud/core/pull/23773, https://github.com/owncloud/core/pull/23841 https://github.com/owncloud/core/issues/23856 https://github.com/owncloud/core/pull/23973)
- [x] Move dav app over to new share code ( #23736 )
- [ ] Move notify recipient over from ajax/\* to sharemanager
- [x] Refactor shared storage ( @icewind1991 ) as in https://github.com/owncloud/core/pull/12086 (https://github.com/owncloud/core/pull/23919)
- [ ] Allow federation app to be disabled (so fix the factory)
#### More:
- [ ] Federated sharing accepting etc
- [ ] Cleanup exceptions
- [x] Properly translate all errors in the OCS Share API... (https://github.com/owncloud/core/pull/24027)
  - Using https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4 makes most sense
- [ ] Migrate `apps/files_sharing/lib/external` to the federated file sharing app
- [x] migrate OCS API for federated sharing to the federated file sharing app https://github.com/owncloud/core/pull/32086
- [x] migrate federated share settings from `files_sharing` to `federatedfilesharing` (PR: https://github.com/owncloud/core/pull/24073)

For 9.2:
- [ ] Display link reshares properly in webUI ~~https://github.com/owncloud/core/issues/22327~~ https://github.com/owncloud/core/issues/29519

CC: @PVince81 @schiesbn

**Comment by DeepDiver1975** [comment]
We might even take advantage of this and analyze the filesystem initialization.
We have to be as lazy as possible ...

**Comment by schiesbn** [comment]
> We might even take advantage of this and analyze the filesystem initialization.
We have to be as lazy as possible ...

Good point, we could for example try to only load the share mount points of the current folder. If people have a lot of shares and not all in the root folder this could result in a nice performance improvement... Just thinking.

**Comment by MTRichards** [comment]
Estimate: 2 weeks.

**Comment by rullzer** [comment]
@icewind1991 can you help with the shared storage PR? See https://github.com/owncloud/core/tree/cyclyc-share-dep-example

**Comment by rullzer** [comment]
I've been thinking about moving over the hooks.

Way to go (from my POV) is:

1. Hook is fired
2. Hook somehow calls the sharemanager with a specific function
3. Sharemanager calls a function on each shareProvider

Any objections or other suggestsions? @schiesbn @DeepDiver1975

**Comment by rullzer** [comment]
This was pushed back to 9.2

**Comment by PVince81** [comment]
> We might even take advantage of this and analyze the filesystem initialization.
> We have to be as lazy as possible ...

It is now and it caused a lot of pain https://github.com/owncloud/core/issues/25557

**Comment by PVince81** [comment]
Strange, there is no entry in this list for "kill share.php"

**Comment by PVince81** [comment]
- [ ] "kill share.php" !

- [ ] make share backends use the new API or kill these altogether:
```
apps/files_sharing/lib/API/Sharees.php:458:                     $backend = Share::getBackend($itemType);
lib/private/Share/Helper.php:49:                $backend = \OC\Share\Share::getBackend($itemType);
lib/private/Share/Share.php:635:                $backend = self::getBackend($itemType);
lib/private/Share/Share.php:936:                self::getBackend($itemType);
lib/private/Share/Share.php:1597:               if (isset(self::$backendTypes[$itemType]) && (!self::getBackend($itemType) instanceof \OCP\Share_Backend_Collection || $itemType != 'folder')) {
lib/private/Share/Share.php:1683:               $backend = self::getBackend($itemType);
lib/private/Share/Share.php:1974:                                       if (($collectionBackend = self::getBackend($row['item_type']))
lib/private/Share/Share.php:2037:                                       $collectionBackend = self::getBackend($row['item_type']);
lib/private/Share/Share.php:2061:                       $collectionBackend = self::getBackend('folder');
lib/private/Share/Share.php:2338:               $backend = self::getBackend($itemType);
lib/private/Tags.php:130:                       $this->backend = \OC\Share\Share::getBackend($this->type);
lib/public/Share.php:371:               return \OC\Share\Share::getBackend($itemType);
core/ajax/share.php:327:                                $backend = \OCP\Share::getBackend((string)$_GET['itemType']);
```
See https://github.com/owncloud/core/issues/26607

**Comment by PVince81** [comment]
- [ ] get rid of all oc_filecache usage (or at least make it customizable), see https://github.com/owncloud/core/issues/26607

**Comment by PVince81** [comment]
Looks like the contacts app still uses `\OCP\Share::registerBackend()` so we can't kill this completely.
But we can at least get rid of the File and Folder backends.

**Comment by PVince81** [comment]
- [ ] `OC\Share::getUsersSharingFile()` move to share provider or manager ?

**Comment by PVince81** [comment]
- [ ] make sure unshare from self still fires old hooks

**Comment by PVince81** [comment]
- [ ] remove hard dependency of files_sharing of `OCA\FederatedFileSharing\FederatedShareProvider`

**Comment by PVince81** [comment]
PR for removing old share backends, seems to work so far: https://github.com/owncloud/core/pull/26608

**Comment by PVince81** [comment]
- [ ] `OCP\Share::getItemShared()` needs a Share 2.0 replacement. Looks like `Share20\Manager::getSharesByPath()` is empty ??

Making it call the provider's `getSharesByPath()` should be doable but I'm more worried about pagination.

**Comment by PVince81** [comment]
looks like it's more than that. If one passes `includeCollections' it also needs to check all parents to see if they have shares.
- [ ] alternative to `OCP\Share::getItems` where `includeCollections` is specified: get shares for the given folder, then do the same for every parent. Could be a new utility method in `ShareManager`

**Comment by PVince81** [comment]
- [ ] setupfromtoken: https://github.com/owncloud/core/issues/24383
- [ ] publicpreview.php: https://github.com/owncloud/core/pull/26611

**Comment by PVince81** [comment]
- [ ] optimize retrieval of share-types properties: https://github.com/owncloud/core/issues/26641

**Comment by VicDeo** [comment]
ticked "migrate federated share settings from files_sharing to federatedfilesharing" as PR was merged long time ago
