### ISSUE TITLE
Meta: Security tickets for 9.0

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#22288]
- [x] Do a security check on the new APIs (https://github.com/owncloud/core/issues/22282)
- [x] Do a security check on the new apps
  - [x]  https://github.com/owncloud/enterprise/issues/1085
  - [x] https://github.com/owncloud/core/issues/22287
- …

**Comment by LukasReschke** [comment]
Moving to 9.0.1 due to EE apps that are only to be released then.
