### ISSUE TITLE
App Update

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#24198]
# ToDos:
- [x] Add a background repair step which can be executed after upgrade during live operations
- [x] Add a progress based feedback for longer running repair steps
- [ ] cleanup emitter vs. EventDispatcher (tech dept)
- [x] enhance OCP\IRepairStep to hold feedback methods
- [x] define backgroudjobs in info.xml @icewind1991 - does this somehow collide with your work?
- [ ] kill https://github.com/owncloud/core/blob/v9.0.1/lib/private/updater.php#L400

**Comment by icewind1991** [comment]
> define backgroudjobs in info.xml @icewind1991 - does this somehow collide with your work?

The background jobs that would be defined in info.xml would be seperate from the job queue (job queue is for one-off async work)

**Comment by DeepDiver1975** [comment]
Just to be sure - we only have one queue and there is nothing going to change with this respect thinking about the executor mechanism you are building for 9.1

So no matter if the jobs are one shot of cron like they live in the same queue and will be equally executed amongst all job executors.

So as soon as a background job is defined in info.xml - we should throw it onto the job queue.

**Comment by icewind1991** [comment]
Background jobs (currently defined in update/install.php, to be moved to info.xml) execution will stay the same (cron.php) and is meant for periodic background jobs (news app sync, syncing of remote system address books, etc)

Job queue will get it's new fancy executor for 9.1 and is meant for one-off async work that is triggered by some action (trashbin expiry)

**Comment by DeepDiver1975** [comment]
Hmm .. I see no need to separate them in terms of who is executing them.

**Comment by DeepDiver1975** [comment]
Mainly done - remaining tasks can be ignored for now -> close
