### ISSUE TITLE
Add hardening checklist in admin section

### ISSUE THREAD

**Issue by butonic** [owncloud/core#26059]
- [ ] standalone app or part of core?
- [ ] "hardening" section in admin settings with checklist like UI
- [ ] move existing setup checks to app
- [ ] add checks:
  - [ ] config.php readonly
  - [ ] data outside web root
  - [ ] files not owned by apache/www-data user/group
  - [ ] don't run git version
  - [ ] all updates installed

cc @PVince81 @DeepDiver1975 @pmaier1

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).
