### ISSUE TITLE
fileid of oc_filecache in danger of hitting max value

### ISSUE THREAD

**Issue by schnidrig** [owncloud/core#26901]
### Database

5 node galera cluster with mariadb.
maxscale with read/write splitter.

### Expected behaviour

virtually unlimited lifetime of oc service

### Actual behaviour

the primary key of the filecache table is in danger of overflowing.
At that point our oc instance will refuse any addition of new files.

### Problem description 

	MariaDB [owncloud]> show create table oc_filecache\G
	*************************** 1. row ***************************
		   Table: oc_filecache
	Create Table: CREATE TABLE `oc_filecache` (
	  `fileid` int(11) NOT NULL AUTO_INCREMENT,
	  `storage` int(11) NOT NULL DEFAULT '0',
	  `path` varchar(4000) COLLATE utf8_bin DEFAULT NULL,
	  `path_hash` varchar(32) COLLATE utf8_bin NOT NULL DEFAULT '',
	  `parent` int(11) NOT NULL DEFAULT '0',
	  `name` varchar(250) COLLATE utf8_bin DEFAULT NULL,
	  `mimetype` int(11) NOT NULL DEFAULT '0',
	  `mimepart` int(11) NOT NULL DEFAULT '0',
	  `size` bigint(20) NOT NULL DEFAULT '0',
	  `mtime` int(11) NOT NULL DEFAULT '0',
	  `storage_mtime` int(11) NOT NULL DEFAULT '0',
	  `encrypted` int(11) NOT NULL DEFAULT '0',
	  `unencrypted_size` bigint(20) NOT NULL DEFAULT '0',
	  `etag` varchar(40) COLLATE utf8_bin DEFAULT NULL,
	  `permissions` int(11) DEFAULT '0',
	  PRIMARY KEY (`fileid`),
	  UNIQUE KEY `fs_storage_path_hash` (`storage`,`path_hash`),
	  KEY `fs_parent_name_hash` (`parent`,`name`),
	  KEY `fs_storage_mimetype` (`storage`,`mimetype`),
	  KEY `fs_storage_mimepart` (`storage`,`mimepart`),
	  KEY `fs_storage_size` (`storage`,`size`,`fileid`)
	) ENGINE=InnoDB AUTO_INCREMENT=252069614 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
	1 row in set (0.00 sec)

The primary key is a **signed** integer with max value of 2147483647.

	MariaDB [owncloud]> select max(fileid), count(fileid) from oc_filecache;
	+-------------+---------------+
	| max(fileid) | count(fileid) |
	+-------------+---------------+
	|   252065705 |      60772002 |
	+-------------+---------------+

We have 60 mio files and the fileid is currently at 250 mio. 
4 months ago that counter was at 146 mio. During the last 4 months we had a 3 node galera cluster.
That means 100 Mio increase in 4 months; with our new 5 node cluster instead of a old 3 nodes cluster that would have been a: 100/3*5 = 170 mio increase. Therefore we'll hit the 2147483647 boundary in about 3.5 years with the current user base and setup. However, given the growth rate of our service, I'd estimate that to be more something like 2 years at best.

Considering, that enterprise customers (at least those I know of) usually are one year behind the current release, I think it is about time to fix this in the db.

Please consider changing the fileid to BIGINT. Or at the very least make it **unsigned**.

More of a hack than a workaround would be to change the auto_increment settings.

	MariaDB [owncloud]> show variables like '%auto_increment%';
	+------------------------------+-------+
	| Variable_name                | Value |
	+------------------------------+-------+
	| auto_increment_increment     | 5     |
	| auto_increment_offset        | 1     |
	| wsrep_auto_increment_control | ON    |
	+------------------------------+-------+

But of course, that would give me tons of other head aches.

**Comment by PVince81** [comment]
Uh oh...

@butonic @DeepDiver1975 @PhilippSchaffrath

**Comment by butonic** [comment]
I am trying to store metadata via extended attributes, which makes me wish the primary key of the table was (storage, fileid) and we were referencing the storage id along with the file id throughout the code. They map to device id and inode pretty well. If we touch the filecache table we should collect other requirements. Currently it is impossible to resolve the owner to a fileid by using sql. The oc storages table might contain a hashed id which causes us to iterate over all user for certain file actions like trash and versions expiry (instead of looking at the files directly). 
Things that come to mind:
- [ ] use bigint for fileid
- [ ] rename oc_filecache to oc_fileindex because it is NOT a cache: the content cannot be rebuilt without losing the fileids & etags.
- [ ] rename storage to storageid
- [ ] make (storageid, fileid) primary key ... and use this combo throughout the api
- [ ] remove unused columns (encryption no longer needs all of them AFAICT)
- [ ] Instead of doing the migration during upgrade we can create the new table and do a user by user migration?

**Comment by PVince81** [comment]
@butonic this is the wrong ticket to discuss this, it will likely get lost. Maybe post here instead: https://github.com/owncloud/core/issues/12487 (or find or create a matching ticket).

Yes for using bigint for fileid if that can fix the issue in this one ticket.

**Comment by Helios07** [comment]
It is even worse for us:
```
MariaDB [rwth_aachen]> select max(fileid), count(fileid) from oc_filecache;
+-------------+---------------+
| max(fileid) | count(fileid) |
+-------------+---------------+
|   529100321 |      51808811 |
+-------------+---------------+
```

(and we split our users to different instances already)

**Comment by PVince81** [comment]
We usually don't change DB schemas in a minor version, but might need to do an exception here... @felixboehm @DeepDiver1975 @butonic 

I suggest to provide a PR for a quickfix that changes the column type to bigint (not sure about performance impact here during upgrade...) and address @butonic's other points separately.

**Comment by davidjericho** [comment]
This one hadn't crossed my mind, but it's definitely a problem for us too.

```MariaDB [owncloudstable82]> select max(fileid), count(fileid) from filecache;
+-------------+---------------+
| max(fileid) | count(fileid) |
+-------------+---------------+
|   676222618 |      45597155 |
+-------------+---------------+
```

It'll be a huge problem with our planned growth this year.

**Comment by butonic** [comment]
Um ... this will require us to alter the sharing table and probably other tables that reference the fileid ... foreign keys anyone?

**Comment by PVince81** [comment]
Ref: foreign keys https://github.com/owncloud/core/issues/13143

Indeed, not only the oc_filecache will be affected.

Other tables that come to mind:
- oc_vcategory_to_object which can use fileid as the object id
- oc_share, the file_source and item_source columns
- oc_properties will use fileid in the future: https://github.com/owncloud/core/issues/25563
- oc_systemtag_object_mapping
- oc_mounts.root_id
- oc_comments.object_id
- activity table also uses fileid somewhere
- ...

**Comment by PVince81** [comment]
Need to also evaluate the impact of bigger values on the clients especially Javascript.

**Comment by PVince81** [comment]
Or use strings for ids: https://github.com/owncloud/core/issues/22330. Not sure about the performance impact with indices though.

**Comment by butonic** [comment]
just using bigint in dhe db is not enuogh. we neet to check if the code does cast to int, eg: https://github.com/owncloud/core/blob/master/lib/private/Files/Cache/Cache.php#L145

+1 for strings for ids and get this right.

**Comment by PVince81** [comment]
setting to triage, needs proper design + scheduling

@pmaier1 @felixboehm

**Comment by wschaft** [comment]
Uh oh...

We need a fix ASAP:

MariaDB [owncloud]> select max(fileid), count(fileid) from oc_filecache;
+-------------+---------------+
| max(fileid) | count(fileid) |
+-------------+---------------+
|  2147483647 |     160067265 |
+-------------+---------------+

**Comment by PVince81** [comment]
Reproduction steps:

1. Setup OC (I used 8.2 locally)
1. insert a dummy entry in the DB with a high fileid, using a non-existing storage id: `insert into oc_filecache (fileid, storage, path) values (2147483646, 60000, '');`
1. try creating a few folders or uploading a few files to make it exceed max int

Expected: no limit
Actual: `An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params [\"1\", \"2\", 1499626958, -1, \"59627dce53dca\", 1499626958, 31, \"2\", \"f7723ab8c8e52c6c0711e88e739400f3\", \"files\\\/x\", \"x\", \"1\", \"1\", \"f7723ab8c8e52c6c0711e88e739400f3\"]:\n\nSQLSTATE[22003]: Numeric value out of range: 167 Out of range value for column 'fileid' at row 1`

**Comment by PVince81** [comment]
Apparently file/folder entries get created on-disk but not in DB. This means that after switching to bigint, will need to run `occ files:scan --all` to make it detect all the created "ghost" files that weren't indexed.

**Comment by PVince81** [comment]
@butonic I checked with a debugger, reading a bigint value from DB with PHP at the code in https://github.com/owncloud/core/blob/master/lib/private/Files/Cache/Cache.php#L140.

The debugger shows that the fileid stayed the same for a value of `2147483659`.

**Comment by PVince81** [comment]
seems to also work for values bigger than 32 bit max-int on PHP 5.6:
before cast:
```
$data['fileid'] = (string[10]) '4500000004';
```
after cast:
```
$data['fileid'] = (int) '4500000004';
```

so if all is well we might not require PHP code changes...

**Comment by PVince81** [comment]
well, unless it breaks on 32 bit systems... I tested on a 64 bit machine.

- [ ] check (int) cast of big ints on 32 bit systems

**Comment by PVince81** [comment]
also tested with values close to ~~the heat death of the universe~~ PHP_INT_MAX:
`insert into oc_filecache (fileid, storage, path) values (9223372036854770000, 60002, '');`

on 64 bit system the PHP cast to `int` still works, so we're good at least for those.

**Comment by PVince81** [comment]
this makes OC work for me on 64 bit systems:
```
# File cache + parent relationship
ALTER TABLE `oc_filecache` CHANGE `fileid` `fileid` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `oc_filecache` CHANGE `parent` `parent` BIGINT NOT NULL DEFAULT '0';
# Shares
ALTER TABLE `oc_share` CHANGE `file_source` `file_source` BIGINT NULL;
# Favorites
ALTER TABLE `oc_vcategory_to_object` CHANGE `objid` `objid` BIGINT NOT NULL;
# Activities
ALTER TABLE `oc_activity` CHANGE `object_id` `object_id` BIGINT NOT NULL DEFAULT '0';
```

**Comment by PVince81** [comment]
Development plan:

### Phase 1: bigint-ify fileid column and related columns containing a fileid

- [ ] 10.0.3:
    - [ ] write migration to convert the fileid columns and related to bigint
    - [ ] 9.1->10.0 update must work as well, the migration above will d
    - [ ] make sure the 9.0->10.0 update path covers this as well
    - [ ] make sure the 8.2->10.0 update path covers this as well, WIP here https://github.com/owncloud/core/pull/28256
- [ ] 9.1: adjust db_structure.xml to convert fileid columns and related to bigint
- [ ] 9.0: adjust db_structure.xml to convert fileid columns and related to bigint
- 8.2 is EOL, no update, sorry

### Phase 2: adjust all other ids

I'd say this is only for 10.0 or later versions.

- [ ] make a list of all tables with numeric ids and write migrations to adjust these to bigint

**Comment by PVince81** [comment]
first need to test on a 32 bit system, with a bit of luck maybe PHP 5.6 already handles this correctly...

**Comment by PVince81** [comment]
@VicDeo please take over, phase 1

**Comment by individual-it** [comment]
1. installed oC on RPi from current github master
2. uploaded some files
```
mysql> select max(fileid), count(fileid) from oc_filecache;
+-------------+---------------+
| max(fileid) | count(fileid) |
+-------------+---------------+
|          32 |            32 |
+-------------+---------------+
```

```
mysql> select fileid,parent,path from oc_filecache;
+--------+--------+--------------------------------------------+
| fileid | parent | path                                       |
+--------+--------+--------------------------------------------+
|      1 |     -1 |                                            |
|      2 |      1 | cache                                      |
|      3 |      1 | files                                      |
|      4 |      3 | files/welcome.txt                          |
|      5 |     -1 |                                            |
|      6 |      5 | avatars                                    |
|      7 |      6 | avatars/21                                 |
|      8 |      7 | avatars/21/23                              |
|      9 |      8 | avatars/21/23/2f297a57a5a743894a0e4a801fc3 |
|     10 |      1 | thumbnails                                 |
|     11 |     10 | thumbnails/4                               |
|     12 |     11 | thumbnails/4/2048-2048-max.png             |
|     13 |     11 | thumbnails/4/39-39.png                     |
|     14 |      3 | files/block-aligned.txt                    |
|     15 |      3 | files/block-aligned-plus-one.txt           |
|     16 |      3 | files/lorem.txt                            |
|     17 |      3 | files/lorem-big.txt                        |
|     18 |     10 | thumbnails/14                              |
|     19 |     10 | thumbnails/16                              |
|     20 |     18 | thumbnails/14/2048-2048-max.png            |
|     21 |     19 | thumbnails/16/2048-2048-max.png            |
|     22 |     18 | thumbnails/14/39-39.png                    |
|     23 |     19 | thumbnails/16/39-39.png                    |
|     24 |     10 | thumbnails/15                              |
|     25 |     24 | thumbnails/15/2048-2048-max.png            |
|     26 |     24 | thumbnails/15/39-39.png                    |
|     27 |     10 | thumbnails/17                              |
|     28 |     27 | thumbnails/17/2048-2048-max.png            |
|     29 |     27 | thumbnails/17/39-39.png                    |
|     30 |      3 | files/folder-INT                           |
|     31 |     30 | files/folder-INT/lorem.txt                 |
|     32 |     30 | files/folder-INT/lorem-big.txt             |
|     33 |     10 | thumbnails/31                              |
|     34 |     33 | thumbnails/31/2048-2048-max.png            |
|     35 |     33 | thumbnails/31/39-39.png                    |
|     36 |     10 | thumbnails/32                              |
|     37 |     36 | thumbnails/32/2048-2048-max.png            |
|     38 |     36 | thumbnails/32/39-39.png                    |
+--------+--------+--------------------------------------------+
38 rows in set (0.00 sec)
```

4. set `insert into oc_filecache (fileid, storage, path) values (2147483646, 60000, '');`
5. can upload 1 more file, after that getting "Server Error" message
6. run
```
ALTER TABLE `oc_filecache` CHANGE `fileid` `fileid` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `oc_filecache` CHANGE `parent` `parent` BIGINT NOT NULL DEFAULT '0';
ALTER TABLE `oc_share` CHANGE `file_source` `file_source` BIGINT NULL;
ALTER TABLE `oc_vcategory_to_object` CHANGE `objid` `objid` BIGINT NOT NULL;
INSERT into oc_filecache (fileid, storage, path) values (9223372036854770000, 60002, '');
```
```
mysql> select max(fileid), count(fileid) from oc_filecache;
+---------------------+---------------+
| max(fileid)         | count(fileid) |
+---------------------+---------------+
| 9223372036854770000 |            41 |
+---------------------+---------------+
1 row in set (0.01 sec)
```
7. upload a file
```
select fileid,parent,path from oc_filecache;
.......
| 9223372036854770000 |          0 |                                            |
| 9223372036854770001 |          3 | files/filewithhugeid.txt                   |
| 9223372036854770002 |         10 | thumbnails/2147483647                      |
| 9223372036854770003 | 2147483647 | thumbnails/2147483647/2048-2048-max.png    |
| 9223372036854770004 | 2147483647 | thumbnails/2147483647/39-39.png            |
+---------------------+------------+--------------------------------------------+
```
8. create a folder
```
select fileid,parent,path from oc_filecache;
.......
|                  38 |     36 | thumbnails/32/39-39.png                    |
|          2147483646 |      0 |                                            |
| 9223372036854770000 |      0 |                                            |
| 9223372036854770001 |      3 | files/filewithhugeid.txt                   |
| 9223372036854770002 |     10 | thumbnails/2147483647                      |
| 9223372036854770005 |      3 | files/folderwithhugeid                     |
+---------------------+--------+--------------------------------------------+
```

9. place file in new folder (something is wrong here, but file can be accessed by web UI)
```
select fileid,parent,path from oc_filecache;
.......
| 9223372036854770000 |          0 |                                            |
| 9223372036854770001 |          3 | files/filewithhugeid.txt                   |
| 9223372036854770002 |         10 | thumbnails/2147483647                      |
| 9223372036854770005 |          3 | files/folderwithhugeid                     |
| 9223372036854770007 | 2147483647 | files/folderwithhugeid/filewithhugeid.txt  |
| 9223372036854770008 | 2147483647 | thumbnails/2147483647/2048-2048-max.png    |
| 9223372036854770009 | 2147483647 | thumbnails/2147483647/39-39.png            |
+---------------------+------------+--------------------------------------------+
```
10. try to delete file that was created before change to bigint -> file gone but not in "deleted files"
```
select fileid,parent,path from oc_filecache;
.......
|                  16 | 2147483647 | files_trashbin/files/lorem.txt.d1499685764 |
......
| 9223372036854770010 |          1 | files_trashbin                             |
| 9223372036854770011 | 2147483647 | files_trashbin/files                       |
| 9223372036854770012 | 2147483647 | files_trashbin/versions                    |
| 9223372036854770013 | 2147483647 | files_trashbin/keys                        |
+---------------------+------------+--------------------------------------------+
```
11. try to delete folder that was created after change to bigint -> does not delete its still there after reload
12. try to delete file that was created after change to bigint -> not possible. trying to select "filewithhugeid.txt" in WebUI will select "folderwithhugeid"

**Comment by VicDeo** [comment]
@individual-it changing schema is not enough. 
Doctrine maps `bigint` fields onto PHP `string` type so all strict comparisons will be evaluated to `false`.
...and nowadays it's a fashion to have strict comparisons everywhere.

**Comment by individual-it** [comment]
@VicDeo yes, we might have the same problems here https://github.com/owncloud/core/pull/28067 see https://github.com/owncloud/core/pull/28067#issuecomment-306768782 but there the situation is different because we cast everything to int, and there is no internal increment because its time.
I've run the tests above because @PVince81 asked me to try it on a 32bit system

**Comment by VicDeo** [comment]
#### core repo - core
- oc_mounts 
 --  root_id
- oc_filecache
 -- fileid
 -- parent
- oc_share
 -- file_source

#### core repo - apps
**dav**
- oc_properties
-- id
-- fileid


**federatedfilesharing**
- oc_federated_reshares
-- share_id
-- remote_id

**files_sharing**
- oc_share_external
-- id
-- remote_id

**files_trashbin**
- oc_files_trash
-- auto_id

**Comment by felixboehm** [comment]
please also have look into calendar and contacts.

**Comment by PVince81** [comment]
@VicDeo how far are we from completion ? Have the backports to stable10 been done everywhere ?

**Comment by VicDeo** [comment]
Phase 1
- [x] core master https://github.com/owncloud/core/issues/28364
- [ ] core stable10 https://github.com/owncloud/core/issues/28581
- [ ] activity master https://github.com/owncloud/activity/issues/584
- [ ] activity stable10
-  [x] files_antivirus master https://github.com/owncloud/files_antivirus/issues/165
-  [ ] files_antivirus stable10
- [x] search_lucene master https://github.com/owncloud/search_lucene/issues/127
- [ ] search_lucene stable10
- [x] search_elastic master https://github.com/owncloud/search_elastic/issues/19
- [ ] search_elastic stable10
- [x] richdocuments master https://github.com/owncloud/richdocuments/issues/184
- [ ] richdocuments stable10 
- [x] music master https://github.com/owncloud/music/issues/569
- [ ] music stable10

**Comment by PVince81** [comment]
We still need to think of:

⚠️ make a decision and sort out the 32-bit system issue

Apparently some things already broke on 32-bit systems due to casting of the size column which was already a bigint a long time ago: https://github.com/owncloud/core/issues/28275

**Comment by PVince81** [comment]
Had a chat with @felixboehm and we'll only make sure that the bigint changes do not break OC completely on 32-bit systems for smaller values. However they will be no guarantee that values bigger than 32-bit are properly supported. So people with Rasperry Pis should still be able to use ownCloud fine assuming they don't scale to huge numbers.

Raised QA ticket to retest 10.0.3 on 32-bit here https://github.com/owncloud/QA/issues/476

**Comment by PVince81** [comment]
@VicDeo are we done with phase 1?

**Comment by VicDeo** [comment]
@PVince81 in general yes, but richdocuments and music should be ported to migrations for completion.
And probably branching is needed to keep non-bigintified versions that are compatible with OC below 10.0.3

**Comment by PVince81** [comment]
moving to "planned" for second phase.

**Comment by ckamm** [comment]
@PVince81 What's the effect on the full id of this change? Currently 'getFileId()' in `apps/dav/lib/Connector/Sabre/Node.php` still does `$id = sprintf('%08d', $this->info->getId());` - so I assume the zero-padding to 8 digits continues, but full ids will now increase in width when the numeric id exceeds 8 digits. 

This works for the desktop client (takes all digits until first non-numeric character).

**Comment by PVince81** [comment]
@ckamm we should probably get rid of that weird compound id with padding and move to "oc:id" and have the instance id part exposed through the capabilities API ? (separate ticket)

**Comment by phil-davis** [comment]
8 digits is only 99,999,999 = 100 million minus 1. 32 bit numbers anyway go to around 2,000,000,000 (signed) or 4,000,000,000 (unsigned) and thus would already be using 9 or 10 digits anyway (for installs with > 99,999,999 ids). So the 8-digit thing should be an existing "feature" regardless of 54-bit changes.

**Comment by ckamm** [comment]
@phil-davis Good point.

@PVince81 Currently oc:id is the compound id and oc:fileid is the numeric one (opposite to the code in Node.php). We could start deprecating oc:id, the cost would be significant migration work in the client. I agree about moving this discussion to a separate ticket.

The bigint change looks good from the desktop client's point of view.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/29437 to follow up with phase 2 and other ids.

All the main ids (fileids and activity table ids) have been adjusted already, closing.
