### ISSUE TITLE
General design / UX issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27578]
Listing these here to be tackled in one go instead of individually:

- [ ] missing focus style on radio buttons: https://github.com/owncloud/core/issues/15983
- [ ] missing label in in device name textbox: https://github.com/owncloud/core/issues/24808
- [ ] system tags missing label: https://github.com/owncloud/core/issues/23627
- [ ] system tag deletion tooltip stays: https://github.com/owncloud/core/issues/23639
- [ ] dancing links in sidebar: https://github.com/owncloud/core/issues/23429
- [ ] install dialog jump when switching DB type: https://github.com/owncloud/core/issues/16079
- [ ] trashbin bkg icon with Edge: https://github.com/owncloud/core/issues/24865
- [ ] grey stars in Edge when unfavoriting: https://github.com/owncloud/core/issues/22188
- [ ] some tooltips do not disappear: https://github.com/owncloud/core/issues/25220
- [ ] untranslated message in encryption recovery key process: https://github.com/owncloud/core/issues/25752
- [ ] fix context menu position in public link page and mobile mode: https://github.com/owncloud/core/issues/25728

- [ ] set as favorite reloads sidebar: https://github.com/owncloud/core/issues/19274
- [ ] don't reload sidebar when clicking on already selected file: https://github.com/owncloud/core/issues/22488

**Comment by PVince81** [comment]
- [ ] controls bar width calculation: https://github.com/owncloud/core/issues/22301
- [ ] login form positioning on narrow window: https://github.com/owncloud/core/issues/24977
- [ ] overlap of sharee name and file name: https://github.com/owncloud/core/issues/19790

- [ ] positioning of UI elements on the profile/avatar section: https://github.com/owncloud/core/issues/23950
- [ ] ctrl+click on app icon keeps spinner: https://github.com/owncloud/core/issues/24185
- [ ] apps page string length issues: https://github.com/owncloud/core/issues/27564
- [ ] animation of sidebar doesn't work: https://github.com/owncloud/core/issues/15308

**Comment by PVince81** [comment]
@felixheidecke @davitol let's use this ticket for small / easy / trivial styling issues or things like tooltips not disappearing. No need to clutter the main bug tracker with lots of small issues.

Also makes it easier to tackle several issues in one go / PR.

**Comment by PVince81** [comment]
- [ ] conflict dialog too wide on mobile: https://github.com/owncloud/core/issues/13102
- [ ] display a spinner when creating a new file/folder (medium difficulty): https://github.com/owncloud/core/issues/13161
- [ ] add empty content message for folders in file picker dialog: https://github.com/owncloud/core/issues/16108

**Comment by kavishdahekar** [comment]
Has anybody started working on these?
@PVince81 are we expecting a single PR for all of these together? Is it okay if I can't get them all but wish to fix some of them?

**Comment by PVince81** [comment]
No need to fix them all in a single PR but it might make sense to put a few smaller fixes together inside a single PR. Feel free to take up a few.

**Comment by Dave-Melia** [comment]
Hey I'm new to this.  I was trying to look at the App list length issue and OwnCloud has a notification "There were problems with the code integrity" . Can this be ignored or does it prevent my changes from displaying?  Thanks

**Comment by PVince81** [comment]
@Dave-Melia you can ignore this. I guess you tried to fix it in a tarball versions. If you use the git version you won't see this warning.

**Comment by davitol** [comment]
- [ ] https://github.com/owncloud/core/issues/27578 Previous Mountpoint Storage Folder name is set in the textbox name for a new mount

**Comment by davitol** [comment]
- [ ] External storage has been disabled by the administrator should disappear when we enable external storage https://github.com/owncloud/core/issues/27752

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
