### ISSUE TITLE
Files app keyboard issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27580]
- [ ] shift key not working correctly: https://github.com/owncloud/core/issues/15157
- [ ] multiselet shift key issue: https://github.com/owncloud/core/issues/20145
- [ ] shift + up, shift + down: https://github.com/owncloud/core/issues/27359
- [ ] keyboard nav must work with sidebar: https://github.com/owncloud/core/issues/19442
- [ ] keyboard arrows must scroll view: https://github.com/owncloud/core/issues/9740

- [ ] filepicker dialog select multiple files on Mac: https://github.com/owncloud/core/issues/18282

and the PR from @noveens which might or might not already fix some of those: https://github.com/owncloud/core/pull/27374

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

(This is an automated comment from [GitMate.io](https://gitmate.io).)
