### ISSUE TITLE
Release checklist 10.0.3 beta/RC

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#28685]
# Release 10.0.3
currently:  Beta Phase

# Build and QA
## Build beta 2
- [x] Build a server beta release, https://download.owncloud.org/community/testing/owncloud-10.0.3beta2.tar.bz2
- [x] Build tarballs for all editions @felixboehm
- [x] Build docker image @tboerger 
- [x] Build Packages @crrodriguez  

## QA
- [x] Smoke Test https://github.com/owncloud/QA/issues/480
- [x] Tracking of maintenance release for 10.0.3 https://github.com/owncloud/qa-enterprise/issues/108
- [x] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [x] Updater

## Known issues
- [x] direct migration 8.2 -> 10.0 not ready for 
  - [x] ~~files_external~~ => it was fixed already for 10.0.3beta: https://github.com/owncloud/core/pull/28662
  - [x] calendar
  - [x] contacts
- [x] cannot accept federated share through notifications in the web UI: https://github.com/owncloud/notifications/issues/107
- [x] drag and drop from file manager to folder doesn't upload to correct dir: https://github.com/owncloud/core/issues/28689
- [x] known issue: SFTP + keypair regression: https://github.com/owncloud/core/issues/28669

# Communication

## Publish beta
- [x] central: https://central.owncloud.org/t/owncloud-server-10-0-3-beta-released/9061
- [x] web updater: https://github.com/owncloud/administration/pull/137

## Beta Programm
- [x] Mailing to beta testers @pmaier1 

## Release Notes
- [x] Gather and publish release notes https://github.com/owncloud/documentation/issues/3360

# Related
## App releases aligned with 10.0.3
These app releases are waiting / depending on 10.0.3
- [ ] oAuth  https://github.com/owncloud/oauth2/issues/63 **QA by @SamuAlfageme**
- [x] Activity **QA by @davitol**
- [x] Firewall https://github.com/owncloud/firewall/issues/396 **QA by @phil-davis**
- [x] Custom Groups **QA by @SergioBertolinSG**
- [x] admin_audit **QA by @SergioBertolinSG**
- [x] User_shibboleth https://github.com/owncloud/user_shibboleth/issues/182 **QA by @davitol**
- [x] Guests https://github.com/owncloud/guests/issues/132 **QA by @davitol**
- [x] Password_policy https://github.com/owncloud/password_policy/issues/94 **QA by @davitol**
- [x] Diagnostics https://github.com/owncloud/diagnostics/issues/11 **QA by @SergioBertolinSG**
- [x] Text Editor https://github.com/owncloud/files_texteditor/issues/209 **QA by @phil-davis**

**Comment by PVince81** [comment]
Known issues to communicate (discovered during smoke testing):
- cannot accept federated share through notifications in the web UI: https://github.com/owncloud/notifications/issues/107

**Comment by pmaier1** [comment]
Added some more apps for beta @DeepDiver1975

**Comment by PVince81** [comment]
customgroups is also ready for beta, but not to be bundled

**Comment by davitol** [comment]
There are pending issues in guests app, and also makefile is pending to be done

**Comment by SergioBertolinSG** [comment]
Diagnostics app is still under testing.

**Comment by felixboehm** [comment]
Sure, that is the nature of a beta version ^^

**Comment by pmaier1** [comment]
Beta mailing to selected customers/partners was sent out on friday!

**Comment by PVince81** [comment]
- [ ] known issue: SFTP + keypair regression: https://github.com/owncloud/core/issues/28669

**Comment by pmaier1** [comment]
Added release notes section.

**Comment by PVince81** [comment]
- [x] RC1: https://central.owncloud.org/t/owncloud-server-10-0-3-rc1/9340/1

**Comment by PVince81** [comment]
Two outstanding PRs:
- [ ] market bug + backport: https://github.com/owncloud/market/pull/168
- [ ] scrollto bug: https://github.com/owncloud/core/pull/29019

- [ ] version update + changelog version PR: https://github.com/owncloud/core/pull/29022

**Comment by kdslkdsaldsal** [comment]
Another point which is missed quite often:

- [ ] Update release dates of final versions in https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by pmaier1** [comment]
Thanks @kdslkdsaldsal. I just updated the overview section. The rest will require rework as well.

**Comment by pmaier1** [comment]
All done in here. oAuth2 will take another 2-3 weeks to be released. Closing.
