### ISSUE TITLE
Core upgrade process: Feedback for administrators

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#28734]
- Assumption: Administrator conducts regular core upgrade via tarball and occ upgrade
- Issues/Problems
  - Apps might also need updates to maintain compatibility
  - Admins are not yet used to our new marketplace and the Market app
  - Currently updates may fail with strange errors/stacktraces that are complicated to understand for some admins
  - It can be very confusing therefore as there are different ways to update apps and error handling is not sufficient in many cases

For that we need to provide some guidance to make upgrading as easy as possible. I thought about this a little today and came to the following concept:

## Config values to take into account

- 'has_internet_connection' => 'true/false'
- 'update_apps_via_mp' => 'true/false'
  - this one would need to introduced as a checkbox somewhere in admin settings and/or config.php value
  - true: Admin wants automated app updates via market app
  - false: Admin does not want the market app to update apps. He will conduct updates manually by obtaining tarballs and placing them to the apps folder.
  - Just came up to my mind: Should this only prevent automated updates during a core update and admins can still update apps via 'update' button in the market app or should 'false' disable updating via market app in general? @felixboehm 

## Market app states to take into account

- Market present and enabled (installed and enabled)
- Market present and disabled (installed but disabled)
- Market not present (app code missing)

## Scenario table (Scenarios x cfg values / market app states)

![scenario_matrix](https://user-images.githubusercontent.com/21193500/29422973-35167a44-837a-11e7-97fc-54a30571d01f.png)

## Process proposal

[Check config values] -> [Check market app state] -> [1)/2)]
1) Issue -> Display proper warning message with advice (-> Scenario actions)
2) No issue -> Go for teh update

## Scenario actions

**Important 1: Warnings should only be displayed when there are actual apps that need an update to be compatible with the core version to update to**

**Important 2: The concept does not yet have an answer for the case that apps are in use that a) are not yet on the marketplace or b) do not provide a version that is compatible with the core version to update to**

- **Scenario 1**

Hint: Offline instance, Market app enabled. You chose to update apps manually.
Please download app tarballs from marketplace.owncloud.com for the following apps, extract them to $appfolder and start the upgrade process again. 
→ show app list

- **Scenario 2**

-> Further market checks (see below)

- **Scenario 3**

Hint: You chose to update apps manually, not via the Market app.
Please choose one of the following options to continue the upgrade:
- If you want the Market app to download app updates automatically from ownCloud Marketplace, please enable 'update_apps_via_mp' via checkbox in admin settings or config/config.php. Afterwards start the upgrade process again.
- Download app tarballs from marketplace.owncloud.com for the following apps manually, extract them to $appfolder and start the upgrade process again.

- **Scenario 4**

Hint: Offline instance, Market app enabled. You chose to update apps automatically via the Market app but the instance is set to 'offline' mode. 
Please choose one of the following options to continue the upgrade:
- Connect the instance to the internet, set 'has_internet_connection' to 'true' in config/config.php and start the upgrade process again.
- Download app tarballs from marketplace.owncloud.com for the following apps manually, extract them to $appfolder and start the upgrade process again. 
→ show app list

- **Scenario 5**

Hint: Offline instance, Market app present but disabled. You chose to update apps manually, not via the Market app.
Please download app tarballs from marketplace.owncloud.com for the following apps manually, extract them to $appfolder and start the upgrade process again.
→ show app list

- **Scenario 6**

Hint: Your instance is set to 'online' mode and you chose to update apps automatically via the Market app. The Market app is currently disabled. 
Please enable it (command) and start the upgrade process again.

- **Scenario 7**

Hint: Market app present but disabled. You chose to update apps manually, not via the Market app.
Please choose one of the following options to continue the upgrade:
- If you want the Market app to download app updates automatically, please enable it (command), enable 'update_apps_via_mp' via checkbox in admin settings or config/config.php. Afterwards start the upgrade process again.
- Download app tarballs from marketplace.owncloud.com for the following apps manually, extract them to $appfolder and start the upgrade process again.

- **Scenario 8**

Hint: Offline instance, Market app present but disabled. You chose to update apps automatically via the Market app but the instance is set to 'offline' mode.
Please choose one of the following options to continue the upgrade:
- Connect the instance to the internet, set 'has_internet_connection' to 'true' in config/config.php and start the upgrade process again. 
- Download app tarballs from marketplace.owncloud.com for the following apps manually, extract them to $appfolder and start the upgrade process again. 
→ show app list

- **Scenario 9**

Hint: Offline instance, Market app not present. You chose to update apps manually, not via the Market app.
Please download app tarballs from marketplace.owncloud.com for the following apps, extract them to $appfolder and start the upgrade process again.
→ show app list

- **Scenario 10**

Hint: Your instance is set to 'online' mode and you chose to update apps automatically via the Market app. The Market app is currently not present.
Please choose one of the following options to continue the upgrade:
- Download the Market app tarball manually from marketplace.owncloud.com, extract it to $appfolder, enable it (command) and start the upgrade process again.
- If you want to download app updates manually, please disable 'update_apps_via_mp' via checkbox in admin settings or config/config.php. Afterwards start the upgrade process again.

- **Scenario 11**

Hint: You chose to update apps manually, not via the Market app.
Please choose one of the following options to continue the upgrade:
- If you want the Market app to download app updates automatically, please enable 'update_apps_via_mp' via checkbox in admin settings or config/config.php. Afterwards start the upgrade process again.
- Download app tarballs from marketplace.owncloud.com for the following apps manually, extract them to $appfolder and start the upgrade process again.
→ show app list

- **Scenario 12**

Hint: Offline instance, Market app not present. You chose to update apps automatically via the Market app but the instance is set to 'offline' mode and the Market app is not present.
Please choose one of the following options to continue the upgrade:
- Connect the instance to the internet and set 'has_internet_connection' to 'true' in config/config.php. Download the Market app tarball from marketplace.owncloud.com manually, extract it to $appfolder and enable it (-> command). Afterwards start the upgrade process again.
- Download app tarballs from marketplace.owncloud.com for the following apps manually, extract them to $appfolder and start the upgrade process again. 
→ show app list

## Further Market checks

1) Check: Enterprise apps needed?
- Yes: 2)
- No: 3) 
2) Check: Marketplace API key present and working?
- Yes: 3)
- No: Warning: To update ownCloud Enterprise apps automatically via the Market app it is necessary to add a Marketplace API key to the Market app. Please log in to your account at marketplace.owncloud.com, copy the API key and insert it to the Market app in the ownCloud web interface. Afterwards start the upgrade process again.
3) Check: Connection to Marketplace working?
- Yes: Go for teh update
- No: Error: Currently we can't connect to the ownCloud Marketplace. This might be due to maintenance of the ownCloud Marketplace or your instance does not have access to the internet. If you can't connect to marketplace.owncloud.com via your web browser, we kindly ask you to be patient until the ownCloud Marketplace is back in operation. Please start the upgrade process again when the Marketplace is back.
Otherwise please check the internet connection of your ownCloud instance. If your instance operates behind a firewall or similar (no internet connection), please set 'has_internet_connection' to 'false' in config/config.php and start the upgrade process again.

## Errors during upgrade?!

- Can't install app
- Problem with connection
- ?

This is a draft / brain dump. I thought about the hint messages but they are not necessarily ready to be copy/pasted. For the ones where an action is required (e.g. enable the market app), occ upgrade could also ask (e.g. should we enable it for you? -> y/n) and continue the upgrade process upon admin decision.
Open for suggestions as always!

@felixboehm @PVince81 @DeepDiver1975 @butonic @hodyroff @michaelstingl

**Comment by felixboehm** [comment]
@davitol we should test 10.0.3 to meet this concept / description.
@pmaier1 can this become simplified?

**Comment by PVince81** [comment]
It doesn't make sense to have the market app enabled on an offline instance. So instead of adding a new switch I'd rather recommend admins to disable the market app completely on offline instances.

But this hints at a little problem: with disabled market app one cannot install/update app tarballs locally with "market:install --local appname.tar.bz2" which is what I'd expect admins to run when updating offline instances.

**Comment by PVince81** [comment]
In general there are way too many scenarios, this doesn't fit the "keep it simple" motto and is confusing. We should try and reduce these to a minimum.

This is why I suggest to have the paradigm where an "offline instance" must have the market app disabled. Maybe if "has_internet_connection" is false, the market app refuses to enable ?

**Comment by PVince81** [comment]
The way I see it there are only 3 scenarios:

- online instance, admin wants to use market place: admin enables market app
- online instance (it's online for other reasons, for example ext storages), but admin doesn't want to use market for install/updates: admin disables market app
- offline instance: admin disables market app

Now if the switch "has_internet_connection" is false we could auto-disable the market app.
And clean up all the other config settings.

The only problem to solve: provide "market:install" or "app:install" command that doesn't need the market app enabled.

Now one could say that an admin wants to manually trigger app updates with an online market. Having an extra switch "disable auto-update of market apps" would be fine.

**Comment by DeepDiver1975** [comment]
Please keep in mind that all stuff above basically is only relevant for single node instances.
In a clustered/mutlinode setup apps cannot be installed via any owncloud mechanism due to the distributed nature.

In a multinode setup the admin has to grab the code (server tar ball as well as any app tar ball), put this into his systems (build new docker image, build new vm, load via ansible ..... what ever).
This is ususally also an offline instance where all the mechanisms above dont work out.

And with respect to the fact: 'find out which apps need to be updated' this is part of the admins pre-deployment testing. Please note that apps don't come from owncloud and the marketplace.
There are 3rdparty contributions involved as well.

**Comment by DeepDiver1975** [comment]
> this one would need to introduced as a checkbox somewhere in admin settings and/or config.php value

littel side note for the future: never design solutions which involve setting config.php from the ui. Even from occ is not that great.

**Comment by pmaier1** [comment]
Agree with @PVince81 in https://github.com/owncloud/core/issues/28734#issuecomment-323290092.

-> **From now on we follow the paradigm: An "offline instance" must have the market app disabled**

- Further market checks will still be needed in the future once the market supports organizations
- Corner case that apps are in use that a) are not yet on the marketplace or b) do not provide a version that is compatible with the core version to update to:
  - App still compatible (info.xml) -> continue with upgrade
  - App not compatible (info.xml) -> stop upgrade and tell admin to remove the respective app and restart upgrade

### Scenarios

- Offline instance: No market app, 'has_internet_connection' => 'false'
- Online instance: Market app, 'has_internet_connection' => 'true'
  - automatic update of the apps during core upgrade
  - when auto-update switch is "false", need to tell the admin that apps won't be updated automatically because he set the switch to "false". Tell the admin to update via occ market:upgrade or via the Market app UI after the update.
- Online instance without market: No Market app, 'has_internet_connection' => 'true'
  - need to tell the admin that apps won't be updated automatically because Market app is not present. -> Doc link to manually install apps

### Todos

- [x] Core check: 'has_internet_connection' => 'false' -> disable market app
- [ ] When market app enabled and 'has_internet_connection' => 'false' -> disable market app and throw appropriate error
- [ ] Add a switch "Disable auto-update of market apps during server update"
- [ ] Documentation for the upgrade process and "market app paradigm"

**Comment by PVince81** [comment]
- [ ] if market app disabled: also add link to documentation https://github.com/owncloud/core/pull/28711/files#diff-b1f9c4262f3d05014a0991b9a2b85811R170

**Comment by PVince81** [comment]
- [ ] @pmaier1 took the time to craft some error messages in his OP, we should probably use those

@DeepDiver1975 can you take care of the above items ? If not, let me know

**Comment by PVince81** [comment]
@DeepDiver1975 any update ?

**Comment by DeepDiver1975** [comment]
> When market app enabled and 'has_internet_connection' => 'false' -> disable market app and throw appropriate error

this is already in place - https://github.com/owncloud/core/pull/28711/files#diff-b1f9c4262f3d05014a0991b9a2b85811R113

**Comment by PVince81** [comment]
> allows installation of app packages

@DeepDiver1975 we discussed before that offline instances anyway need to extract tarballs instead of using market:install command. To align with the concept "offline instance must have market disabled" we thought that disabling it would make it so.

Anyway, I don't mind if we don't touch the market app state here. This was a request from @pmaier1

**Comment by PVince81** [comment]
> @pmaier1 took the time to craft some error messages in his OP, we should probably use those

I suggest to put these in the documentation instead and link to the documentation.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/28812

**Comment by PVince81** [comment]
The logic in the code is still quite complex, this would likely make a nice flow diagram 😄

**Comment by pmaier1** [comment]
> I suggest to put these in the documentation instead and link to the documentation.

Ok fine if we have appropriate guidance during upgrade.

Would it be possible to summarize the approach again for understanding and docs as you decided not to disable the market app. Will an admin run into timeouts / errors when market app enabled and 'has_internet_connection' => 'false' ? Should we invest time for a flow diagram or are you confident with the approach?

**Comment by PVince81** [comment]
@pmaier1 I decided to auto-disable the market app when "has_internet_connection" is false during occ upgrade. See test steps in the PR
