### ISSUE TITLE
Release checklist 10.0.4 beta1

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29276]
# Release 10.0.4
currently:  Beta Phase

# Build and QA
## Build beta 1
- [x] Build a server beta release, https://download.owncloud.org/community/testing/owncloud-10.0.4beta1.tar.bz2
- [ ] Build docker image ?
- [x] Build Packages @crrodriguez  

## QA
- [x] Smoke Test https://github.com/owncloud/QA/issues/501
- [ ] Tracking of maintenance release for 10.0.4 (TODO: ticket)
- [ ] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [ ] Updater

## Known issues
- TODO: report here
- last known issues from release notes: https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#release-notes-label

# Communication

## Publish beta
- [x] central
- [ ] web updater

## Beta Programm
- [x] Mailing to beta testers @pmaier1 

## Release Notes
- [ ] Gather and publish release notes

# Related
## App releases aligned with 10.0.4
- [ ] guests (optional)
- [ ] oauth ?
- [ ] workflow ?
- [ ] impersonate ?

**Comment by PVince81** [comment]
- [ ] market app ? (I'd expect marketplace version to match the bundled version)

**Comment by PVince81** [comment]
- [ ] BUG: known issue, integrity check error in 10.0.4beta1: core/js/mimetype.js not found, this file is supposed to be excluded from the check: https://github.com/owncloud/core/issues/29277

**Comment by crrodriguez** [comment]
pkgs are publishing now.

**Comment by crrodriguez** [comment]
publishing failed obs.int cannot reach dl-oo
ssh: connect to host dl-oo port 22: Connection timed out
building file list ... done
rsync: mkdir "/srv/www/htdocs//download/repositories/10.0.4:/testing" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(577) [Receiver=3.0.7]
rsync: connection unexpectedly closed (188 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.0]
@jnweiger

**Comment by crrodriguez** [comment]
Fixed now.. publishing right now..

**Comment by crrodriguez** [comment]
https://download.owncloud.org/download/repositories/10.0.4:/testing/ , packages are now available there.

**Comment by pmaier1** [comment]
Invite to beta testers was sent out!
