### ISSUE TITLE
Release checklist 10.0.4 beta2

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29373]
# Release 10.0.4
currently:  Beta Phase

# Build and QA
## Build beta 2
- [x] Build a server beta release, https://download.owncloud.org/community/testing/owncloud-10.0.4beta1.tar.bz2
- [ ] Build docker image ?
- [x] Build Packages @crrodriguez  

## QA
- [x] Smoke Test 
- [ ] Tracking of maintenance release for 10.0.4 (TODO: ticket)
- [ ] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [ ] Updater

## Known issues
- TODO: report here
- last known issues from release notes: https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#release-notes-label

# Communication

## Publish beta
- [x] central
- [ ] web updater

## Beta Programm
- [x] Mailing to beta testers @pmaier1 

## Release Notes
- [ ] Gather and publish release notes

# Related
## App releases aligned with 10.0.4
- [ ] guests (optional)
- [ ] oauth ?
- [ ] workflow ?
- [ ] impersonate ?
