### ISSUE TITLE
Release checklist 10.0.4 RC1

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29468]
# Release 10.0.4
currently:  Beta Phase

# Preparations
- [x] check stable10 CI status
- [x] update market app changelog
- [ ] release market app
- [x] update changelog: https://github.com/owncloud/core/pull/29506

# Build and QA
## Build RC1
- [ ] Build a server beta release
- [ ] Build docker image ?
- [x] Build Packages @crrodriguez  

## QA
- [x] Smoke Test https://github.com/owncloud/core/issues/29649
- [x] changelog testing: https://github.com/owncloud/core/issues/29697
- [ ] Tracking of maintenance release for 10.0.4 (TODO: ticket)
- [ ] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [x] Updater (via beta channel, pending to deploy)

## Known issues
- TODO: report here
- last known issues from release notes: https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#release-notes-label

# Communication

## Publish beta
- [ ] central
- [ ] web updater

## Beta Programm
- [x] Mailing to beta testers @pmaier1 

## Release Notes
- [ ] Gather and publish release notes

# Related
## App releases aligned with 10.0.4
- [ ] guests
- [ ] oauth ?
- [ ] workflow ?
- [ ] impersonate ?

**Comment by PVince81** [comment]
Here are the tickets I'm still waiting for:
- [ ] sharee autocomplete additional info backport: https://github.com/owncloud/core/pull/29457 (in CI)
- [ ] cluster config switch to prevent market shoot-yourself-in-the-foot in cluster env: https://github.com/owncloud/core/pull/29492
- [ ] market UI adjustement for cluster config https://github.com/owncloud/market/pull/184
- [ ] auth fixes, blocking client: https://github.com/owncloud/core/pull/28733
- [ ] auth fixes, many related tickets: https://github.com/owncloud/core/pull/28879
- [ ] the mariadb 10.2 workarounds: https://github.com/owncloud/core/pull/29100 + backport

**Comment by PVince81** [comment]
changelog PR for RC1: https://github.com/owncloud/core/pull/29506

**Comment by PVince81** [comment]
- [ ] cannot build market app stable10: https://github.com/owncloud/market/issues/186

- [ ] backport any master changes from market app to market app's stable10 branch!

**Comment by pmaier1** [comment]
RC1 was uploaded for beta testers.
