### ISSUE TITLE
Testing 10.0.4RC1 / RC2 Changelog

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#29697]
Added

- [x] Added support for eml mimetype - #29204 - not sure if files_texteditor should be able to open this kind of files.
- [x] Added "occ dav:cleanup-chunks" command to clean up expired uploads - #29180
- [x] Added "occ files:scan" repair mode to repair mismatch filecache paths - #29074 #29232
- [x] Added occ command to change/recreate master-key - #29260
- [x] Detailed mode for "occ security:routes" - #29095
- [x] Webdav property to retrieve a private link to files or folders - #29041
- [ ] CORS support for public API routes - #28852 - Phil
- [x] More "files_sharing" capabilities entries - #29040
- [x] Display server name in admin page, don't show in status.php - #28938 - I don't see it in the web settings.
- [ ] Validate public link mail on the client side - #29042 - Comment about this https://github.com/owncloud/core/pull/29042/files#diff-99ea0d0c9aa0d63172b459efb8c4cb42R87
- [x] Expose XHR response in share dialog autocomplete callback for extensions - #29231
- [x] Let apps provide icons for settings sections - #29358
- [x] Added cancellable prehooks for logout operation - #29352 - To test this, test https://github.com/owncloud/impersonate/issues/64 using master code of impersonate, not 0.1.1 version.
- [x] Markdown support for app descriptions in apps settings panel - #29333
- [x] Add option to allow user to share only with the groups they belong to - #29391 - Should a regular user be able to share with admin user in this case?
- [x] Cacheable storage adapter for use by Flysystem based external storage backends - #29414 
 Test using dropbox app. => cannot test, app is not using this currently. Skip
- [x] Add user additional info field for share autocomplete - #29457
- [x] Add dispatcher event for remote fed shares - #29482
- [x] Adding mode of operations - either single-instance or clus… - #29492
- [x] Added support for MariaDB 10.2.7+ - #29240
- [x] Admins can now exclude files from integrity check in config.php - #29460
- [ ] Use X-Request-ID header as request id if provided by client, useful for logging - #29434
- [x] Added authentication headers verification to validate the session - #29525 - Oauth
- [x] Added IServiceLoader on server container to load app service classes from XML tags in info.xml - #29525  - Oauth
- [x] Trigger events for federated shares - #29566

Changed

- [x] Exclude mimetypelist.js from integrity check - #29048 #29316 - I don't see this fixed, in the integrity check that file appears as missing, failing. => build script issue, to be verified in RC2
- [x] Refactor set and reset of capabilities - #29200
- [x] All amazon locations support v4 now - v3 deprecated - #29153
- [x] Modified time value of files is now 64 bits long - #28961
- [x] User names must now be at least 3 characters long - #29237
- [x] AccountMapper get by email is now case insensitive - #29341
- [x] Remove deprecated federated share API warning as it needlessly pollutes logs - #29364
- [x] Improve UI for public link sharing permissions for folders - #29413
- [x] Replace notify user for local shares with button - #29463
- [x] Log out current user after submitting form in password reset page - #29464
- [x] Update minimum supported browser versions - #29507
- [x] Admins can now change display name even when its modification is disallowed for regular users - #29442

Removed

- [x] Remove AvatarPermissions repair step - #29202
- [x] Remove unused FTP code - #29186
- [x] Remove app store related code obsoleted by market app - #29249

Fixed

- [x] Corrected namespace for OC\Memcache\ArrayCache which caused errors on some environments - #29219
- [x] External storage Javascript code from apps is now loaded correctly (fixes Dropbox app and others) - #29225 - Test with dropbox
- [x] Use product name from theme - #29251
- [x] Make sure the external storage folder name is editable when returning from OAuth authorization - #29253 - test with dropbox as well
- [x] Fix duplicate external storage config that appear sometimes when returning from OAuth authorization - #29254 - more dropbox
- [x] Log exceptions in decrypt-all command - #29248
- [x] SFTP key pair mode now works again - #29156
- [x] Use correct class namespace for ownCloud ext storage - #28935
- [x] Fix generated zip file to avoid errors with some zip tools - #29149
- [x] Fix position of dialog boxes - #29133 #29467
- [ ] Move 64bit mtime migration from dav to core - #29121 - Phil
- [x] Allow 0 byte quota to be entered on UI - #29113
- [x] Don't display warning about limited commands when running maintenance:install - #28968
- [x] Handle no user session in isSharingDisabledForUser() - #28915
- [x] Fix icon format for federated cloud sharing - #28972
- [x] Fix for decrypting user specific keys - #29189 - Test with encryption
- [x] Remove alternate keys storage during user delete - #29155 - Test with encryption
- [x] Fix error logs due to deletion of keys - #28934 - Test with encryption
- [x] Fix encryption panel to properly detect current mode after upgrade to ownCloud 10 - #29049 - Test with encryption
- [x] Fix quota check when uploading to federated shares - #29325 #29424
- [x] Fix issue when mounting another encrypted ownCloud - #29360
- [x] AccountMapper get by email is now case insensitive - #29341 - Duplicated
- [x] Fix order of apps to be deterministic during install process - #29267 - This needs Mac OS High Sierra.
- [x] Only initiate connection to federated share when necessary - #29314
- [x] Allow group named "0" to be deleted - #29323
- [x] Do not translate CORS header in settings page - #29313
- [x] Disable background scan for home storage/cache - #29306 - Extreme corner case - uses encryption too.
- [x] Fixed double escaping in full page error messages - #29304 - This needs a unit test.
- [x] Updated davclient.js which fixes issue whenever an app extends Array prototype - #29305
- [x] Fix OCS apps API to correctly include attributes into generated XML - #29303
- [ ] Make enum type mapping work with migrations - #29268 - Upgrade with database tweaking
- [x] Handle invalid storage when getting storage root id - #29278
- [x] Fix storing/retrieval for dav properties of non files - #29273
- [x] Remove double quotes from boolean values in status.php output - #29271
- [x] Tidy code in DAV related classes - #29272 - Nothing to test, code cleaning.
- [x] Fix the missing argument to DecryptAll - #29371 - This is throwing an exception.
- [x] Skip copying skeleton files if skeleton dir is not accessible - #29379
- [x] Use chunked DB query when preloading directory content for DAV properties - #29416
- [x] Fix failure when checking integrity signature for non-existing files - #29433
- [x] Prevent uploading of part files through WebDav - #29432
- [ ] Only trigger "changeUser" event if account object really changed - #29429 - No idea what to test here if any, ask Jörn
- [x] Only load app type once in app manager classes - #29428
- [x] Use efficient startsWith implementation in server container - #29427 - No idea what to test here if any, ask Jörn => the fact that OC still works proves it works as this is a very core component that resolves classes
- [x] Fix race condition in browser when uploading folder tree - #29435
- [x] Disable nginx buffering for file downloads to avoid huge memory usage in some scenarios - #29403 - Requires nginx
- [x] Fix many issues related to session removal - #28879
- [x] Fix SMB to better detect when overwriting through rename - #29564

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
@mmattel are you able to verify https://github.com/owncloud/core/pull/29400 on 10.0.4 RC1 ?

**Comment by mmattel** [comment]
I have tested https://github.com/owncloud/core/pull/29400 live on my productive 10.0.3. system (issue was blocking me) and it worked fine ! I also tested on master on my dev system - also fine - if this is of help. I did not downloaded and tested 10.0.4RC1 but I fully expect its working here.

**Comment by PVince81** [comment]
Okay thanks, I'll just tick the box then. I think this is low risk anyway.

**Comment by mmattel** [comment]
@PVince81 should´t https://github.com/owncloud/core/pull/29261 (Remove double quotes from boolean values in status.php output) be added into the fixed section?

**Comment by PVince81** [comment]
@mmattel ok, will do in https://github.com/owncloud/core/pull/29725

**Comment by PVince81** [comment]
@mmattel it's already there

**Comment by PVince81** [comment]
> Only trigger "changeUser" event if account object really changed - #29429 - No idea what to test here if any, ask Jörn

For this I think you need to test "user:sync" both with new users in LDAP and also existing users. If this works then consider it working. The optimization seems to be when detecting existing users, we simply save some time by not running unnecessary code.

@davitol

**Comment by PVince81** [comment]
Fixes:
- [ ] CorsController broken, fix here: https://github.com/owncloud/core/pull/29736
- [ ] optional addition: https://github.com/owncloud/core/pull/29738

**Comment by PVince81** [comment]
To test:
- [ ] notifications app + shib: https://github.com/owncloud/notifications/pull/122

Additional fixes added in RC2:
- [ ] CORS whitelist, setting page (Vincent)
- [ ] CORS interaction (Vincent, using js-owncloud-client)
- [ ] regenerate master key with already decrypted files: https://github.com/owncloud/core/issues/29735
- [ ] sort checkbox list of allowed personal storages: https://github.com/owncloud/core/issues/29746
- [ ] federated share import from public link: https://github.com/owncloud/core/issues/29677
- [ ] properly display product name in status.php with theming: https://github.com/owncloud/core/issues/29728
