### ISSUE TITLE
Release checklist 10.0.5 RC3

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30057]
# Release 10.0.5 ~~RC1~~ RC3

# Preparations
- [x] check stable10 CI status
- [x] update core changelog

# Build and QA
## Build RC3
- [x] Build a server beta release => https://download.owncloud.org/community/testing/owncloud-10.0.5RC3.tar.bz2
- [ ] Build docker image ?
- [ ] Build Packages @crrodriguez  

## QA
- [ ] Smoke Test @davitol https://github.com/owncloud/core/issues/30219
- [x] changelog testing @davitol https://github.com/owncloud/core/issues/30152 
- [ ] Tracking of maintenance release for 10.0.5 (TODO: ticket)
- [ ] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [ ] Updater (via beta channel, pending to deploy)

## Known issues
- TODO: report here
- last known issues from release notes: https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#release-notes-label

# Communication

## Publish beta
- [ ] central
- [ ] web updater

## Beta Programm
- [ ] Mailing to beta testers @pmaier1

## Release Notes
- [ ] Gather and publish release notes

# Related
## App releases aligned with 10.0.5
None

**Comment by PVince81** [comment]
seems I missed the market app update/release, is there any change since last time ? @patrickjahns @felixheidecke @DeepDiver1975

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are #29373 (Release checklist 10.0.4 beta2), and #29468 (Release checklist 10.0.4 RC1).

**Comment by PVince81** [comment]
Missing changelog entries, will be added in final build or next RC: https://github.com/owncloud/core/pull/30058

**Comment by DeepDiver1975** [comment]
> seems I missed the market app update/release, is there any change since last time 

no release necessary for market

**Comment by PVince81** [comment]
RC1 build is broken, will have to build RC2.

See https://github.com/owncloud/core/pull/30068

**Comment by patrickjahns** [comment]
> seems I missed the market app update/release, is there any change since last time ?

what update? we introduced fetching of market app with the last release, didn't we?

**Comment by PVince81** [comment]
> what update? we introduced fetching of market app with the last release, didn't we?

ok, need to update the checklist... thanks for the info

**Comment by PVince81** [comment]
Ok, we sorted out the issues. No RC2 either because after tagging we found a critical core issue that broke the Dropbox ext storage. All fixed in RC3 now.
