### ISSUE TITLE
Testing 10.0.5RC3 Changelog

### ISSUE THREAD

**Issue by davitol** [owncloud/core#30152]
**Added**
   - [x] Add php-intl as hard requirement - #29539
    - [x] Optionally show server hostname in status.php - #29471
    - [x] Add link for logfiles docs in exception page and simplify text - #29674
    - [x] Link to trusted domains docs in error message - #29730
    - [x] Add indices on share table - #29883 #29592
    - [x] Add dispatcher event for "unshare from self" action - #29851
    - [x] Technology preview for PHP 7.2 support - #29878
    - [ ] Added public hooks for file operations using Symfony Event Dispatcher - #29939
    - [x] Expose getAppPath() and getAppWebPath() on the AppManager service #30041
    - [x] Add warning in settings page when running in debug mode - #29936
    - [x] move to general settings page https://github.com/owncloud/configreport/pull/45  stable10

**Changed**
   - [x] Switch Webdav URL in field in navigation panel to the new endpoint - #29766
    - [x] Require a minimum of 1 character for the application password name - #29831
    - [x] Only allow a single active theme app with no magic fallbacks to inactive app themes - #29854
    - [x] Config report now hides email address from email config - #29949
    - [x] Change "remote" to "federated" suffix in sharing autocomplete dialog. - #30046  https://github.com/owncloud/core/issues/29015#issuecomment-358289052

**Removed**
   - [x] Removed old Dropbox storage backend, people should use the files_external_dropbox app instead - #29135
    - [x] Revoke tasks.crt - #29882
    - [x] Remove unused composer dependency on natxet/CssMin - #29930

**Fixed**
   - [x]  Fix Dropbox / GDrive oauth handshake handling - #30071
    - [x]  Redisplay login page on CSRF error - #30035
    - [ ]  Do not reset display name to uid on sso login - #30038
    - [x] Do not automatically disable apps of certain types - #29870
    - [x] Fix provisioning API when dealing with group name "0" - #30004
    - [x]  Tweak occ command help output - #29959
    - [x] Now using upsert instead of insertIfNotExists for file cache updates, fixes concurrency issues - #29934
    - [ ] Only set CORS headers on Webdav endpoint when Origin header is specified - #29874
    - [x] Ignore broken/dead symlinks on filescan - #28959
    - [ ] Improve performance by caching non-existing accounts - #29866
    - [x] Fix template location order by searching the enabled theme app first - #29867
    - [x] Actually log message instead of {$message} - #29844
    - [x] Improved performance on new DAV endpoint by skipping querying parent nodes - #29834
    - [x] Adjust error message about PHP compatibility to say PHP X.X like previous line. - #29828
    - [ ] Raise more useful message when constructor are not resolvable - #29760
    - [x] Fix wording for versions expiration occ command - #29671
    - [x] Handle invalid or missing external storage backend to keep mount point visible - #29562
    - ❌  Fix integrity check when owncloud is not installed - #29692
    - [x] Fix issues about unsharing with some scenarios after moving the share - #29716
    - [x] Allow group 0 to be created by provisioning API - #29734
    - [x] Do not reset quota if it was not provided - #29673
    - [x] Improve quota value validation - check size only if size key is set - #29743
    - [ ] Code cleanup - #29799

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.
