### ISSUE TITLE
Release checklist 10.0.5

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30231]
# Release 10.0.5

# Preparations
- [x] check stable10 CI status
- [x] update core changelog

# Build and QA
## Build final tarball
- [x] Build a server beta release => https://download.owncloud.org/community/owncloud-10.0.5.tar.bz2
- [ ] Build docker image ?
- [ ] Build Packages @crrodriguez  

## QA
- [x] Smoke Test @davitol https://github.com/owncloud/core/issues/30219
- [ ] Tracking of maintenance release for 10.0.5 (TODO: ticket)
- [ ] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [ ] Updater (via beta channel, pending to deploy)

## Known issues
- TODO: report here
- last known issues from release notes: https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#release-notes-label

# Communication

## Publish announcement
- [ ] central
- [ ] web updater @VicDeo 

## Release Notes
- already deployed

# Related
## App releases aligned with 10.0.5
None

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is #29373: Release checklist 10.0.4 beta2.

**Comment by Falseee** [comment]
What is the ETA of the 10.0.5 ?
I cant use the calender and the contacts.

**Comment by PVince81** [comment]
@Falseee should be out later today. Please report your problem with calendar/contacts on http://central.owncloud.org/ and what makes you believe that 10.0.5 will fix it. Those apps worked correctly for me on 10.0.4 and also 10.0.5 RC3.

**Comment by Falseee** [comment]
@PVince81 
I already opened two issues, both closed by @DeepDiver1975 with the reason: "fixed in 10.0.5".

https://github.com/owncloud/contacts/issues/629
https://github.com/owncloud/calendar/issues/873

**Comment by PVince81** [comment]
Announcements etc, aborted as 10.0.5 build is broken due to missing dependencies.

Follow up here https://github.com/owncloud/core/issues/30298
