### ISSUE TITLE
Release checklist 10.0.6

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30298]
# Release 10.0.6
Hotfix release for 10.0.6 as there was a dependency issue.
Built from "hotfix-10.0.6" branch.

# Preparations
- [x] check stable10 CI status
- [x] update core changelog

# Build and QA
## Build final tarball
- [x] Build a server beta release => https://download.owncloud.org/community/owncloud-10.0.6.tar.bz2
- [x] Build docker image
- [ ] Build Packages @crrodriguez  

## QA
- [x] Smoke Test @davitol @patrickjahns https://github.com/owncloud/core/issues/30300
- [ ] Tracking of maintenance release for 10.0.6
- [ ] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [ ] Updater (via beta channel, pending to deploy)

## Known issues
- last known issues from release notes: https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#release-notes-label

# Communication

## Publish announcement
- [ ] central
- [ ] web updater @VicDeo  https://github.com/owncloud/administration/pull/147

## Release Notes
- already deployed

# Related
## App releases aligned with 10.0.6
None

# Merge back
- [x] Merge back changes from hotfix-10.0.6 branches across all repos @PVince81: https://github.com/owncloud/core/pull/30299 (other repos do not have changes)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is #30231: Release checklist 10.0.5.

**Comment by PVince81** [comment]
@ownclouders leave this ticket alone!

**Comment by PVince81** [comment]
moving to 10.0.7 due to critical issue: https://github.com/owncloud/core/issues/30393
