### ISSUE TITLE
Release checklist 10.0.7

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30393]
# Release 10.0.7
Hotfix release for 10.0.7 as there was a critical regression
Built from "hotfix-10.0.7" branch.

# Preparations
- [x] check hotfix-10.0.7 CI status
- [x] update core changelog

# Build and QA
## Build RC tarball
- [x] Build a server RC release => https://download.owncloud.org/community/testing/owncloud-10.0.7RC2.tar.bz2
- [x] Smoke Test @davitol @patrickjahns https://github.com/owncloud/core/issues/30501
- [x] Test changelog entries

## Build final tarball
- [x] Build a server final release
- [ ] Build docker image
- [x] Build Packages @crrodriguez  

## QA
- [x] Smoke Test @davitol @patrickjahns
- [x] Tracking of maintenance release for 10.0.7
- [x] Tarball upgrades
- [ ] Smoke Test Packages
- [ ] Upgrade Packages
- [ ] Updater (via beta channel, pending to deploy)

## Known issues
- last known issues from release notes: https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#release-notes-label

# Communication

## Publish announcement
- [ ] central
- [x] web updater @VicDeo  https://github.com/owncloud/administration/pull/148

## Release Notes
- already deployed

# Related
## App releases aligned with 10.0.7
None

# Merge back
- [x] Merge back changes from hotfix-10.0.7 branches across all repos

**Comment by PVince81** [comment]
- [ ] waiting for https://github.com/owncloud/core/pull/30365/

**Comment by PVince81** [comment]
RC2 built, it will appear here shortly once mirrors catch up: https://download.owncloud.org/community/testing/owncloud-10.0.7RC2.tar.bz2

**Comment by PVince81** [comment]
Needs retesting on RC2:
- [ ] authentication app password lock-out and other issues, regression test all auth related stuff: https://github.com/owncloud/QA/issues/529
- [ ] null user issue: https://github.com/owncloud/core/pull/30450
