### ISSUE TITLE
10.0.8RC1/2/3 - Changelog Testing

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#31098]
# Changelog for 10.0.8. Summary

Summary of the complete Changelog: https://github.com/owncloud/core/blob/stable10/CHANGELOG.md

This summary has a QA purpose.

### Added
- [x] Share personal cleanup + note - [#30486] (https://github.com/owncloud/core/issues/30486)  - https://github.com/owncloud/core/pull/29935#issuecomment-381095714 was fixed in RC2 @SergioBertolinSG 
- [x] Add option to disable link share password enforcement for write-only shares - [#30408](https://github.com/owncloud/core/issues/30408) @SergioBertolinSG
- [x] Make syslog output configurable, introduce new default that includes the request id - [#30346](https://github.com/owncloud/core/issues/30346) @PVince81 - works
- [x] Added new API event for zip file download - [#30067](https://github.com/owncloud/core/issues/30067) @SergioBertolinSG not testable, just improvements for future enhancements
- [x] Added new API event for public link creation - [#30067](https://github.com/owncloud/core/issues/30067) @SergioBertolinSG not testable, just improvements for future enhancements
- [x] Added command to verify and fix checksums - [#31008](https://github.com/owncloud/core/pull/31008) - @SergioBertolinSG Bugs found - https://github.com/owncloud/core/issues/31133 and https://github.com/owncloud/core/issues/31136
- [ ] Introduce seen and single user sync command line features - [#31025](https://github.com/owncloud/core/issues/31025) [#31032](https://github.com/owncloud/core/issues/31032) - @jvillafanez :x: https://github.com/owncloud/user_ldap/issues/174#issuecomment-382061868
- [x] Added config setting to specify minimum characters for sharing autocomplete - [#30994](https://github.com/owncloud/core/issues/30994) [#31067](https://github.com/owncloud/core/issues/31067) @SergioBertolinSG - works but tooltip is confusing https://github.com/owncloud/core/issues/31137
- [x] Added personal note field for link share email - [#30486](https://github.com/owncloud/core/issues/30486) [#30571](https://github.com/owncloud/core/issues/30571) [#30813](https://github.com/owncloud/core/issues/30813) [#31057](https://github.com/owncloud/core/issues/31057) @SergioBertolinSG 
- [x]  Add conditional Logging target logfile for shared_secret and users - [#30443](https://github.com/owncloud/core/issues/30443) @SergioBertolinSG - https://github.com/owncloud/core/issues/31200 It was a configuration problem on my side.
- [x] Add Webdav-Location header in private link redirect - [#30387] (https://github.com/owncloud/core/issues/30387) [#30595](https://github.com/owncloud/core/issues/30595) @SergioBertolinSG
- [x] Added "uid" parameter to "validatePassword" events - [#30334](https://github.com/owncloud/core/issues/30334) @SergioBertolinSG
- [x] Added log entry when the "data-fingerprint" command was run - [#30281](https://github.com/owncloud/core/issues/30281) @PVince81 - works (note: needs loglevel <= 1)
- [x] Added "heic" and "heif" as image mime types for thumbnails - [#30108] -(https://github.com/owncloud/core/issues/30108) @SergioBertolinSG Thumbnails are not generated, only detected as pictures in the web ui (not iOS app).
- [x] Added new API events for commenting actions - [#30142](https://github.com/owncloud/core/issues/30142) @SergioBertolinSG
- [x] Added "register notifier" event for use with the notification emails feature - [#30613](https://github.com/owncloud/core/issues/30613) @SergioBertolinSG
- [x] Added group option to files:scan command - [#30615](https://github.com/owncloud/core/issues/30615) @PVince81
- [x] Added warning if no files to process in occ files:transfer-ownership command - [#30612](https://github.com/owncloud/core/issues/30612) @patrickjahns + 🤖 (acceptance tests)
- [x] Added user:modify command to core - [#30652](https://github.com/owncloud/core/issues/30652) @PVince81 => works changing display name and email
- [ ] Added config switch to enable fallback to http scheme when creating fed shares - [#30646](https://github.com/owncloud/core/issues/30646) @patrickjahns @DeepDiver1975    ❌   - see https://github.com/owncloud/core/issues/31098#issuecomment-382660842
- [ ] Added repair step for orphaned sub-shares - [#30695](https://github.com/owncloud/core/issues/30695) @jvillafanez - ❌   https://github.com/owncloud/core/pull/30695#issuecomment-381515029  => deferred to 10.0.9, no revert as it causes no issues
- [x] Added repair step to fix orphaned reshares - [#31004](https://github.com/owncloud/core/issues/31004) @jvillafanez (Checked with mysql and postgresql, untested with sqlite and oracle)
- [x] Added Symfony event to let apps resolve private links - [#30911] (https://github.com/owncloud/core/issues/30911) => test that private link of file in trash can open (trashbin uses this event) @SergioBertolinSG
- [x] Added Symfony events for delete and create share - [#31026](https://github.com/owncloud/core/issues/31026) @SergioBertolinSG
- [x] Added Symfony events for group membership events - [#31003](https://github.com/owncloud/core/issues/31003) @SergioBertolinSG
- [x] Added config.php option to select apps to ignore missing signature file (mostly for themes) - [#30891](https://github.com/owncloud/core/issues/30891) [#31066](https://github.com/owncloud/core/issues/31066) Confirmed by @thommierother https://github.com/owncloud/core/pull/30891#issuecomment-381077539
- [x] Added ability for full-page frontend-only apps in info.xml - [#30918](https://github.com/owncloud/core/issues/30918) @PVince81 - tested with [phoenix](https://github.com/owncloud/phoenix) build in "apps/phoenix", app can be enabled and opened full screen
- [x] ~~Files app UI now retries chunk uploads in web UI on stalled uploads - [#31005](https://github.com/owncloud/core/issues/31005) @PVince81 - :no_entry_sign: when simulating chunk failure, the upload finishes with error about sum of chunks sizes not matching~~ => reverted in RC3
- [x] More user-friendly email address input in link share dialog - [#30945](https://github.com/owncloud/core/issues/30945) @PVince81 - select2 input appears and autocomplete works (seen in https://github.com/owncloud/core/pull/30998#issuecomment-381742256)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31096 (10.0.8RC1 smoke test results), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/30152 (Testing 10.0.5RC3 Changelog), and https://github.com/owncloud/core/pull/31040 ([stable10] Update changelog again for 10.0.8).

**Comment by patrickjahns** [comment]
### Changed

- [ ] Renamed SMB logging config.php settings from "wnd" to "smb" - [#30244](https://github.com/owncloud/core/issues/30244)
- [ ] Improved error messages in user:delete command - [#30164](https://github.com/owncloud/core/issues/30164)
- [ ] Allow avatars to be visible publicly for public calendar - [#30228](https://github.com/owncloud/core/issues/30228)
- [ ] Improved error messages in user:delete command - [#30164](https://github.com/owncloud/core/issues/30164)
- [ ] Validate email address in mail settings section - [#30315](https://github.com/owncloud/core/issues/30315)
- [ ] Only decrypt users who have already logged in with decrypt-all occ command - [#30640](https://github.com/owncloud/core/issues/30640)
- [ ] Replace usage of "create_function" in PHP - [#30714](https://github.com/owncloud/core/issues/30714)
- [ ] Provisioning API can now properly set default or zero quota - [#30755](https://github.com/owncloud/core/issues/30755)
- [ ] User quota setting can be queried through provisioning API - [#30850](https://github.com/owncloud/core/issues/30850)

**Comment by patrickjahns** [comment]
### Fixes

- [ ] Fix wording if you are not a member of any groups - [#30558](https://github.com/owncloud/core/issues/30558)
- [ ] Fix for error when querying non present log_secret - [#30470](https://github.com/owncloud/core/issues/30470)
- [ ] Properly create a session for a pure token based request, fixed oauth2 issues - [#30542](https://github.com/owncloud/core/issues/30542)
- [ ] Free resources in preview providers - [#30533](https://github.com/owncloud/core/issues/30533)
- [ ] Make theming work when theme app is outside the ownCloud root - [#30477](https://github.com/owncloud/core/issues/30477)
- [ ] Don't try decrypting federated shares in decrypt-all command - [#30155](https://github.com/owncloud/core/issues/30155)
- [ ] Keep null in getMetaData in Checksum storage wrapper, fixes some files:scan scenarios - [#30302](https://github.com/owncloud/core/issues/30302)
- [ ] Fix failure of shares which are already moved with transfer ownership - [#30161](https://github.com/owncloud/core/issues/30161)
- [ ] Return 403 instead of 503 to resume syncing of desktop client - [#30353](https://github.com/owncloud/core/issues/30353)
- [ ] Fix validation for new encryption storage key location - [#30357](https://github.com/owncloud/core/issues/30357)
- [ ] Prevent share icon from shrinking with long texts - [#30352](https://github.com/owncloud/core/issues/30352)
- [ ] Fixed regression where a user could not set own email address in the settings page - [#30319](https://github.com/owncloud/core/issues/30319)
- [ ] Check trashbin permissions before moving to trash, fixes deletion as guest user - [#30240](https://github.com/owncloud/core/issues/30240)
- [ ] Handle no read access to skeleton - [#30241](https://github.com/owncloud/core/issues/30241)
- [ ] Fix file name escaping in error messages in web UI related to file operations - [#30193](https://github.com/owncloud/core/issues/30193)
- [ ] Show new basename and extension while waiting for rename operation to finish in web UI - [#30040](https://github.com/owncloud/core/issues/30040)
- [ ] Fix deletion of group with special characters in web UI - [#30111](https://github.com/owncloud/core/issues/30111)
- [ ] Fix missing preview in file upload conflict window - [#30125](https://github.com/owncloud/core/issues/30125)
- [ ] Properly filter link share email parameters - [#30165](https://github.com/owncloud/core/issues/30165)
- [ ] Convert null to empty string for Oracle in file cache accessor - [#30224](https://github.com/owncloud/core/issues/30224)

**Comment by patrickjahns** [comment]
### Removed
- Removed private oc_current_user Javascript variable - [#30486](https://github.com/owncloud/core/issues/30486) [#30556](https://github.com/owncloud/core/issues/30556)
- Remove app store config values from config.sample.php - [#30422](https://github.com/owncloud/core/issues/30422)
- Remove documentation of the theme option in config.sample.php - [#30350](https://github.com/owncloud/core/issues/30350)
- Remove unused config.sample.php parameters - [#30933](https://github.com/owncloud/core/issues/30933) [#30812](https://github.com/owncloud/core/issues/30812)
- Remove "Unlimited" word from quota report in personal page - [#31041](https://github.com/owncloud/core/issues/31041)

**Comment by IljaN** [comment]
To test checksum command, upload a file and then manually modify checksum column in oc_filecache to something else.

More notes here: https://github.com/owncloud/documentation/issues/4014

**Comment by patrickjahns** [comment]
## ⚠️  Auth / Security related ⚠️  
  - [ ] Properly create a session for a pure token based request, fixed oauth2 issues - [#30542](https://github.com/owncloud/core/issues/30542)
- [ ] Catch session unavailable exception - [#30623](https://github.com/owncloud/core/issues/30623)
- [ ] Catch session unavailable exception - [#30347](https://github.com/owncloud/core/issues/30347)
- [ ] Fixing logout for app password scenario - [#30591](https://github.com/owncloud/core/issues/30591)
- [ ] Proper HTTP status code on login exception - [#30639](https://github.com/owncloud/core/issues/30639)
- [ ] Fix some CSRF issues on Webdav endpoint by only checking for POST method - [#30358](https://github.com/owncloud/core/issues/30358)
- [ ] Adding a system configuration for global CORS domains - [#30906](https://github.com/owncloud/core/issues/30906)
- [ ] Better label for CORS in settings section - [#30663](https://github.com/owncloud/core/issues/30663)
- [ ] Allow regular users to change their CORS domains - [#30649](https://github.com/owncloud/core/issues/30649)
- [ ] Remove implicit login in base.php to remove bogus "Login failed" logs - [#30814](https://github.com/owncloud/core/issues/30814)
- [ ] Initialize root folder service later to fix user backend registration order issue - [#30810](https://github.com/owncloud/core/issues/30810)
- [ ] Check apache auth on login form - [#31074](https://github.com/owncloud/core/issues/31074)
- [ ] Check basic auth credentials periodically after a timeout instead of … - [#31076](https://github.com/owncloud/core/issues/31076)
- [ ] Polish totp middleware a little - [#30849](https://github.com/owncloud/core/issues/30849)
- [ ] Fix CORS OPTIONS request for unauthenticated requests - [#30912](https://github.com/owncloud/core/issues/30912)

**Comment by DeepDiver1975** [comment]
> Removed private oc_current_user Javascript variable - #30486 #30556

We had a regression in calendar which was resolved already https://github.com/owncloud/calendar/pull/884

**Comment by patrickjahns** [comment]
@DeepDiver1975  @PVince81 
Can we put this in "developer" release notes - so third party developers will know about this change ?

**Comment by pako81** [comment]
@patrickjahns Tested:

>  Fix validation for new encryption storage key location - #30357

Works perfectly. Please go ahead and tick the checkbox

**Comment by patrickjahns** [comment]
@jvillafanez 
`docker run -p 1521:1521 deepdiver/docker-oracle-xe-11g` - then you have oracle.

If you need a container with oracle inside - you can use https://hub.docker.com/r/owncloudci/php/tags

**Comment by PVince81** [comment]
> Can we put this in "developer" release notes - so third party developers will know about this change ?

This was never supposed to be public API but people still used this.

We can add a note in the regular release notes as we don't have developer release notes.

**Comment by PVince81** [comment]
Tested "Fixed regression where a user could not set own email address in the settings page - #30319"
- [x] TEST: email can be saved when opening confirmation link while being logged in
- [x] TEST: email can be saved when opening confirmation link while being logged out then logging in
- [x] TEST: correct error when opening confirmation link as the wrong user

**Comment by PVince81** [comment]
Tested "Set empty authtoken names to 'none' as empty is not allowed any more - #30908"

- [x] TEST: Setup OC 10.0.4, created two app tokens, one with no name and one with a name, upgrade to 10.0.7 => both tokens still work => DB contains "(none)" for the formerly unnamed token

**Comment by PVince81** [comment]
Ticked "Added config.php option to select apps to ignore missing signature file (mostly for themes)" as  Confirmed by @thommierother https://github.com/owncloud/core/pull/30891#issuecomment-381077539

**Comment by PVince81** [comment]
Tested "Guide users to also check spelling for typos in federated share id - #30355" => with failure: no_entry missing code path #30159 (comment) (would consider "known issue" as it's minor)

**Comment by PVince81** [comment]
Tested "Added user:modify command to core - [#30652](https://github.com/owncloud/core/issues/30652)"  => works changing display name and email

**Comment by PVince81** [comment]
Tested "Fix failure of shares which are already moved with transfer ownership - [#30161](https://github.com/owncloud/core/issues/30161)", not working 100% as expected, raised bug https://github.com/owncloud/core/issues/31150

**Comment by PVince81** [comment]
Found bug "Public link share name length check is inaccurate": https://github.com/owncloud/core/issues/31157

**Comment by IljaN** [comment]
Tested: Better label for CORS in settings section - #30663 -> OK!

**Comment by IljaN** [comment]
Allow regular users to change their CORS domains - #30649 -> OK!

Tested by setting custom Origin header in curl, if origin matched the whitelisted origin, correct CORS headers are present. CORS-Whitelists are isolated between different users.

**Comment by IljaN** [comment]
Tested: Adding a system configuration for global CORS domains - #30906 -> OK!

**Comment by IljaN** [comment]
Tested: Fix CORS OPTIONS request for unauthenticated requests - #30912 -> OK!

OPTIONS with "Access-Control-Request-Method" header returns 200 on authenticated ocs-api request.

**Comment by PVince81** [comment]
Failed Test "Make theming work when theme app is outside the ownCloud root - [#30477](https://github.com/owncloud/core/issues/30477)" and failed, raised https://github.com/owncloud/core/issues/31170

**Comment by PVince81** [comment]
Added "regression test retention / trashbin expiration" checkbox as the fix of the matching item moves more code around and does more than just fixing the issue.

**Comment by IljaN** [comment]
Tested: Keep null in getMetaData in Checksum storage wrapper, fixes some files:scan scenarios #30302 -> OK!

Filescan does not crash on unreadable local and ext-storage files.

**Comment by IljaN** [comment]
Tested: Fixing logout for app password scenario - #30591  -> OK!

No login failed messages in log when logging in with app password.

@voroyam Can you please test app-password login in combination with ldap? No "Login-Failed" Messages should appear in the log.

**Comment by IljaN** [comment]
Added "test app-pasword login with ldap"

**Comment by PVince81** [comment]
Missing items and items to add since RC1:
### Added
- [ ] Added option for user:sync to reenable formerly disabled users - [#31124](https://github.com/owncloud/core/pull/31124)
- [ ] Ability to log extra JSON fields - [#31121](https://github.com/owncloud/core/issues/31121)
- [ ] Trigger event when logging - [#31121](https://github.com/owncloud/core/issues/31121)

- [ ] Added Symfony events for configuration changes (config.php and appconfig) - [#30788](https://github.com/owncloud/core/issues/30788) [#30937](https://github.com/owncloud/core/issues/30937) [#31107](https://github.com/owncloud/core/issues/31107)
- [ ] Added Symfony events for updating share attributes (expiration, password, name) - [#31120](https://github.com/owncloud/core/issues/31120)
- [ ] Added Symfony events for feature change in group admin - [#31132](https://github.com/owncloud/core/issues/31132)

### Changed
- [ ] Set minimum php version to 5.6 in composer.json - [#31100](https://github.com/owncloud/core/issues/31100)

### Fixes
- [ ] Properly align three button dialogs - [#31147](https://github.com/owncloud/core/issues/31147)
- [ ] Many documentation improvements in config.sample.php - [#31114](https://github.com/owncloud/core/issues/31114) [#31127](https://github.com/owncloud/core/issues/31127) [#31128](https://github.com/owncloud/core/issues/31128) [#31068](https://github.com/owncloud/core/issues/31068)
- [ ] Fix some documentation paths in config.sample.php - [#30431](https://github.com/owncloud/core/issues/30431)
- [ ] Fix App Framework ApiContoller initialization to fix thumbnail access - [#31104](https://github.com/owncloud/core/issues/31104) => this for 
- [ ] Properly trigger file-related Symfony events when chunking - [#31087](https://github.com/owncloud/core/issues/31087)

**Comment by IljaN** [comment]
Tested: Fix some CSRF issues on Webdav endpoint by only checking for POST method - #30358 -> OK

PROPFIND via Postman works without CSRF-Token

**Comment by patrickjahns** [comment]
Testing "Do not log errors when uploading forbidden file format"

**Comment by PVince81** [comment]
Tested "Make syslog output configurable, introduce new default that includes the request id ", works

**Comment by patrickjahns** [comment]
Testing: Added config switch to enable fallback to http scheme when creating fed shares

Receiving side just sees this error message when going via http
![image](https://user-images.githubusercontent.com/6403243/38933848-6c9ce5ce-431a-11e8-834d-6a1477cd7050.png)

**Comment by PVince81** [comment]
Retested "Make theming work when theme app is outside the ownCloud root - #30477", works in RC3

**Comment by PVince81** [comment]
# Notifications items to test

- [ ] Allow CORS requests to list notifications - [#176](https://github.com/owncloud/notifications/issues/176)
- [ ] Add support for email notifications - [#156](https://github.com/owncloud/notifications/issues/156) [#162](https://github.com/owncloud/notifications/issues/162) [#175](https://github.com/owncloud/notifications/issues/175) [#171](https://github.com/owncloud/notifications/issues/171)
- [ ] Add occ command arguments for link and link text - [#172](https://github.com/owncloud/notifications/issues/172)
- [ ] Fix occ command for group notification - [#146](https://github.com/owncloud/notifications/issues/146)

**Comment by PVince81** [comment]
Tested "Properly trigger file-related Symfony events when chunking" with old chunking, new chunking and no chunking: events are triggered

**Comment by IljaN** [comment]
Tested "Use storage specific move operation for object store - #30817" => OK!

**Comment by SergioBertolinSG** [comment]
Retested Fix App Framework ApiContoller initialization to fix thumbnail access - #31104 - @SergioBertolinSG #29914 (comment) Not working in RC2, Works in RC3.

**Comment by pako81** [comment]
Tested "regression test retention / trashbin expiration" - works fine (at least no regression). Need however to clarify what is the expected behavior about the min retention period. Will open a separate issue for that.

**Comment by PVince81** [comment]
Failed: "Added config switch to enable fallback to http scheme when creating fed shares - #30646", tested by @DeepDiver1975. It seems the code is not triggered / the fix is in the wrong location.

@DeepDiver1975 will fix it. Ticket: (will raise)

**Comment by IljaN** [comment]
Tested: Catch session unavailable exception - #30347 #30623 -> OK!

Additional codereview + T

**Comment by PVince81** [comment]
### 10.0.8 RC4 items to test

- [ ] Federation fallback to http config switch: https://github.com/owncloud/core/issues/31196 @patrickjahns to test
- [ ] Expiration date missing in link share email: https://github.com/owncloud/core/issues/31057 @PVince81 - to test
- [ ] Prevent background scan to scan homes of users who never logged in - [#31189](https://github.com/owncloud/core/issues/31189) @PVince81 - to test

**Comment by patrickjahns** [comment]
-> tested "Prevent background scan to scan homes of users who never logged in" 
tested during other test -> message not appearing

**Comment by patrickjahns** [comment]
Tested "Federation fallback to http config switch" -> works as expected

**Comment by PVince81** [comment]
RC testing is done, thanks a lot everybody for the big effort!

final smoke test here: https://github.com/owncloud/core/issues/31096#issuecomment-382798088
