### ISSUE TITLE
Moving FutureFile after chunk assembly logs warning

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31631]
### Steps

1. ~~Run acceptance test from https://github.com/owncloud/guests/pull/212 with name features/apiGuests/guests.feature:44~~
1. ~`cd tests/acceptance; ./run.sh features/apiWebdav/webdav-related-new-endpoint.feature:497`~
EDIT vicdeo:
since https://github.com/owncloud/core/commit/a55ce776c336831cc4e0c258c5780a81bd5a64c1#diff-4ab58a91bb1ef5af35805d89e6475100 it's
`cd tests/acceptance; ./run.sh ./run.sh features/apiWebdav/webdav-related-new-endpoint.feature:38`

1. Observe output then search for ".file"

### Expected
No warning

### Actual
Warning appears:
```
{"reqId":"nPvqv4sBxY2z8A77udaO","level":2,"time":"2018-06-04T13:04:12+00:00","remoteAddr":"127.0.0.1","user":"guest@example.com","app":"dav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/guest@example.com\/chunking-42\/.file","message":"Could not get node for path: \"uploads\/guest@example.com\/chunking-42\/.file\" : File with name \/\/chunking-42 could not be located"}
```

### Version
With stable10 51142893f67331533d4b94b8db1bf9bb92d61c3d and guests PR which adds a new test https://github.com/owncloud/guests/pull/212.

### TODO
- [x] debug for stack trace
```
0  OCA\DAV\DAV\MiscCustomPropertiesBackend->delete() /srv/www/htdocs/owncloud/apps/dav/lib/DAV/MiscCustomPropertiesBackend.php:55
1  Sabre\DAV\PropertyStorage\Plugin->afterUnbind() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/PropertyStorage/Plugin.php:126
2  call_user_func_array:{/srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105}() /srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105
3  OCA\DAV\Connector\Sabre\Server->emit() /srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105
4  Sabre\DAV\CorePlugin->httpMove() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php:649
5  call_user_func_array:{/srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105}() /srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105
6  OCA\DAV\Connector\Sabre\Server->emit() /srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105
7  OCA\DAV\Connector\Sabre\Server->invokeMethod() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php:479
8  OCA\DAV\Connector\Sabre\Server->exec() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php:254
9  OCA\DAV\Server->exec() /srv/www/htdocs/owncloud/apps/dav/lib/Server.php:279
10 require_once()  /srv/www/htdocs/owncloud/apps/dav/appinfo/v2/remote.php:31
11 {main}          /srv/www/htdocs/owncloud/remote.php:165
```

- [x] confirm whether this also happens outside of guest app
- [x] check if regression
- [ ] find good solution

@VicDeo I believed you touched this logic recently as part of https://github.com/owncloud/core/pull/31093 and might understand it better.
The code states that this is supposed to be a "rare" situation here: https://github.com/owncloud/core/blob/stable10/apps/dav/lib/DAV/AbstractCustomPropertiesBackend.php#L245
But the reason the node is not found is because it was already moved (actually copied + deleted) after chunk assembly.

Would it be safe to ignore the exception here and prevent the log entry or is there some bigger issue hidden in there ?
Should this code also be covered by some logic grabbing the nodes beforehand like in https://github.com/owncloud/core/pull/31093 ?

**Comment by PVince81** [comment]
Edited first post: this also happens in core, not isolated to guest app.

Need to run `./run.sh features/apiWebdav/webdav-related-new-endpoint.feature:497` and this appears:
```
[Mon Jun  4 15:17:41 2018] 127.0.0.1:39274 [201]: /remote.php/dav/uploads/user0/chunking-42/3
    And user "user0" uploads new chunk file "3" with "CCCCC" to id "chunking-42" using the API       # FeatureContext::userUploadsNewChunkFileOfWithToId()                                                                                                                                          
[Mon Jun  4 15:17:42 2018] Could not get node for path: "uploads/user0/chunking-42/.file" : File with name //chunking-42 could not be located
[Mon Jun  4 15:17:42 2018] 127.0.0.1:39290 [204]: /remote.php/dav/uploads/user0/chunking-42/.file
    And user "user0" moves new chunk file with id "chunking-42" to "/existingFile.txt" using the API # FeatureContext::userMovesNewChunkFileWithIdToMychunkedfile()                                                                                                                                 
```

**Comment by PVince81** [comment]
Also happening on v10.0.8.

Bisect leads to 0422d3200c9daf7dcb4939fdc8751ed52d59fd19 from https://github.com/owncloud/core/pull/29273

**Comment by PVince81** [comment]
Leaving in backlog to be scheduled

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/25493 (New chunking API assembly very slow), https://github.com/owncloud/core/issues/25682 (New chunking: etags on the final MOVE), https://github.com/owncloud/core/issues/18575 (Warning when moving two files to different storages.), https://github.com/owncloud/core/issues/7887 (Warnings in logs on master), and https://github.com/owncloud/core/issues/10358 (possibility to omit warnings about symbolic links in activity log).

**Comment by VicDeo** [comment]
@PVince81  
ouch. too many factors here. chunks, guests, etc... 
In general MiscCustomPropertiesBackend is used to store the properties for  non-file  entities like calendars and contacts.Those entities are referenced by path.

https://github.com/owncloud/core/pull/31093 is irrelevant here as it applies to files only

**Comment by VicDeo** [comment]
@PVince81 probably this filter needs to be adjusted to ignore `uploads` directory https://github.com/owncloud/core/blob/stable10/apps/dav/lib/Server.php#L226

**Comment by PVince81** [comment]
I hope this warning will not appear also for regular files in case of a move that requires copy + delete

**Comment by VicDeo** [comment]
@PVince81  https://github.com/owncloud/core/pull/31890 reduces mention of `.file` 
from 20 https://drone.owncloud.com/owncloud/core/8192/295
to 6 https://drone.owncloud.com/owncloud/core/8199/295
Is that enough? :)

**Comment by PVince81** [comment]
that's a good start.

we should get rid of those completely as they are misleading and admins will think something is wrong: find out how to prevent MiscCustomPropertiesBackend to complain about deleted nodes (or exclude IFutureFile?)

**Comment by VicDeo** [comment]
@PVince81 The rest is not related to `MiscCustomPropertiesBackend` ;)
```
{"reqId":"YAd2623fYlxPvJ5eQoTY","level":0,"time":"2018-06-25T20:14:59+00:00","remoteAddr":"172.20.0.5","user":"user0","app":"webdav","method":"MOVE","url":"\/remote.php\/webdav\/uploads\/user0\/chunking-42\/.file","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name uploads\\\/user0\\\/chunking-42\\\/.file could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php(89): 

{"reqId":"bUd2FZaE70g8qmMVthIk","level":4,"time":"2018-06-25T20:15:05+00:00","remoteAddr":"172.20.0.5","user":"user0","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/user0\/chunking-42\/.file","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 Chunks on server do not sum up to 5 but to 15\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Upload\\\/ChunkingPlugin.php(57): OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->verifySize()\\n#1 [internal function]: OCA\\\\DAV\\\\Upload\\\\ChunkingPlugin->beforeMove('uploads\\\/user0\\\/c...', 'files\\\/user0\\\/myC...')\\n#2 
```

**Comment by PVince81** [comment]
Oh... can you still look into the QuotaPlugin then ? Let me know if the fix would be too complex.

**Comment by VicDeo** [comment]
@PVince81 these failures seems to be expected:
` New chunked upload PUT using old DAV path should fail`
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature#L84

`Scenario: New chunked upload MOVE using old DAV path should fail`
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature#L95
`Upload file via new chunking endpoint with wrong size header`
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature#L111

**Comment by phil-davis** [comment]
I agree, there are acceptance tests that verify that if the client sends "wrong stuff" that the upload will fail with a reasonable 4nn code.

**Comment by PVince81** [comment]
failing is ok but does it log additional bogus entries ? if not then the current fix is enough

**Comment by VicDeo** [comment]
it's a pita to play detective trying to relate  800+ log entries to 75 test cases :cry:

**Comment by PeterPablo** [comment]
From a users perspective I want to note that when uploading from Mac with Client 2.4.2 (rev 10200) to an ownCloud instance 10.0.9 with apache and mysql, I regularly receive the above mentioned error log entry. I am uploading as a user, so no `guest app` is involved.
Hopefully the supplied fix will resolve the log spam in 10.9.10. Am I correct in assuming the fix will be included in that upcoming release?

partial `config.php`
```
'dbtype' => 'mysql',
  'version' => '10.0.9.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 104857600,
  'installed' => true,
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'cron_log' => true,
  'mail_from_address' => 'peter.ploss',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'gmail.com',
  'updatechecker' => false,
  'appstore.experimental.enabled' => true,
  'htaccess.RewriteBase' => '/owncloud',
```

**Comment by PVince81** [comment]
the log spamming fix will be in 10.0.10
