### ISSUE TITLE
10.0.9RC Changelog Testing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31829]
# Changelog for 10.0.9. Summary

Summary of the complete Changelog: https://github.com/owncloud/core/blob/stable10/CHANGELOG.md

This summary has a QA purpose.

Make sure to refresh the page before editing, and keep the edit window open for a short a time as possible.

### Added
- [x] occ user:list now takes a list of attributes to display - [#31115](https://github.com/owncloud/core/issues/31115) @phil-davis
- [x] Added Symfony events for user preference changes - [#31266](https://github.com/owncloud/core/issues/31266) @phil-davis - unit tests pass, debugger tests done in PR, no further QA test.
- [x] Added Symfony events for public links shared by email - [#31632](https://github.com/owncloud/core/issues/31632) tested by unit tests @davitol
- [x] Added Symfony events for accept and reject for local shares - [#31702](https://github.com/owncloud/core/issues/31702) @davitol
- [x] Added support for Imprint and Privacy Policy URLs in web UI and email footers - [#31666](https://github.com/owncloud/core/issues/31666) [#31699](https://github.com/owncloud/core/issues/31699) [#31730](https://github.com/owncloud/core/issues/31730) [#31766](https://github.com/owncloud/core/pull/31766) @davitol
- [x] Added HTML template for lost password email - [#31144](https://github.com/owncloud/core/issues/31144) @davitol 
- [x] Received local shares can now trigger a notification to accept or reject them, also visible in "Shared with you" section - [#31613](https://github.com/owncloud/core/issues/31613) @davitol
- [x] Rejected shares can now be accepted again in the "Shared with you" section - [#31613] (https://github.com/owncloud/core/issues/31613) @davitol
- [x] Provide original exception via logging events - [#31623](https://github.com/owncloud/core/issues/31623) @phil-davis - tested by unit tests 
- [x] Share autocomplete now displays useful tooltip when typing less characters - [#31729](https://github.com/owncloud/core/issues/31729) @phil-davis
- [x] Added public Webdav API for versions using a new "meta" DAV endpoint - [#31729](https://github.com/owncloud/core/pull/29207) [#29637](https://github.com/owncloud/core/pull/29637) @phil-davis - acceptance tests exist
- [x] Added support for retrieving file previews using Webdav endpoint - [#29319](https://github.com/owncloud/core/pull/29319) [#30192](https://github.com/owncloud/core/pull/30192) Note: https://github.com/owncloud/core/issues/31849 @phil-davis
- [x] Added versioning support for primary object store - [#29607](https://github.com/owncloud/core/pull/29607) [#31285](https://github.com/owncloud/core/pull/31285) [#31595](https://github.com/owncloud/core/pull/31595) @davitol

**Comment by phil-davis** [comment]
### Changed

- [ ] Updated ca-bundle.crt - [#31734](https://github.com/owncloud/core/issues/31734)
- [ ] Removed example theme which now lives in the [theme-example repository](https://github.com/owncloud/theme-example) - [#31447](https://github.com/owncloud/core/issues/31447)
- [ ] A user who is a member of multiple groups is now excluded from sharing if at least one of their group is configured for exclusion - [#31737](https://github.com/owncloud/core/issues/31737) @phil-davis
- [ ] Changed back default minimum search characters to 2 for share autocomplete due to confusion - [#31729](https://github.com/owncloud/core/issues/31729) @phil-davis
- [ ] Files app UI now uses new versions API through the "meta" DAV endpoint

#### Library updates

- Bump symfony to 3.4.8 and other pending minor bumps - [#31221](https://github.com/owncloud/core/issues/31221)
- Bump karma from 2.0.0 to 2.0.2 in /build - [#31253](https://github.com/owncloud/core/issues/31253)
- Bump karma-jasmine from 1.1.1 to 1.1.2 in /build - [#31378](https://github.com/owncloud/core/issues/31378)
- Bump karma-coverage from 1.1.1 to 1.1.2 in /build - [#31380](https://github.com/owncloud/core/issues/31380)
- Bump zendframework/zend-inputfilter from 2.8.1 to 2.8.2 - [#31431](https://github.com/owncloud/core/issues/31431)
- Bump icewind/smb from 1.1.0 to 3.0.0 in /apps/files_external/3rdparty - [#31521](https://github.com/owncloud/core/issues/31521)
- Bump symfony 3.4.9 to 3.4.11 - [#31571](https://github.com/owncloud/core/issues/31571)
- Update jsdoc requirement to ~3.5.5 - [#30036](https://github.com/owncloud/core/issues/30036)

**Comment by phil-davis** [comment]
### Removed

- [ ] Removed old private ajax API for previews, deprecated by DAV endpoint support - [#30254](https://github.com/owncloud/core/pull/30254)

**Comment by phil-davis** [comment]
### Fixed

- [ ] Fixed restoring of versions for single file shares - [#31681](https://github.com/owncloud/core/issues/31681)
- [ ] Group admins are not able to create groups any more using provisioning API - [#31738](https://github.com/owncloud/core/issues/31738)
- [ ] Fix Oracle for queries using ILIKE operator - [#31466](https://github.com/owncloud/core/issues/31466)
- [ ] Improve user-sync command help description - [#31691](https://github.com/owncloud/core/issues/31691)
- [ ] Fix deletion and restoration of files in trashbin in some partial selection scenarios - [#31700](https://github.com/owncloud/core/issues/31700)
- [ ] Do not load the code of disabled theme apps - [#31478](https://github.com/owncloud/core/issues/31478)
- [ ] Fix encrypt-all and decrypt-all commands to keep shares when encrypting - [#31600](https://github.com/owncloud/core/issues/31600) [#31590](https://github.com/owncloud/core/issues/31590)
- [ ] Proceed with encrypt-all command by enabling user-keys if no mode is selected by user - [#31612](https://github.com/owncloud/core/issues/31612)
- [ ] Validate maximum length of a username - [#31664](https://github.com/owncloud/core/issues/31664)
- [ ] Save timezone as given during login - [#31493](https://github.com/owncloud/core/issues/31493)
- [ ] Fix checksum computation to not apply on read-write streams to avoid potential mismatch results - [#31619](https://github.com/owncloud/core/issues/31619)
- [ ] Exclude uploads directory from read-only cache mask, fixes guest app chunked uploads - [#31596](https://github.com/owncloud/core/issues/31596)
- [ ] Properly normalize paths for event, no &$magic needed - [#31689](https://github.com/owncloud/core/issues/31689)
- [ ] Use the correct user id in login related Symfony events - [#31605](https://github.com/owncloud/core/issues/31605)
- [ ] Fix public link dialog issue when collaborative tags app is disabled - [#31581](https://github.com/owncloud/core/issues/31581)
- [ ] Fix updating public link share in transfer ownership command - [#31176](https://github.com/owncloud/core/issues/31176)
- [ ] Do not set the password again if it hasn't changed - [#31370](https://github.com/owncloud/core/issues/31370)
- [ ] Use correct l10n to translate 'password was changed' email - [#31553](https://github.com/owncloud/core/issues/31553)
- [ ] Improve text in settings/personal App Password - [#31539](https://github.com/owncloud/core/issues/31539)
- [ ] Fix default language code example - [#31448](https://github.com/owncloud/core/issues/31448)
- [ ] Fix double slash in versioning file copy events - [#31452](https://github.com/owncloud/core/issues/31452)
- [ ] Split public password enforced capabilities based on a config - [#31499](https://github.com/owncloud/core/issues/31499)
- [ ] Fix bogus exceptions related to missing DAV nodes after deletion - [#31479](https://github.com/owncloud/core/issues/31479)
- [ ] Fix enabling of users by group admins in the web UI - [#31489](https://github.com/owncloud/core/issues/31489)
- [ ] Fix AccountMapper to return an object or throw an exception - [#31445](https://github.com/owncloud/core/issues/31445)
- [ ] Proper handling of exceptions in UserManager - [#31446](https://github.com/owncloud/core/issues/31446)
- [ ] Properly cache non-existing user in UserManager - [#31446](https://github.com/owncloud/core/issues/31446)
- [ ] Update verify checksums console output to flow more naturally - [#31449](https://github.com/owncloud/core/issues/31449)
- [ ] Subadmin shouldn't be able to add users to their groups via API - [#31337](https://github.com/owncloud/core/issues/31337)
- [ ] Catch duplicate inserts in token table - [#31460](https://github.com/owncloud/core/pull/31460)
- [ ] Fix overflowing public share names in the share panel - [#31369](https://github.com/owncloud/core/issues/31369)
- [ ] Fix occ user:sync to sync quota from preferences after upgrade if backend provided no quota - [#31360](https://github.com/owncloud/core/issues/31360)
- [ ] Fix for Redis dev editions - [#31282](https://github.com/owncloud/core/issues/31282)
- [ ] Fix mail debug message recipient field - [#31227](https://github.com/owncloud/core/issues/31227)
- [ ] Prevent infinite loop in case of error in "log" event handler - [#31247](https://github.com/owncloud/core/issues/31247)
- [ ] Fix HTTP status code when uploading virus-infected files - [#31260](https://github.com/owncloud/core/issues/31260)
- [ ] Add back robots.txt in the release - [#31248](https://github.com/owncloud/core/issues/31248)

**Comment by phil-davis** [comment]
@davitol I volunteered myself for some PRs that I am already familiar with, but I did not do. That will get me started. You do the same. Then as we get them done, we can put our names against more, or look for other "volunteers" if needed.

**Comment by phil-davis** [comment]
### 10.0.9RC2 Items

- [ ] Added account module middleware to be able to plug in logic after authentication - [#31883](https://github.com/owncloud/core/issues/31883)
- [ ] Received local shares can now trigger a notification to accept or reject them, also visible in "Shared with you" section - extra changes from issue [#31886](https://github.com/owncloud/core/issues/31886)
- [ ] - Added public Webdav API for versions using a new "meta" DAV endpoint - added issues [#31805](https://github.com/owncloud/core/issues/31805) [#31801](https://github.com/owncloud/core/issues/31801)
- [ ] - Added support for retrieving file previews using Webdav endpoint - added issues [#31748](https://github.com/owncloud/core/issues/31748) [#31788](https://github.com/owncloud/core/issues/31788) [#31862](https://github.com/owncloud/core/issues/31862) [#31865](https://github.com/owncloud/core/issues/31865)
- [ ] A user who is a member of multiple groups is now excluded from sharing if at least one of their group is configured for exclusion - added [#31822](https://github.com/owncloud/core/issues/31822)
- [ ] Bookmarks certificate was removed - [#31878](https://github.com/owncloud/core/issues/31878)
- [ ] Work around Edge browser memory leak in web UI chunked upload - [#31884](https://github.com/owncloud/core/issues/31884)
- [ ] Don't fail if ISqlMigration doesn't return anything - [#31779](https://github.com/owncloud/core/issues/31779)
- [ ] Catch duplicate inserts in token table - added [#31794](https://github.com/owncloud/core/issues/31794)

**Comment by phil-davis** [comment]
Password policy testing overview:
- [x] enable password policy, change policy parameters for min length, min uppercase, min lowercase, min numbers, min special chars and the actual special chars. Check that relevant error messages are returned when trying to change password from webUI, ``occ`` commands and user provisioning API. PR https://github.com/owncloud/password_policy/pull/21 tidied the messages
- [x] setup user_ldap. Confirm that LDAP users do not get password expiry, but that ordinary users do.
- [x] try to change other user's passwords as admin. Confirm that normal users get their password changed and get a password change recorded from which password expiry ticks. Confirm that LDAP user passwords cannot be changed (and so they never get password history, and so never get expired). PR https://github.com/owncloud/password_policy/pull/31 prevents ``occ`` command from expiring LDAP user passwords.
- [x] install and enable one-time password TOTP. Check it works along with password policies and expiry. Problem found with interaction between OTP and password expired flow in webUI see issue https://github.com/owncloud/password_policy/issues/32
- [x] create app passwords. Confirm that they work across ordinary password change and expiry. Seems to be some issue with app passwords not working correctly after the ordinary password has expired - issue https://github.com/owncloud/password_policy/issues/33
- [x] check password expiry for new users that never change their password - https://github.com/owncloud/password_policy/issues/25 and fix in PR https://github.com/owncloud/password_policy/pull/34

**Comment by davitol** [comment]
> ❌  Fix updating public link share in transfer ownership command - #31176 @davitol FIXED

Retested in RC3 and it is fixed
