### ISSUE TITLE
fix API acceptance tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32040]
- [x] we have an apiSharing-v1 folder - is there an apiSharing-v2 ??
- [x]  test sharing on ocs/v2 #32074
- [x]  refactor tests/acceptance/features/bootstrap/AppManagementContext.php so it can be used on a remote server #33095
- [x] make tests/acceptance/features/apiShareOperations/getWebDAVSharePermissions.feature also work with new DAV path  #33349
- [x] join tests/acceptance/features/apiSharees/sharees_provisioningapiv2.feature and tests/acceptance/features/apiSharees/sharees.feature issue #33350 and PR #33351 
- [x] in https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature not every scenario has an webdav version defined #31799
- [x]  this scenario is in the old webdav feature file but uses the new webdav https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature#L114 is ist for old, new or both versions? test is included now in `apiWebdavProperties/createFolder.feature`
- [x]  in https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature put more `Given` in the `Background` section #31799
- [x]  split https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related.feature into multiple features
- [x] in tests/acceptance/features/apiSharing/updateShare.feature not only check the return codes but also if something useful happened (e.g. share is accessible) ##33329
- [x]  in tests/acceptance/features/apiSharing/updateShare.feature `Increasing permissions is allowed for owner` why making that user a sub-admin? #33333
- [x]  merge both features files in https://github.com/owncloud/core/tree/master/tests/acceptance/features/apiTrashbin into one file with `Examples` tables - issue #33354 
- [x] if needed split trashbin tests into multiple features - issue #33363 PR #33365 
- [x] fix api trashbin feature files, so that Background steps are used to create users - issue #33363 PR #33365 
- [x] look at https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiMain/dav-versions.feature and find out what it is about (duplications of API-Webdav suite?, scenarios that need to be moved? ....?) - issue #33379 
- [x]  check https://github.com/owncloud/core/tree/master/tests/acceptance/features/apiMain if tests should be moved into own suites - apiMain suite runs for 30min, so still OK
- [x]  split tests in https://github.com/owncloud/core/tree/master/tests/acceptance/features/apiMain into more files if needed
- [x] in acceptance/features/apiSharing/uploadToShare.feature test also with new WebDAV path #33346

**Comment by individual-it** [comment]
> we have an apiSharing-v1 folder - is there an apiSharing-v2 ??
- there is only a v1 version of the sharingAPI, and in tests/acceptance/features/bootstrap/Sharing.php we set `private $sharingApiVersion = 1;`
but all requests use the ocs endpoint, so it can be  `/ocs/v1.php/apps/files_sharing/api/v1` or `/ocs/v2.php/apps/files_sharing/api/v1` and as allways the codes will be diffrent on v1 and v2. 
I think we should tests both endpoints, same as done in apiProvisioning

**Comment by individual-it** [comment]
all done
