### ISSUE TITLE
API/Acceptance tests for Async Upload

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#32580]
With https://github.com/owncloud/core/pull/32414 merged, we are looking to have simple API acceptance tests, that generally test this behavior. 

Once these are working, we should consider also using these test steps for:
- [x] objectstore / files_primary_s3 tests are now in core, so they all run with S3 in nightly builds
- [x] firewall - issue https://github.com/owncloud/firewall/issues/536 - PR https://github.com/owncloud/firewall/pull/540
- [x] antivirus  - issue: https://github.com/owncloud/files_antivirus/issues/274 - PR https://github.com/owncloud/files_antivirus/pull/276

Double checking for
- [x] guests - issue https://github.com/owncloud/guests/issues/278 - PR https://github.com/owncloud/guests/pull/280
- [x] workflow (manually tested)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/30493 (Rename integration API tests to acceptance), and https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error).

**Comment by individual-it** [comment]
@DeepDiver1975 @PVince81 in the case of an error e.g. MOVE a file that does not exist, the async operation still replies with an `202` code. There is a correct error code in `OC-JobStatus-Location`, but the request itself returns `202`. Is that correct?

**Comment by PVince81** [comment]
I think I'd rather expect a 404 and have an existence check happen before the job goes async.

**Comment by individual-it** [comment]
other interesting tests:
- [ ] file_versioning

**Comment by individual-it** [comment]
moving to next sprint for the rest of the work

**Comment by individual-it** [comment]
all done, closing
