### ISSUE TITLE
cli occ command acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33051]
We have added a category of acceptance tests called ``cli`` to the existing ``api`` and ``webui`` categories. See QA issue https://github.com/owncloud/QA/issues/570

This core issue is to link together various smaller issues for adding features and scenarios to test each of the ``occ`` commands:

- [x] #39173
- [x] create acceptance tests for ``occ`` provisioning commands (``user:*`` and ``group:*``) #33052 
- [x] create acceptance tests for ``occ`` app management commands (enable, disable, list...) #33054
- [x] create acceptance tests for ``occ`` background commands
- [x] create acceptance tests for ``occ`` config commands (app set, system set, list...) #33386
- [x] create acceptance tests for ``occ`` dav commands (https://github.com/owncloud/core/pull/39068)
- [x] create acceptance tests for ``occ`` db commands (might be more challenging) https://github.com/owncloud/core/issues/39190
- [x] create acceptance tests for ``occ`` encryption commands https://github.com/owncloud/core/issues/39189
- [x] #39193
- [x] create acceptance tests for ``occ`` files commands (#33613)
- [x] #39195
- [x] #39196
- [x] create acceptance tests for ``occ`` log commands https://github.com/owncloud/core/issues/33136
- [x] create acceptance tests for ``occ`` maintenance commands
- [x] #39197
- [x] create acceptance tests for ``occ`` security commands
- [x] #39192
- [x] #39191
- [x] create acceptance tests for ``occ`` trashbin commands #33536
- [x] create acceptance tests for ``occ`` versions commands https://github.com/owncloud/core/issues/39165

**Comment by kiranparajuli589** [comment]
Closing this because the separate issues for each command have been issued. Please refer to those issues for more information.
