### ISSUE TITLE
webUI tests for versions

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33382]
Add webUI tests to check the behaviour of file versions, e.g.:
- [x] viewing versions of a file (PR #33395)
- [x] restoring versions of a file (PR #33395)
- [ ] deleting old versions of a file (I don't think you can do that in the webUI?) (PR #33585)
- [x] and for sharees to see versions of files shared with them (PR #33395)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/32850 (webUI tests for personal general settings), and https://github.com/owncloud/core/issues/32583 (Automated webUI tests for languages).

**Comment by phil-davis** [comment]
@dpakach this was auto-closed by the related PR. Please check the boxes of the tests that are done. And close the issue if it really is completed.

**Comment by phil-davis** [comment]
@dpakach ping - please review and tick the boxes for test scenarios that are done
