### ISSUE TITLE
Acceptance tests to verify setting a password to valid and invalid values

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33570]
We currently only test creating users and changing passwords using a small set of passwords.

Add test cases that check:
- [x] creating users using the provisioning API (PR #33571)
- [x] editing users using the provisioning API (PR #33571)
- [x] creating users using the occ command (#33598)
- [x] editing users using the occ command (#33598)
- [x] creating users using the webUI ([new issue](https://github.com/owncloud/user_management/issues/107))
- [x] editing users using the webUI ([new issue](https://github.com/owncloud/user_management/issues/107))

With passwords that have:
- [x] special characters that are on the "ordinary" US-keyboard and ASCII sset (``!@#$%^&*()`` sort of thing)
- [x] special European characters like ``España``
- [x] other Unicode characters like ``नेपाली``
- [x] characters that are invalid - e.g. space is invalid, what else is invalid?

Related issue in docs: https://github.com/owncloud/docs/issues/251

**Comment by phil-davis** [comment]
Some of the webUI extra tests will need to be in the ``user_management`` app for ``master``

**Comment by phil-davis** [comment]
List of "interesting" strings https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by phil-davis** [comment]
@dpakach please check the issues linked in the first post, and tick the ones that are done.
If they are all done, then we can close this main issue.

**Comment by dpakach** [comment]
@phil-davis  everything mentioned in the first post seems to be done so closing this.
