### ISSUE TITLE
Test files:scan occ command

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#33617]
Part of #33613

- [x] Test `files:scan <user_id>` (#33647)
- [x] Test `files:scan --path=<path` (#33647)
- [x] Test `files:scan --group=<group>` (#33647)
- [x] Test `files:scan --group=<group>` negative tests (#33767)
- [x] Test `files:scan <user_id>` negative tests (#33747)
- [x] Test `files:scan --repair`
      hard to do setup the problems it solve and needs to be run in single user mode
- [x] Test `files:scan --unscanned`
      hard to setup the problem it solves as it scanns not fully scanned file.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/18994 (Issue with command "occ files:scan"), and https://github.com/owncloud/core/pull/29635 (Add basic tests for files:scan command).

**Comment by skshetry** [comment]
Blocked due to #33630

**Comment by individual-it** [comment]
moving to next sprint for the rest of the work

**Comment by skshetry** [comment]
Negative validation for groups blocked by #33738

**Comment by skshetry** [comment]
Closing this as all of the tasks have been completed(or, hard to setup).
