### ISSUE TITLE
create acceptance tests for occ files commands

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33613]
Part of main issue #33051 

- [x] acceptance tests for ``files:checksums:verify`` (#36469)
- [x] acceptance tests for ``files:cleanup`` (#33741)
- [x] acceptance tests for ``files:scan`` (#33617)
- [x] acceptance tests for ``files:transfer-ownership`` [Already tested]

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/33386 ( create acceptance tests for occ config commands (app set, system set, list...)), https://github.com/owncloud/core/issues/33136 (occ log commands acceptance tests), https://github.com/owncloud/core/pull/32610 ( Acceptance test step for occ user:resetpassword ), https://github.com/owncloud/core/issues/31579 (test), and https://github.com/owncloud/core/issues/22485 (test).

**Comment by phil-davis** [comment]
Note: after the initial ``files:scan`` test scenarios are working, then see if we can add some tests with long file names - see issue https://github.com/owncloud/qa-enterprise/issues/190

**Comment by phil-davis** [comment]
@skshetry you are assigned to this old issue. Maybe the `files:checksums:verify` can be covered "easily" and get this closed?

**Comment by skshetry** [comment]
Yes, I'll add this to the current sprint, and either I or someone else will look into this.

**Comment by skshetry** [comment]
@phil-davis, testing `files:checksum:verify` is not possible. This command recalculates the `checksum` of the files again and provides a message if there's a mismatch between what's in the `filescache`, and the re-calculated checksum. So, unless we plant invalid checksums, and have some way of reading the checksum again from the DB, the only tests we could run is, if the commands were successful.

**Comment by phil-davis** [comment]
OK, planting invalid checksums will be "difficult". Just add a test that runs the command and gets a successful checksum verify.

**Comment by skshetry** [comment]
Closing as all commands have been tested.
