### ISSUE TITLE
10.1 - Changelog Test Results

### ISSUE THREAD

**Issue by davitol** [owncloud/core#33624]
# Changelog

All notable changes to this project will be documented in this file.

Items based on https://github.com/owncloud/core/blob/stable10/CHANGELOG.md

### Added
- [x] Allow loading JSON files in setups with pretty URLs - [#32835](https://github.com/owncloud/core/issues/32835) @davitol **phoenix.owncloud.com is running this patch and it works**
- [x] Support global CORS domains for public pages - [#33139](https://github.com/owncloud/core/issues/33139) @davitol **phoenix.owncloud.com is running this patch and it works**
- [x] New tag scope "static tags", editable but not assignable - [#33420](https://github.com/owncloud/core/issues/33420) @davitol **See test steps in the following comment: https://github.com/owncloud/core/pull/33420#issue-228402933**  Issues related: https://github.com/owncloud/core/issues/34002 https://github.com/owncloud/systemtags_management/issues/40
- [x] Added "getBucket" method to HomeObjectStore to fix S3 issue - [#33513](https://github.com/owncloud/core/issues/33513) @davitol **Tests steps in: https://github.com/owncloud/files_primary_s3/issues/152#issue-380113238**

### Changed
- [x] Set shipped apps max version to 10 in preparation for Semver switch - [#33496](https://github.com/owncloud/core/issues/33496 ) @davitol **Tested: Quick OC check and see that files app still displays all sidebar tabs which means the apps were loaded correctly. Increase version.php and check that occ upgrade is not confused by max-version.**
- [x] Disable browser autocomplete for password fields - [#32590](https://github.com/owncloud/core/issues/32590) @davitol **Test steps: Check with Browser Developer tools that autocomplete field is set to "off"**
- [x] Bump punic 3.1.0 => 3.2.0 - [#33462](https://github.com/owncloud/core/issues/33462) @davitol **CI tests works**
- [x] Bump symfony/polyfill components v1.9.0 => v1.10.0 - [#33377](https://github.com/owncloud/core/issues/33377) @davitol **Not related to the release**
- [x] Bump symfony/translation from 3.4.17 to 3.4.18 - [#33429](https://github.com/owncloud/core/issues/33429) **Translations keeps working**
- [x] Bump jakub-onderka/php-console-highlighter from 0.3.2 to 0.4 - [#32944](https://github.com/owncloud/core/issues/32944) => not related to released code @PVince81
- [x] Bump handlebars from 4.0.11 to 4.0.12 in /build - [#32661](https://github.com/owncloud/core/issues/32661) => handlebars template are used in versions sidebar and that worked fine @PVince81
- [x] Bump sinon from 6.2.0 to 7.1.1 - [#32825](https://github.com/owncloud/core/issues/32825) [#33073](https://github.com/owncloud/core/issues/33073) [#33306](https://github.com/owncloud/core/issues/33306) [#33373](https://github.com/owncloud/core/issues/33373)  => not related to released code @PVince81
- [x] Bump league/flysystem from 1.0.46 to 1.0.48 - [#33199](https://github.com/owncloud/core/issues/33199)   => change will not affect OC. unit tests prove that ext storage still works @PVince81
- [x] Bump composer/xdebug-handler to 1.3.0 - [#32977](https://github.com/owncloud/core/issues/32977)  => not related to released code @PVince81
- [x] Bump sabre/dav from 3.2.2 to 3.2.3 - [#33276](https://github.com/owncloud/core/issues/33276) => see PROPFIND infinity fix test result
- [x] Bump friendsofphp/php-cs-fixer (v2.13.0 => v2.13.1) - [#33290](https://github.com/owncloud/core/issues/33290) => not related to released code @PVince81

### Removed
- [x]  Deprecate Sharing 1.0 APIs which will be removed in ownCloud 11 - [#33220](https://github.com/owncloud/core/issues/33220) @davitol **Test steps: a) Quick test in the web UI, sharing still seems to work, so does "unshare from self". b) Retest fed sharing. Tested 10.1 <-> 10.0.9 using HTTP and ```'sharing.federation.allowHttpFallback' => true,```in config.php**

### Fixed
- [x] Fix for some upgrade path that led to DAV tables missing bigint conversion - [#33603](https://github.com/owncloud/core/issues/33603) @davitol **Test steps: Setup OC from scratch and check that every id column of the affected tables now appears as BIGINT on MySQL. List of tables checked here: https://github.com/owncloud/core/issues/32555#issuecomment-439103378**
- [x]  Fix checksum verify command verbose mode and path argument handling - [#33610](https://github.com/owncloud/core/issues/33610) **Test result: https://github.com/owncloud/enterprise/issues/2952#issuecomment-451145760**
- [x] Fix form to enter initial password to properly display error message - [#33453](https://github.com/owncloud/core/issues/33453) @davitol **Test steps detailed in https://github.com/owncloud/core/pull/33453#issue-229002940**
- [x] File cache corruption check now only reports storage id once - [#33539](https://github.com/owncloud/core/issues/33539) **Unit test**
- [x] Fix escaping of public share names - [#33419](https://github.com/owncloud/core/issues/33419) @davitol **Test steps from https://github.com/owncloud/core/pull/33419#issue-228316903**
- [x] Update config.sample.php to fix a broken link - [#33518](https://github.com/owncloud/core/issues/33518) @davitol **Test: Check new tocker page url and the quotes are now in config.sample.php file. Tocker URL works fine**
- [x] Add "uid" argument to Symfony login events for consistency - [#33470](https://github.com/owncloud/core/issues/33470) @davitol **Test steps: add line ```
\OC::$server->getLogger()->warning('I am here with uid = ' . $params['uid'] . ' post login');
``` To see if the `uid` is passed via symfony events in the method post_login(), after line https://github.com/owncloud/admin_audit/blob/master/handlers/session.php#L55**
- [x] Prevent deletion of calendar group shares during cleanup - [#33394](https://github.com/owncloud/core/issues/33394) @davitol **Test steps: https://github.com/owncloud/core/issues/33216#issue-371440835**
- [x] Fix upload avatar for LDAP users - [#33369](https://github.com/owncloud/core/issues/33369) @davitol **Test: Configure an LDAP backend in oC, log in with an LDAP user and upload an avatar via webUI**
- [x] Fix double escaping in email subject - [#33342](https://github.com/owncloud/core/issues/33342) @davitol **Test: Create a file called !@£$%^&*()_.txt and share it, notify by email. Check escaping in email.**
- [x] Add missing type hints in code - [#33314](https://github.com/owncloud/core/issues/33314) @davitol **Test: Test success in Drone, fixed https://drone.owncloud.com/owncloud/core/12056/107**
- [x] Increase versions list performance by ignoring shared storages - [#33291](https://github.com/owncloud/core/issues/33291) @davitol **Automated tests**
- [x]  Fix PROPFIND with Depth infinity requests through Sabre update - [#28341](https://github.com/owncloud/core/issues/28341) **PropFind depth 3 and check it works??**
- [x] Adjust "has never logged in" text in occ command - [#33275](https://github.com/owncloud/core/issues/33275) @davitol **Test steps: https://github.com/owncloud/core/issues/33268#issue-372962613**
- [x] Don't remove temporary file on failure when creating office file preview - [#33234](https://github.com/owncloud/core/issues/33234) @davitol **Test steps: https://github.com/owncloud/core/pull/33232#issue-224346918**
- [x] Warning log about oc_readonly storage wrapper is now logged in debug level - [#33212](https://github.com/owncloud/core/issues/33212) @davitol **Test steps: "Storage wrapper" message no longer appears in warning level but it appears in debug level** 
- [x] Fix occ encrypt-all command to not attempt re-encrypting already encrypted files - [#33206](https://github.com/owncloud/core/issues/33206) @davitol **Test steps: https://github.com/owncloud/encryption/issues/52#issue-357589027**
- [x] Register areCredentialsValid as a sensitive logging method - [#32713](https://github.com/owncloud/core/issues/32713) @davitol **Test steps: connect oC to ldap and cut the connection to the ldap server and try to log in. Check in the owncloud.log that the pwd is not shown  ```OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(203): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)```**
- [x] Deletion of user now also updates storages applicable fields - [#32906](https://github.com/owncloud/core/issues/32906) @davitol **Test steps: https://github.com/owncloud/core/issues/32637#issue-358009322**
- [x] Blacklist the method "setPassword" in stack traces - [#33176](https://github.com/owncloud/core/issues/33176) @davitol **Test steps: connect oC to ldap and cut the connection to the ldap server and try to log in. Check in the owncloud.log that the pwd is not shown**
- [x] Fix wording in occ command help - [#33179](https://github.com/owncloud/core/issues/33179) @davitol **Test: run occ app:list --help and the command output is like the one shown in https://github.com/owncloud/core/pull/33169#issue-222361756**
- [x] Fix preLogin hook parameter inconsistencies - [#33185](https://github.com/owncloud/core/issues/33185) @davitol **Unit test in the PR*

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @ownclouders, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32566 (10.0.10 - Changelog Test Results), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), and https://github.com/owncloud/core/issues/30152 (Testing 10.0.5RC3 Changelog).

**Comment by PVince81** [comment]
- [ ] persistent locking backend + frontend :robot: 
- [ ] OCM :robot: 
- [ ] some extra bugfixes ?

**Comment by davitol** [comment]
Added new entries from PR https://github.com/owncloud/core/pull/33928/files

## Added

- [ ] Added mime types for sharedlib and executable - [#33893](https://github.com/owncloud/core/issues/33893)
- [ ] New tag scope "static tags", editable but not assignable - [#33420](https://github.com/owncloud/core/issues/33420) [#33864](https://github.com/owncloud/core/issues/33864)
- [ ] - Introduce persistent and explicit locking of file and folders - [#33266](https://github.com/owncloud/core/issues/33266) [#33785](https://github.com/owncloud/core/issues/33785) [#33843](https://github.com/owncloud/core/issues/33843)
- [ ] Add sharing scope to enable addressbook sharing with custom groups - [#33849](https://github.com/owncloud/core/issues/33849)
- [ ] Bump symfony 3.4.15 to 3.4.20 - [#33001](https://github.com/owncloud/core/issues/33001) [#33460](https://github.com/owncloud/core/issues/33460) [#33667](https://github.com/owncloud/core/issues/33667) [#33821](https://github.com/owncloud/core/issues/33821)
- [ ] Patch bumps punic pear-core-minimal xdebug-handler - [#33830](https://github.com/owncloud/core/issues/33830)

### Fixed

- [ ] Return 403 instead of 500 status when uploading into share without write permissions - [#33640](https://github.com/owncloud/core/issues/33640)
- [ ] Fix performance issue when fetching versions: do not iterate over all storages when only first is needed - [#33859](https://github.com/owncloud/core/issues/33859)
- [ ] Config sample asciidoc fixes - [#33870](https://github.com/owncloud/core/issues/33870)
- [ ]  Correction to default apps folder in config.sample.php - [#33912](https://github.com/owncloud/core/issues/33912)


## Changed

 -  [ ] Bypass apps max-version check for daily/git release channels - [#33861](https://github.com/owncloud/core/issues/33861)
- [ ]  - Changed default link share name to be "Public link" - [#33879](https://github.com/owncloud/core/issues/33879)

**Comment by davitol** [comment]
Added new entries from PR https://github.com/owncloud/core/pull/33958/

## Added

- [ ] Introduce persistent and explicit locking of file and folders (Webdav locks) - [#33266](https://github.com/owncloud/core/issues/33266) [#33785](https://github.com/owncloud/core/issues/33785) [#33843](https://github.com/owncloud/core/issues/33843) [#33957](https://github.com/owncloud/core/pull/33957)
- [ ] Add minimal frontend in files app for persistent locks (Webdav locks) - [#33951](https://github.com/owncloud/core/issues/33951)
- [ ] Add X-Request-ID to header Access-Control-Allow-Headers - [#33926](https://github.com/owncloud/core/issues/33926)

## Changed

- [ ] Use new DAV endpoint in web UI file list and upload - [#33544](https://github.com/owncloud/core/issues/33544)
- [ ] Changed default link share name to be "Public link" - [#33879](https://github.com/owncloud/core/issues/33879) [#33955](https://github.com/owncloud/core/issues/33955)
- [ ] Bump composer/xdebug-handler to 1.3.0 - [#32977](https://github.com/owncloud/core/issues/32977)
- [ ] Bump friendsofphp/php-cs-fixer (v2.13.0 => v2.13.1) - [#33290](https://github.com/owncloud/core/issues/33290)
- [ ] Bump hoek from 4.2.0 to 4.2.1 in /build - [#33574](https://github.com/owncloud/core/issues/33574)
- [ ] Bump jakub-onderka/php-console-highlighter from 0.3.2 to 0.4 - [#32944](https://github.com/owncloud/core/issues/32944)
- [ ] Bump lodash from 4.17.4 to 4.17.11 in /build - [#33754](https://github.com/owncloud/core/issues/33754)
- [ ] Bump phpseclib/phpseclib from 2.0.11 to 2.0.13 - [#33433](https://github.com/owncloud/core/issues/33433) [#33922](https://github.com/owncloud/core/issues/33922)
- [ ] Bump punic 3.1.0 => 3.2.0 - [#33462](https://github.com/owncloud/core/issues/33462)
- [ ] Bump sinon from 6.2.0 to 7.1.1 - [#32825](https://github.com/owncloud/core/issues/32825) [#33073](https://github.com/owncloud/core/issues/33073) [#33306](https://github.com/owncloud/core/issues/33306) [#33373](https://github.com/owncloud/core/issues/33373)
- [ ] Bump squizlabs/php_codesniffer 3.3.2=>3.4.0 - [#33940](https://github.com/owncloud/core/issues/33940)
- [ ] Bump symfony 3.4.15 to 3.4.20 - [#33001](https://github.com/owncloud/core/issues/33001) [#33460](https://github.com/owncloud/core/issues/33460) [#33667](https://github.com/owncloud/core/issues/33667) [#33821](https://github.com/owncloud/core/issues/33821)
- [ ] Bump symfony/polyfill components v1.9.0 => v1.10.0 - [#33377](https://github.com/owncloud/core/issues/33377)
- [ ] Bump symfony/translation from 3.4.17 to 3.4.18 - [#33429](https://github.com/owncloud/core/issues/33429)
- [ ] Bump zendframework/zend-inputfilter from 2.8.2 to 2.9.0 - [#33920](https://github.com/owncloud/core/issues/33920)

## Fixed

- [ ] Fix up grammar mistake in console output - [#33947](https://github.com/owncloud/core/issues/33947)
- [ ] Expand occ user reset password email validation - [#33945](https://github.com/owncloud/core/issues/33945)
- [ ] Config sample fixes - [#33870](https://github.com/owncloud/core/issues/33870) [#33954](https://github.com/owncloud/core/issues/33954)

**Comment by PVince81** [comment]
effort for testing was estimated to 5md

**Comment by mmattel** [comment]
## Added ##

[ ] show a short list of mount infos: files_external:list --short #32178

**Comment by davitol** [comment]
-[ ] PROPFIND without any properties locks up the server https://github.com/owncloud/enterprise/issues/3071

**Comment by davitol** [comment]
Test Locking files:

1) Using Libre Office:

![screen shot 2019-01-14 at 12 05 18](https://user-images.githubusercontent.com/10596560/51109765-8149c580-17f6-11e9-92a6-1a7d81706495.png)

JFYI Files are locked for PUT (modifying) but not for GET (download)

```
curl -u admin -X PUT http://10.40.40.222:9681/remote.php/dav/files/admin/pedro.txt
Enter host password for user 'admin':
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Locked</s:exception>
  <s:message/>
  <d:lock-token-submitted>
    <d:href>files/admin/pedro.txt</d:href>
  </d:lock-token-submitted>
</d:error>
➜  ~ curl -v -u admin -X PUT http://10.40.40.222:9681/remote.php/dav/files/admin/pedro.txt
Enter host password for user 'admin':
*   Trying 10.40.40.222...
* TCP_NODELAY set
* Connected to 10.40.40.222 (10.40.40.222) port 9681 (#0)
* Server auth using Basic with user 'admin'
> PUT /remote.php/dav/files/admin/pedro.txt HTTP/1.1
> Host: 10.40.40.222:9681
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 423 Locked
< Date: Mon, 14 Jan 2019 11:12:03 GMT
< Server: Apache
< Strict-Transport-Security: max-age=15768000; preload
< Set-Cookie: octsafs3v5s3=2tr0ksdbknmn36toqjdknoe81n; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=8dWapbLDG9zt9p%2FQKo1ZRZy6mJWgu3aM%2BqZF0WyLJBNFgBQt1PD6%2F0T1fYUaXRK3uZ3ybL%2FduUshfPWbKkqLsQgip1v7GfR8O1NpznyCVOnm0iy858lFAcSxB49tSQvB; path=/; HttpOnly
< Content-Security-Policy: default-src 'none';
< Set-Cookie: octsafs3v5s3=m19uhgaela3vr967v90dn08ka2; path=/; HttpOnly
< Set-Cookie: cookie_test=test; expires=Mon, 14-Jan-2019 12:12:06 GMT; Max-Age=3600
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Length: 277
< Content-Type: application/xml; charset=utf-8
<
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Locked</s:exception>
  <s:message/>
  <d:lock-token-submitted>
    <d:href>files/admin/pedro.txt</d:href>
  </d:lock-token-submitted>
</d:error>
* Connection #0 to host 10.40.40.222 left intact
```


Using latest ownCloud Android App version. Trying to modify the locked file we can see it is not possible:

![request](https://user-images.githubusercontent.com/10596560/51109973-31b7c980-17f7-11e9-9a39-f0f3ad26a296.png)

![response](https://user-images.githubusercontent.com/10596560/51109976-35e3e700-17f7-11e9-8a9f-72ac1bee23cf.png)




Also we can see the lock in the Database:


```
select * from oc_persistent_locks;
+----+---------+------------------+-------------------------------------------+---------+------------+--------------------------------------+----------------------------------+-------+-------+
| id | file_id | owner_account_id | owner                                     | timeout | created_at | token                                | token_hash                       | scope | depth |
+----+---------+------------------+-------------------------------------------+---------+------------+--------------------------------------+----------------------------------+-------+-------+
|  1 |      17 |                1 | LibreOffice - http://www.libreoffice.org/ |    1800 | 1547463538 | ee52cd2e-6975-4593-b3e9-6de3ebe1101b | 6386a195e1cb5b97b929bc73db7fa6f4 |     1 |     0 |
+----+---------+------------------+-------------------------------------------+---------+------------+--------------------------------------+----------------------------------+-------+-------+
```

**Comment by davitol** [comment]
Added new entries from PR https://github.com/owncloud/core/pull/34278/

### Added

- [ ] Added Symfony event for federation to provide apps with federated share receiver id - [#34152](https://github.com/owncloud/core/issues/34152)
-[ ]  New tag scope "static tags", editable but not assignable [#34098](https://github.com/owncloud/core/issues/34098)
- [ ] Introduce persistent and explicit locking of file and folders (Webdav locks) #34270](https://github.com/owncloud/core/issues/34270) [#34267](https://github.com/owncloud/core/issues/34267) [#34227](https://github.com/owncloud/core/issues/34227) [#34208](https://github.com/owncloud/core/issues/34208) [#34203](https://github.com/owncloud/core/issues/34203)
- [ ] Federated sharing new spec OCM 1.0-proposal1 -  [#34252](https://github.com/owncloud/core/issues/34252)
- [ ] If only the patch level of an app's version changes no migrations will run - [#33218](https://github.com/owncloud/core/issues/33218) [#34138](https://github.com/owncloud/core/issues/34138)
- [ ] Bump handlebars from 4.0.11 to 4.0.12 in /build [#34071](https://github.com/owncloud/core/issues/34071)
- [ ] Bump pear/archive_tar from 1.4.3 to 1.4.5 - [#34080](https://github.com/owncloud/core/issues/34080)

### Fixed

- [ ] Fix missing translations in the user settings module - [#34234](https://github.com/owncloud/core/issues/34234) [#34261](https://github.com/owncloud/core/issues/34261)
- [ ] Skip preview expiry when owner cannot be determined - [#34207](https://github.com/owncloud/core/issues/34207)
- [ ] Allow the testing app to not be in the default apps folder - [#34196](https://github.com/owncloud/core/issues/34196)

**Comment by davitol** [comment]
Added new entries from 10.1. RC2 PR https://github.com/owncloud/core/pull/34373/

**Comment by davitol** [comment]
- [ ] Introduce persistent and explicit locking of file and folders (Webdav locks) - (https://github.com/owncloud/core/issues/34355) (https://github.com/owncloud/core/issues/34350)
- [ ] Bump @bower_components/browser-update from 2.0.1 to v2.0.2 in /build - (https://github.com/owncloud/core/issues/34290)
