### ISSUE TITLE
Add test scenarios for trying to reshare when user is in a group excluded from sharing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33824]
There are already some acceptance test scenarios that check that, for a user in a group that is excluded from sharing, that user cannot create a share of their own file or folder.
``tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature``
```
  Scenario: user tries to share a file in a group which is blacklisted from sharing
  Scenario: user tries to share a folder in a group which is blacklisted from sharing
```

- [x] add scenarios to check that the user cannot reshare a share that they received from someone else, consider:
- [x] reshare a single file received as a share #33865
- [x] reshare a folder received as a share #33865
- [x] reshare a file inside a folder received as a share #33865
- [x] reshare a folder inside a folder received as a share #33865

None of these should be possible.

Ref: https://github.com/owncloud/enterprise/issues/3037

**Comment by paurakhsharma** [comment]
@phil-davis  Turns out owncloud/enterprise#3037 is only UI bug where sharing dialog box shows field to enter the name of sharee. PR #33865 doesn't use UI to verify that. It only checks if the user is not allowed to share. New PR needs to be made to verify owncloud/enterprise#3037 where we should use UI to verify this.

**Comment by phil-davis** [comment]
Yes, the webUI is probably using its "private" API. The public sharing API is working, the new tests demonstrate that. I guess the private API used by the webUI will be not doing the needed checks.

**Comment by paurakhsharma** [comment]
@phil-davis  Do we close this now?

**Comment by phil-davis** [comment]
Done - tests for attempting to reshare have been merged.

**Comment by phil-davis** [comment]
I raised issue #33918 to deal with the webUI issue.
