### ISSUE TITLE
Expand apiFederation acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34149]
The current set of federation API-based acceptance tests is quite small. See ``tests/acceptance/features/apiFederation``

Create more feature files to cover something like:
- [x] user can federated-share a file or folder
- [x] federated share receiver can see the pending shared file or folder
- [x] federated share receiver can accept the pending shared file or folder
- [x] original content can all be seen by the federated share receiver (files in root, files in multiple levels of folders)  #37077
- [x] sharer can add/modify/delete/move files/folders at multiple levels in the share and the federated share receiver sees the changes #37081
- [x] the federated share receiver can add/modify/delete/move files/folders at multiple levels in the share and the sharer sees the changes #37086
- [x] the sharer can unshare and the receiver no longer sees the files/folders #37090
- [x] the federated share receiver can move the location of the received share, and still see the files and changes are still correctly seen at both ends #37102
- [x] the sharer can move/rename the original shared file/folder and the federated share receiver still sees the received share and changes are still correctly seen at both ends #37102

Note also issue #32066 which calls for test scenarios that have combinations of incoming/outgoing federation sharing enabled/disabled.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/33422 (Extend federation acceptance tests), https://github.com/owncloud/core/pull/33506 (Adding more federation acceptance tests), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), and https://github.com/owncloud/core/issues/22492 (test).

**Comment by phil-davis** [comment]
There is enough range of test coverage now - closing.
