### ISSUE TITLE
10.2 - Changelog Test Results - Removed

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35053]
Part of #35020

### Removed

- [x] Drop PHP 5.6 support across the platform - [#34698](https://github.com/owncloud/core/issues/34698) - CI plus try to run with PHP 5.6 and the UI complains nicely @phil-davis 
- [x] Removed bundled documentation, help links now point to the online documentation - [#34612](https://github.com/owncloud/core/issues/34612) [#34649] (https://github.com/owncloud/core/issues/34649) @dpakach
- [x] Remove incompatible script for generating DB changeset - [#34722](https://github.com/owncloud/core/issues/34722) - @dpakach 
- [x] Remove classes that were deprecated since OC 8.0.0: OCP\Config, OCP\PERMISSION_XXX, OCP\Template - [#34927](https://github.com/owncloud/core/issues/34927) - code looks good, must have covered by :robot: @dpakach
