### ISSUE TITLE
10.2 - Changelog Test Results - Changed

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35052]
Part of #35020

### Changed

- [x] Bump @bower_components/bowser from 1.6.0 to 1.9.4 in /build - [#34844](https://github.com/owncloud/core/issues/34844) @dpakach
- [x] Bump @bower_components/backbone from 1.2.3 to 1.4.0 in /build - [#34288](https://github.com/owncloud/core/issues/34288) [#34621](https://github.com/owncloud/core/issues/34621) - tested with comments panel, create+edit still works - @PVince81
- [x] Bump @bower_components/base64 from 0.3.0 to 1.0.2 in /build - [#34542](https://github.com/owncloud/core/issues/34542) - hoping :robot: would have caught any issues
- [x] Bump @bower_components/clipboard from 1.5.12 to v2.0.4 in /build - [#34620](https://github.com/owncloud/core/issues/34620) - copy public link with clipboard button still works - @PVince81
- [x] Bump @bower_components/bootstrap from 3.3.6 to 3.3.7 in /build - [#34843](https://github.com/owncloud/core/issues/34843) @dpakach
- [x] Bump @bower_components/handlebars from v4.0.12 to v4.1.1 in /build - [#34454](https://github.com/owncloud/core/issues/34454) [#34802](https://github.com/owncloud/core/issues/34802) - share dialog template renders fine - @PVince81
- [x] Bump @bower_components/moment from 2.22.0 to 2.24.0 in /build - [#34459](https://github.com/owncloud/core/issues/34459) - human date format in file list works fine - @PVince81
- [x] Bump @bower_components/strengthify from 0.5.2 to 0.5.6 in /build - [#34451](https://github.com/owncloud/core/issues/34451) - @dpakach 
- [x] Bump @bower_components/underscore from 1.8.3 to 1.9.1 in /build - [#34457](https://github.com/owncloud/core/issues/34457) - @dpakach 
- [x] Bump composer/semver from 1.4.2 to 1.5.0 - [#34882](https://github.com/owncloud/core/pull/34882) - CI-related, OK @phil-davis 
- [x] Bump extend from 3.0.1 to 3.0.2 in /build - [#34411](https://github.com/owncloud/core/issues/34411) - security fix - :robot: & smoke test - @individual-it 
- [x] Bump handlebars from 4.0.12 to 4.1.1 in /build - [#34456](https://github.com/owncloud/core/issues/34456) [#34801](https://github.com/owncloud/core/issues/34801) - :robot: & smoke test - @individual-it 
- [x] Bump karma from 3.1.3 to 4.0.1 in /build - [#34458](https://github.com/owncloud/core/issues/34458) [#34675](https://github.com/owncloud/core/issues/34675) :robot: @dpakach 
- [x] Bump icewind/smb from 3.0.0 to 3.1.1 in /apps/files_external/3rdparty - [#34670](https://github.com/owncloud/core/issues/34670) - smoke test with files_external accessing smb server - @individual-it
- [x] Bump icewind/streams from 0.5.2 to 0.7.1 in /apps/files_external/3rdparty - [#34537](https://github.com/owncloud/core/issues/34537) - smoke test with files_external accessing smb server - @individual-it
- [x] Bump icewind/streams from 0.5.2 to 0.7.1 - [#34617](https://github.com/owncloud/core/issues/34617) - smoke test with files_external accessing smb server - @individual-it
- [x] Bump league flysystem 1.0.51 - [#34417](https://github.com/owncloud/core/issues/34417) [#34946](https://github.com/owncloud/core/issues/34946) :robot: is testing a lot of filesystem scenarios including S3
- [x] Bump react promise v2.7.1 - [#34416](https://github.com/owncloud/core/issues/34416) - hoping :robot: would have caught any issues
- [x] Zendframework bumps 20190208 - [#34413](https://github.com/owncloud/core/issues/34413) - covered by CI plus smoketest @phil-davis 
- [x] Bump paragonie/random_compat v2.0.17 => v2.0.18 - [#34043](https://github.com/owncloud/core/issues/34043) - hoping :robot: would have caught any issues
- [x] Bump pear/archive_tar from 1.4.6 to 1.4.7 - [#34990](https://github.com/owncloud/core/issues/34990)
- [x] Bump phpseclib/phpseclib from 2.0.13 to 2.0.15 - [#34285](https://github.com/owncloud/core/issues/34285) [#34741](https://github.com/owncloud/core/issues/34741) - hoping :robot: would have caught any issues
- [x] Bump pimple/pimple from 3.0.2 to 3.2.3 - [#31753](https://github.com/owncloud/core/issues/31753) - hoping :robot: would have caught any issues
- [x] Bump sinon from 7.1.1 to 7.3.1 in /build - [#34881](https://github.com/owncloud/core/issues/34881) [#34943](https://github.com/owncloud/core/issues/34943) :robot: @dpakach 
- [x] Bump symfony v3.4.20 => v3.4.24 - [#34042](https://github.com/owncloud/core/issues/34042) [#34663](https://github.com/owncloud/core/issues/34663) [#34954](https://github.com/owncloud/core/issues/34954) - covered by CI plus smoketest @phil-davis
- [x] Bump symfony/process from 3.4.21 to 3.4.22 - [#34407](https://github.com/owncloud/core/issues/34407) - covered by CI plus smoketest @phil-davis
- [x] Bump symfony/translation from 3.4.21 to 3.4.22 - [#34406](https://github.com/owncloud/core/issues/34406) - covered by CI plus smoketest @phil-davis
- [x] Bump symfony/console from 3.4.21 to 3.4.22 - [#34404](https://github.com/owncloud/core/issues/34404) - covered by CI plus smoketest @phil-davis
- [x] Bump symfony/polyfill components from v1.10.0 to v1.11.0 - [#34882](https://github.com/owncloud/core/pull/34882) - covered by CI plus smoketest @phil-davis
- [x] Bump symfony/routing from 3.4.21 to 3.4.22 - [#34408](https://github.com/owncloud/core/issues/34408) - covered by CI plus smoketest @phil-davis
- [x] Bump symfony/event-dispatcher from 3.4.21 to 3.4.22 - [#34405](https://github.com/owncloud/core/issues/34405) - covered by CI plus smoketest @phil-davis
- [x] Bump remaining symfony 3.4.22 components - [#34412](https://github.com/owncloud/core/issues/34412) - covered by CI plus smoketest @phil-davis
- [x] Bump deepdiver1975/tarstreamer from 0.1.0 to 0.1.1 - [#34615] (https://github.com/owncloud/core/issues/34615) - @dpakach  -> tested by @patrickjahns 
- [x] Bump zendframework/zend-servicemanager from 3.3.2 to 3.4.0 - [#33971](https://github.com/owncloud/core/issues/33971) hopefully covered by :robot: 
- [x] Bump zendframework/zend-inputfilter from 2.9.0 to 2.9.1 - [#34145](https://github.com/owncloud/core/issues/34145) hopefully covered by :robot:
- [x] Bump dependencies after PHP 5.6 deprecation, swiftmailer 6.2 - [#34755](https://github.com/owncloud/core/issues/34755) - :robot: Covered by CI and smoke test @dpakach 
- [x] Bump README.md doc links to 10.1 - [#34403](https://github.com/owncloud/core/issues/34403) - link invalid, issue #35035 - @dpakach
- [x] Updating phpunit/phpunit (5.7.27 => 6.5.14) - [#34866](https://github.com/owncloud/core/issues/34866) - CI and testing only, works @phil-davis 
- [x] Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0) - [#34920](https://github.com/owncloud/core/issues/34920) - CI and testing only, works @phil-davis 
- [x] Increase size of login_name from 64 to 255 - [#34280](https://github.com/owncloud/core/issues/34280) @dpakach 
- [x] Warn when .htaccess file is not writable - [#34486](https://github.com/owncloud/core/issues/34486) [#34461](https://github.com/owncloud/core/issues/34461)  @dpakach 
- [x] Add password confirmation field when resetting password - [#34492](https://github.com/owncloud/core/issues/34492) [#34834](https://github.com/owncloud/core/issues/34834) @dpakach
- [x] Add email footer with motto in email for changing password - [#34498](https://github.com/owncloud/core/issues/34498) @dpakach 
- [x] Change the styling of the active settings navigation menu item - [#34561](https://github.com/owncloud/core/issues/34561) => section is bold in files app and settings page :white_check_mark: - @PVince81
- [x] Added delay in search field - [#34613](https://github.com/owncloud/core/issues/34613) @dpakach 
- [ ] Tidy up code for notification by email - [#34786](https://github.com/owncloud/core/issues/34786) :no_entry_sign: :  raised  #35089 - fixed in RC2 [#35137] (https://github.com/owncloud/core/issues/35137) - @dpakach  - raised #35218
- [x] Some code now made PHP 7 specific - [#34925](https://github.com/owncloud/core/issues/34925) - covered by CI plus smoketest @phil-davis

**Comment by phil-davis** [comment]
Bump README.md doc links to 10.1 - #34403 - the link is invalid, issue #35035
It looks like it has been invalid at least since the docs conversion, and has been pointing into an odd place for a long time. PR #35036 to master.

**Comment by dpakach** [comment]
Notify by email on group share can be done multiple times #35089

**Comment by patrickjahns** [comment]
Tested tar_streamer - works as expected.
Do we have a webui/api test for this? Otherwise we might add downloading a tar archive to the acceptance tests ( one for zip and one for tar )

**Comment by individual-it** [comment]
@patrickjahns thank you for testing, no tests for that AFAIK, please open an issue so we can schedule adding the tests

**Comment by individual-it** [comment]
@dpakach please retest: Tidy up code for notification by email - it was fixed in RC2 [#35137](https://github.com/owncloud/core/issues/35137)

**Comment by individual-it** [comment]
updated the list above with changes in RC2 listed in e801e4e

**Comment by dpakach** [comment]
@individual-it tested  #35137 in RC2. Works fine.

**Comment by individual-it** [comment]
new regression found while writing acceptance tests
 Sharer gets "Email notification was sent!" message even when the email was not sent  - #35218

**Comment by PVince81** [comment]
close ?

please raise tickets for the other "to automate" tests before closing if not done already

**Comment by individual-it** [comment]
I think we are done here for now
list for tests to be automated here https://github.com/owncloud/core/issues/35207
