### ISSUE TITLE
10.2 - Changelog Test Results - Added

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35051]
Part of  #35020

### Added

- [x] Add new capability to advertise the availability of the detail parameter for private links (RC2) - [#35104](https://github.com/owncloud/core/issues/35104) - @individual-it 
- [x] Add background:queue:execute occ command for running cron jobs manually - [#34995](https://github.com/owncloud/core/issues/34995)  - @individual-it
- [ ] Adding background:queue commands: status and delete - [#34783](https://github.com/owncloud/core/issues/34783) :no_entry_sign: issue #35222
- [ ] Added new permissions option for public link - [#34983](https://github.com/owncloud/core/issues/34983)  raised  #35056 & #35057  - fixed in RC2 #35082 - :no_entry_sign: other issue #35155 @individual-it @dpakach 
- [x] Support for extra share key-value attributes - [#34951](https://github.com/owncloud/core/issues/34951) :robot: (unit)
- [x] Internal permission to prevent file download when set in share attribute, for "secure view" feature  - [#34951](https://github.com/owncloud/core/issues/34951) [#35095](https://github.com/owncloud/core/issues/35095) :robot: (unit)
- [x] Support for automatically accepting incoming federated shares from trusted servers - [#34206](https://github.com/owncloud/core/issues/34206) - raised #35067 - fixed in RC2 [#35135](https://github.com/owncloud/core/issues/35135) - @individual-it 
- [x] User option for automatically accepting incoming shares - [#34647](https://github.com/owncloud/core/pull/34647) [#34842](https://github.com/owncloud/core/pull/34842) [#34934](https://github.com/owncloud/core/issues/34934)
- [x] User option for automatically accepting incoming federated shares - [#34706](https://github.com/owncloud/core/issues/34706)
- [x] User option to opt-out autocomplete in share dialog - [#34942](https://github.com/owncloud/core/issues/34942) - @individual-it 
- [x] Add before-after share link auth events - [#34399](https://github.com/owncloud/core/issues/34399) :robot: (unit)
- [x] Log broken smb config params for easier debugging - [#34056](https://github.com/owncloud/core/issues/34056) - @individual-it 
- [x] Add support for detecting library mime types - [#34082](https://github.com/owncloud/core/issues/34082) - @individual-it 
- [x] Extend repair command to be able to list repair steps and run them individually - [#34499](https://github.com/owncloud/core/issues/34499) - @individual-it 
- [x] Added CORS headers for many existing API calls, required for Phoenix  - [#34476](https://github.com/owncloud/core/issues/34476) - @individual-it & :robot:  #34665 #34697
- [ ] Encryption now supports working with a Hardware Security Module - [#34527](https://github.com/owncloud/core/issues/34527) :no_entry_sign: crash in hsmdaemon https://gitea.int.owncloud.com/consulting/hsmdaemon/issues/6
- [x] Command for first run wizard to reset for all users - [firstrunwizard/#83](https://github.com/owncloud/firstrunwizard/pull/83) => already tested here https://github.com/owncloud/firstrunwizard/issues/102
- [x] Inform admin about the need to login again after changing the master encryption key - [#34596](https://github.com/owncloud/core/issues/34596) - @individual-it 
- [x] Added checkboxes to hide quota and password - [#34479](https://github.com/owncloud/core/issues/34479) - @individual-it
- [ ] By default the "apps-external" directory is included in config.php during installation - [#34656](https://github.com/owncloud/core/issues/34656) [#34902](https://github.com/owncloud/core/issues/34902) => directly exists but core doesn't function correctly :no_entry_sign: raised https://github.com/owncloud/core/issues/35031 - @PVince81
- [x] Added files:scan --group and --groups options - [#34754](https://github.com/owncloud/core/issues/34754) - @individual-it
- [x] Allow admins to enable medial search on group and user - [#34779](https://github.com/owncloud/core/issues/34779) :heavy_check_mark: known issue with LDAP #35066 @individual-it 
- [x] Add composer cleaner - [#34784](https://github.com/owncloud/core/issues/34784) :robot: (unit)
- [x] Add events for user preference changes - [#34820](https://github.com/owncloud/core/issues/34820)  :robot: (unit)
- [x] Add occ command to poll incoming federated shares for updates - [#34933](https://github.com/owncloud/core/issues/34933) [#34959](https://github.com/owncloud/core/issues/34959) [#34993](https://github.com/owncloud/core/issues/34993) - RC2: [#35073](https://github.com/owncloud/core/issues/35073)  -  @individual-it

**Comment by individual-it** [comment]
conflict dialogue for "Download / View / Upload" public link shows folder-size not file-size #35056

**Comment by individual-it** [comment]
conflict dialogue for "Download / View / Upload" public link multiplies the conflict files on "cancel" #35057

**Comment by individual-it** [comment]
medial search on group does not work with LDAP groups #35066

**Comment by individual-it** [comment]
automatically accept incoming federated shares generate a notification, accepting the share from there renames it #35067

**Comment by individual-it** [comment]
there is a problem in the hsmdaemon see https://gitea.int.owncloud.com/consulting/hsmdaemon/issues/6

**Comment by patrickjahns** [comment]
To be tested with RC2:
- Added new permissions option for public link - #34983 🚫 raised #35056 & #35057 - @individual-it

**Comment by individual-it** [comment]
updated also the list above with changes listed in https://github.com/owncloud/core/commit/e801e4eefa51f5d8a9d82560331d035f89ee693e and will retest them

**Comment by individual-it** [comment]
@dpakach  found  a new issue - Cannot change public link share permission to Download/View/Upload #35155

**Comment by individual-it** [comment]
`background:queue:status` throws error when trying to list fed-sharing jobs #35222

**Comment by PVince81** [comment]
close ?

**Comment by individual-it** [comment]
I think we are done here for now
list for tests to be automated here https://github.com/owncloud/core/issues/35207
