### ISSUE TITLE
10.2 - Changelog Test Results - Fixed

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35054]
Part of #35020

### Fixed
- [x] Wrong translation file referenced for accept & decline share - [#35063](https://github.com/owncloud/core/issues/35063) - @individual-it 
- [x] Respect 'writable' appdir flag on update - [#35097](https://github.com/owncloud/core/issues/35097) - @individual-it 
- [x] Fix regression with missing progress bar in files drop view - [#35059](https://github.com/owncloud/core/issues/35059) - @individual-it 
- [x] Log exception when background job class not found - [#34723](https://github.com/owncloud/core/issues/34723) @paurakhsharma 
- [x] Prevent concurrent updates in group shares to avoid duplicate entries - [#34769](https://github.com/owncloud/core/issues/34769) :robot: - see https://github.com/owncloud/core/issues/35054#issuecomment-487001623
- [x] Calender invitation now uses actual sender name - [#34901] (https://github.com/owncloud/core/issues/34901) @paurakhsharma 
- [x] Fix public link share default expiration behavior - [#34971](https://github.com/owncloud/core/issues/34971)  @skshetry 
- [x] Improve files error handling on download - [#34886](https://github.com/owncloud/core/issues/34886) - @individual-it 
- [x] Directly honour robots.txt if htaccess.RewriteBase is set - [#34949](https://github.com/owncloud/core/issues/34949) - @individual-it 
- [x] Reduce sharing query size by properly reusing the query builder - [#34915](https://github.com/owncloud/core/issues/34915) :robot:  CI and smoke-test
- [x] Tar download support for file names longer than 99 chars - [#34615](https://github.com/owncloud/core/issues/34615) @skshetry 
- [x] Fix Webdav error page, include CSP and message - [#34817](https://github.com/owncloud/core/issues/34817) - @individual-it 
- [x] Handle accept decline with invalid share id - [#34786](https://github.com/owncloud/core/issues/34786) - @dpakach
- [x] Normalize path when moving chunks to final destination - [#34777](https://github.com/owncloud/core/issues/34777) :robot: (admin_audit)
- [x] Better support for international email addresses after swiftmailer update - [#34759](https://github.com/owncloud/core/issues/34759) @paurakhsharma 
- [x] Fix first time login handling - [#34758](https://github.com/owncloud/core/issues/34758) @DeepDiver1975 
- [x] Server container interface should inherit from icontainer,… - [#34756](https://github.com/owncloud/core/issues/34756) :robot: 
- [x] Don't expose hashed password in OCS api - [#34691](https://github.com/owncloud/core/issues/34691) - share_with="**redacted**" now - @PVince81
- [x] Fixes UID issue with birthday calendar events - [#34701](https://github.com/owncloud/core/issues/34701) @paurakhsharma 
- [x] Improve avatar performance by having many avatar related calls bypass the file cache - [#34592](https://github.com/owncloud/core/issues/34592) @paurakhsharma 
- [x] Improve speed of apps list settings page by caching integrity check results - [#34584](https://github.com/owncloud/core/issues/34584) @skshetry 
- [x] Fix chunking infinite loop in some environment related issues - [#34558](https://github.com/owncloud/core/issues/34558) @skshetry 
- [x] Fixes issue file picker choose button disabled for directory selection - [#34426](https://github.com/owncloud/core/issues/34426) @paurakhsharma 
- [x] Use sabre/vobject ^4.2 to fix issues in ITip messages - [#34553](https://github.com/owncloud/core/issues/34553) @paurakhsharma 
- [x] Filter static tags when searching files by tag - [#34557](https://github.com/owncloud/core/issues/34557) @skshetry 
- [x] Fix collaborative tags PHP API for get and create operations - [#34610](https://github.com/owncloud/core/issues/34610) - hope :robot: would have caught any issue
- [x] Improve performance of account sync service - [#34546](https://github.com/owncloud/core/issues/34546) :robot: (in LDAP)
- [x] Improve code occ files_external:list --short - [#34549](https://github.com/owncloud/core/issues/34549) @skshetry 
- [x] Fix preview expiration issues with trashbin/versions - [#34533](https://github.com/owncloud/core/issues/34533) @paurakhsharma 
- [x] Use the displayname in lost password emails where possible - [#34512](https://github.com/owncloud/core/issues/34512) @paurakhsharma 
- [x] Store quota overrides in preferences table - [#34467](https://github.com/owncloud/core/issues/34467) @dpakach
- [x] Prevent password removal in share dialog if enforced - [#34497](https://github.com/owncloud/core/issues/34497) @skshetry 
- [x] Encryption now skips shared files when adding recovery key - [#34506](https://github.com/owncloud/core/issues/34506) @sharidas 
- [x] Fix encryption to use API instead of config access - [#34504](https://github.com/owncloud/core/issues/34504) @paurakhsharma 
- [x] Properly handle StorageNotAvailableException in Webdav endpoint - [#34485](https://github.com/owncloud/core/issues/34485) - @individual-it 
- [x] Properly hide share fields in "Shared with You" section when permissions are restricted - [#34473](https://github.com/owncloud/core/issues/34473) @paurakhsharma 
- [x] Repair subshares earlier to avoid errors - [#34462](https://github.com/owncloud/core/issues/34462) - ❌  No way to reproduce @skshetry 
- [x] Only parse info.xml once to improve performance for every request - [#34482](https://github.com/owncloud/core/issues/34482) - smoke tests enable/disable/use various apps @individual-it 
- [x] Catch errors when info.xml is malformed - [#34427](https://github.com/owncloud/core/issues/34427) @paurakhsharma 
- [x] Send OCM requests as JSON - [#34424](https://github.com/owncloud/core/issues/34424) - @dpakach 
- [x] Remove composer that is now in vendor bin - [#34418](https://github.com/owncloud/core/issues/34418) - related to CI test tooling moving to vendor-bin, CI still passes @phil-davis 
- [x] Use recipient language when sending notification email - [#34255](https://github.com/owncloud/core/issues/34255) @paurakhsharma 
- [x] Fix shares not accessible for guest users when using "share_folder" config option - [#34395](https://github.com/owncloud/core/issues/34395) @skshetry 
- [x] Fix reset confirmation mail from occ - [#34154](https://github.com/owncloud/core/issues/34154) @skshetry 
- [x] Correctly write Login failed entry in log when 2FA is enforced - [#34055](https://github.com/owncloud/core/issues/34055) @skshetry 
- [x] Center the logo and login fields - [#34057](https://github.com/owncloud/core/issues/34057) @skshetry 
- [x] Fix Apache warnings by setting headers to "always" in htaccess - [#34089](https://github.com/owncloud/core/issues/34089) - :no_entry_sign: - raised #35093 - fixed in RC2  [#35118](https://github.com/owncloud/core/issues/35118) - @individual-it
- [x] Fix external storage advanced checkbox state issue - [#34168](https://github.com/owncloud/core/issues/34168) @skshetry 
- [x] Set permissions on log file creation instead of every write - [#34061](https://github.com/owncloud/core/issues/34061) - @individual-it 
- [x] Images are again properly rotated now based on EXIF rotation - [#34356] (https://github.com/owncloud/core/issues/34356) @paurakhsharma 
- [x] Fix query parts for federated shares to be less expensive - [#34401](https://github.com/owncloud/core/issues/34401) - :robot: 
- [x] Fix cancel upload and hide 'uploading' message for files_drop shared folders - [#34097](https://github.com/owncloud/core/issues/34097) :no_entry_sign: raised #35086 - fixed in RC2 [#35134](https://github.com/owncloud/core/issues/35134)  - @skshetry

**Comment by skshetry** [comment]
#34971 
Location of "Enforce date" changed from `10.1` which was as below:
![Screenshot from 2019-04-23 11-51-02](https://user-images.githubusercontent.com/18718008/56558340-1ca0c280-65be-11e9-8c10-189367b9ff4a.png)

And, when expiration date is unenforced and default share is removed on public link share, no expiration date is set.

**Comment by skshetry** [comment]
Regarding #34097:

Canceling upload in files_drop did not work correctly if it is canceled after waiting for a few sec. But, this does work if it is canceled immediately (which didn't work on `v10.1.1`).  The uploading message does disappear after the file is uploaded.

See test video here: https://cloud.owncloud.com/index.php/s/1psr6GzChn3u83L

**Comment by paurakhsharma** [comment]
Regarding #34427
I the exception is shown in the log but I am not sure if it is the expected error message.(according to this PR)

These are the steps I followed.
1) Change `appinfo.xml` to an invalid XML
2) Run the command `./occ app:check-code <app_name>`
3) I see an `InvalidArgumentException\` thrown in `owncloud.log` with message `Could not convert XML to array` (which is expected)

But, I cannot produce an error with the message as in https://github.com/owncloud/core/pull/30457/files#diff-1e7169b61c01f1c8a31c364b3a217135R128
How do I produce such a message?

**Comment by skshetry** [comment]
Fix chunking infinite loop in some environment-related issues was tested using the `How this has been tested` section in #34489

**Comment by individual-it** [comment]
after #34089 headers can be set twice in 4xx responses if already defined in apache config - raised #35093

**Comment by sharidas** [comment]
I have verified #34506 with 10.2.0 RC1. 
Verified it by by creating a local share within oC users and enabled recovery key for the recipient of share user. Used debugger to verify the recovery keys are not added for recipient share user.

**Comment by patrickjahns** [comment]
I see the following open points:
- Store quota overrides in preferences table - #34467
- Prevent concurrent updates in group shares to avoid duplicate entries - #34769

I believe #34769 was agreed that this can not be manually confirmed and is fine - what about #34467 ?

**Comment by skshetry** [comment]
Repair subshares earlier to avoid errors - #34462 - was also skipped as it cannot be reproduced (as per the discussion with pvince).

**Comment by PVince81** [comment]
For "Prevent concurrent updates in group shares to avoid duplicate entries - #34769" we should check that we have acceptance tests that cover the general cases with subshares (but not this one specific case about duplicates)

**Comment by PVince81** [comment]
for "Store quota overrides in preferences table - #34467" it is likely that LDAP will be required.
manual test would be fine for RC but consider automating it as part of https://github.com/owncloud/user_ldap/issues/368#issuecomment-487053363

**Comment by individual-it** [comment]
updated the list above with changes in RC2 listed in e801e4e

**Comment by individual-it** [comment]
I think we are done here for now
list for tests to be automated here https://github.com/owncloud/core/issues/35207
