### ISSUE TITLE
10.2.1 Changelog test results

### ISSUE THREAD

**Issue by davitol** [owncloud/core#35652]
### Fixed

- [x] Handling of "password fields" on public link shares - [#35541](https://github.com/owncloud/core/issues/35541) [#35563](https://github.com/owncloud/core/issues/35563) @jesmer
- [x] Error when user was removed from a group - [#35289](https://github.com/owncloud/core/issues/35289) [#35570](https://github.com/owncloud/core/issues/35570) **Test steps: https://github.com/owncloud/core/issues/35289#issue-446556457** @davitol 
- [x] Incorrect avatar storage location - [#35311](https://github.com/owncloud/core/issues/35311) [#35531](https://github.com/owncloud/core/issues/35531) **Tests steps: https://github.com/owncloud/enterprise/issues/3379#issuecomment-501670081** @davitol 
- [x] Incorrect rendering of password changed notification email - [#35255](https://github.com/owncloud/core/issues/35255) [#35491](https://github.com/owncloud/core/issues/35491) **Test steps: https://github.com/owncloud/core/issues/35255#issue-445327359** @davitol 
- [x] Performance issue with sharing on masterkey encryption - [#35492](https://github.com/owncloud/core/issues/35492) **Tests steps: https://github.com/owncloud/core/pull/35406#issuecomment-498217532** @davitol 
- [x] Permission change handling for share receivers on internal shares - [#35510](https://github.com/owncloud/core/issues/35510) [#35633](https://github.com/owncloud/core/pull/35633) **Tests steps:https://github.com/owncloud/enterprise/issues/3364#issue-450731850** @davitol
- [x] Permission handling of public link shares based upon internal shares [#35600](https://github.com/owncloud/core/pull/35600) **Tests steps: check public link is not allowed to have more permissions than the original share. https://github.com/owncloud/core/pull/35600#issuecomment-506257711** @davitol
- [x] Automatically set expiration date on newly created shares [#35550](https://github.com/owncloud/core/issues/35550) [#35593](https://github.com/owncloud/core/pull/35593) **Test steps: https://github.com/owncloud/core/issues/35550#issue-456776376 and Desktop Mac v2.5.4** @davitol 
- [x] Incorrectly sent password reset tokens [#32889](https://github.com/owncloud/core/issues/32889) [#35607](https://github.com/owncloud/core/pull/35607) **Test steps https://github.com/owncloud/core/issues/32889#issue-364357851** @davitol

### Changed

- [x] Added `-y` option to `encryption:encrypt-all` occ command [encryption#33](https://github.com/owncloud/encryption/issues/33) [#35606](https://github.com/owncloud/core/pull/35606) **Tests steps: https://github.com/owncloud/encryption/issues/33#issue-325334184 @davitol
- [ ] Updated application revocation list  - [#35506](https://github.com/owncloud/core/issues/35506) **Not Tested**

**Comment by jesmrec** [comment]
> Handling of "password fields" on public link shares - #35541 #35563 @jesmrec



Request with body

`path:        /Documents/
shareType:   3
shareWith:   
name:        Documents link (2)
expireDate:  2019-07-09
password:    a
permissions: 1`

returns inside response:

 `...
<share_with>***redacted***</share_with>
<share_with_displayname>***redacted***</share_with_displayname>
...`

Request with body

`Request with body 

`path:        /Documents/
shareType:   3
shareWith:   
name:        Documents link
expireDate:  2019-07-09
permissions: 1`

does not return `share_with` neither `share_with_displayname` 

Tested with

![Screenshot 2019-06-26 at 10 05 47](https://user-images.githubusercontent.com/14894746/60162566-13b8b100-97fa-11e9-8187-74da94577461.png)
 
iOS12 / Android 8

**Comment by davitol** [comment]
## Changelog RC2

- [ ] https://github.com/owncloud/core/pull/35633 @davitol **Test steps: https://github.com/owncloud/core/issues/35528#issue-456101496**

**Comment by davitol** [comment]
## Changelog RC3

- [ ] Issue with loading javascript files from additional app folders [#35640](https://github.com/owncloud/core/issues/35640) [#35709](https://github.com/owncloud/core/pull/35709)
