### ISSUE TITLE
10.3.2. - Changelog test Results

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36477]
Changelog for ownCloud Core 10.3.2 (UNRELEASED)
=======================================

- [x] Fix [#36222](https://github.com/owncloud/core/pull/36222): Fix share transfer in files:transfer-ownership command @davitol **Test steps: https://github.com/owncloud/core/pull/36222#issue-321819259**
- [x] Fix [#36225](https://github.com/owncloud/core/pull/36225): Respect accounts.enable_medial_search setting for remote search @davitol **Test steps: https://github.com/owncloud/core/pull/36225#issue-322742639**
- [x] Fix [#36242](https://github.com/owncloud/core/pull/36242): Fix SMB access denied error while listing the contents of the folder @davitol **Works in development environment**
- [x] Fix [#36281](https://github.com/owncloud/core/pull/36281): Avoid unnecessary "Avatar not found" logs @davitol **Test steps: https://github.com/owncloud/core/pull/36281#issue-328403169 `{"reqId":"f81d5297-daed-4e06-a9ff-a681c8550735","level":2,"time":"2019-11-27T09:52:46+00:00","remoteAddr":"172.25.0.1","user":"abcdefp","app":"no app in context","method":"GET","url":"\/remote.php\/dav\/avatars\/abcdefp\/128.png","message":""}`no longer shown**
- [x] Fix [#36288](https://github.com/owncloud/core/pull/36288): Guests' home storage will be read-only so check for isReadable instead @davitol **Test steps: https://github.com/owncloud/core/pull/36288#issue-329261062**
- [x] Fix [#36319](https://github.com/owncloud/core/pull/36319): LargeFileHelper::getFileSizeViaCurl is broken with newer libcurl @davitol **CI fixed and works**
- [x] Fix [#36305](https://github.com/owncloud/core/issues/36305): Do not try to set null parent Id in the file cache @davitol **https://github.com/owncloud/enterprise/issues/3580#issuecomment-547992617**
- [x] Fix [#36329](https://github.com/owncloud/core/pull/36329): Follow single-bucket initialization for multi-bucket setup @davitol **Test steps: https://github.com/owncloud/core/pull/36329#issue-332036521**
- [x] Fix [#36241](https://github.com/owncloud/core/issues/36241): Disallow sharing share_folder or it's parents @davitol **Test steps: https://github.com/owncloud/core/issues/36241#issue-502569177**
- [x] Fix [#35488](https://github.com/owncloud/core/issues/35488): Fix sharing behavior to distinguish user and group having the same name @davitol **Test steps: https://github.com/owncloud/core/issues/35488#issue-454701527**
- [x] Fix [#30853](https://github.com/owncloud/core/issues/30853): Do not create error log about user home in user creation @davitol **Test steps: https://github.com/owncloud/core/issues/30853#issue-307154467**
- [x] Fix [#36384](https://github.com/owncloud/core/pull/36384): Allow sharing with guests when group restriction is active @davitol **Test steps: https://github.com/owncloud/core/pull/36384#issue-337365575**
- [x] Fix [#36386](https://github.com/owncloud/core/issues/36386): Allow re-sharer to send an e-mail for public link @davitol **Test steps: share a shared folder via public link and check the mail is fired**
- [ ] Fix [#36401](https://github.com/owncloud/core/pull/36401): Handling null properly in dav files endpoint **Not tested, QA environment not available**
- [x] Fix [#36420](https://github.com/owncloud/core/pull/36420): Fix a php error for occ command files_external:list --output @davitol **Test steps: Running the command no php error is shown**
- [x] Fix [#36431](https://github.com/owncloud/core/pull/36431): Fix user search problem happening after user deletion @davitol **Test steps: https://github.com/owncloud/core/pull/36431#issue-341846486**
- [ ] Fix [#36465](https://github.com/owncloud/core/pull/36465): The authentication header can also hold an empty string **To be tested with Kerberos app**
- [x] Fix [#36298](https://github.com/owncloud/core/issues/36298): Occ system:cron only shows progess bar if option is set @davitol **Test steps: occ system:cron -> no output; occ system:cron -p -> see progress bar**
- [x] Chg [#36244](https://github.com/owncloud/core/pull/36244): Update Symfony components to 3.4.32 ⚙️ 
- [x] Chg [#36253](https://github.com/owncloud/core/pull/36253): Update phpspec/prophecy (1.8.1 => 1.9.0) ⚙️
- [x] Chg [#36274](https://github.com/owncloud/core/pull/36274): Update zendframework/zend-validator (2.12.0 => 2.12.1) ⚙️
- [x] Chg [#36285](https://github.com/owncloud/core/pull/36285): Update league/flysystem (1.0.55 => 1.0.57) ⚙️
- [x] Chg [#36299](https://github.com/owncloud/core/issues/36299): Update sabre/dav from version 4.0.1 to 4.0.2 ⚙️
- [x] Chg [#36310](https://github.com/owncloud/core/pull/36310): Update pear/archive_tar (1.4.7 => 1.4.8) ⚙️
- [x] Chg [#3508](https://github.com/blueimp/jQuery-File-Upload/pull/3508): Update jQuery-File-Upload from 9.18 to 9.34 ⚙️
- [x] Chg [#36344](https://github.com/owncloud/core/pull/36344): Update twbs/bootstrap (3.3.7 => 3.4.1) ⚙️
- [x] Chg [#36345](https://github.com/owncloud/core/pull/36345): Update nikic/php-parser (4.2.4 => 4.2.5) ⚙️
- [x] Chg [#36348](https://github.com/owncloud/core/pull/36348): Update psr/log (1.1.0 => 1.1.1) ⚙️
- [x] Chg [#36358](https://github.com/owncloud/core/pull/36358): Update Symfony components to 3.4.33 and other dependencies ⚙️
- [x] Chg [#36405](https://github.com/owncloud/core/pull/36405): Update Symfony components to 3.4.34 ⚙️
- [x] Chg [#36410](https://github.com/owncloud/core/pull/36410): Update nikic/php-parser (4.2.5 => 4.3.0) ⚙️
- [x] Chg [#36417](https://github.com/owncloud/core/pull/36417): Update swiftmailer/swiftmailer (v6.2.1 => v6.2.3) ⚙️
- [x] Chg [#36426](https://github.com/owncloud/core/pull/36426): Update Symfony components to 3.4.35
- [x] Chg [#36448](https://github.com/owncloud/core/pull/36448): Update pear/pear-core-minimal (v1.10.9 => v1.10.10) ⚙️
- [x] Chg [#36454](https://github.com/owncloud/core/pull/36454): Update pear/console_getopt (v1.4.2 => v1.4.3) ⚙️
- [x] Chg [#36465](https://github.com/owncloud/core/pull/36465): Update webmozart/assert (1.5.0 => 1.6.0) ⚙️
- [x] Enh [#36420](https://github.com/owncloud/core/pull/36420): New option in occ command files_external:list --mount-options @davitol **Test steps: https://github.com/owncloud/core/pull/36420#issue-340127313**

**Comment by phil-davis** [comment]
I checked all the boxes for PHP dependencies. Those are tested by having green CI. We have green CI for core and for all the apps.

**Comment by jesmrec** [comment]
## Mobile 

### Environment:

**Server version**: 10.3.2RC1<br>
**OAuth2 version**: 0.4.2<br>
**Device & Android version**: Xiaomi MiA2, v9.0 <br>
**Android app version**: 2.13.1 (https://github.com/owncloud/android/tree/oc-android-2.13.1)<br>
**Device & iOS version**: iPhoneX, v13.2<br>
**iOS app version**: 1.1.2 (https://github.com/owncloud/ios-app/tree/version_1.1.2)<br>
**iOS-legacy app version**: 3.8.2 (https://github.com/owncloud/ios-legacy/tree/version_3.8.2)<br>

_______________

### Server fixes 

List of issues with posible mobile client concerns:

#### https://github.com/owncloud/core/issues/36241

To test this, `'share_folder' => '/ReceivedShares'` was added to `config.php`. A share was created to enforce the `/ReceivedShares`folder creation.

then we check the PROPFIND response to find out, which permissions are allowed to the folder:

`<oc:permissions>NVCK</oc:permissions>`

This is: rename, move, create file, create folder. Sharing (R) is not allowed (core fix correct). 

Client tests:

**- iOS**: item is not allowed to share. Sharing option hidden. Correct.
**- Android:** item is not allowed to share, under error handling. Behaviour to improve (sharing option disabled for such folder). [Issue created in Android repository](https://github.com/owncloud/android/issues/2735)

#### https://github.com/owncloud/core/pull/36225

Checking (as regression) the autocomplete feature (userID, email, None)

**- iOS:** OK
**- Android**: OK

#### https://github.com/owncloud/core/pull/36242

It should not concern the clients. We lack of an environment to test this. Mobile clients display the list that the `PROPFIND` returns, so it is not dependent from the attached storage backend to oC core.

#### https://github.com/owncloud/core/issues/35488

Group and user with the same name were created. 

**- iOS:** The app is preventing to share with two items with same name (if you already shared with user called "Peter", groups with name "Peter" are not displayed as matching option). Bug in the iOS app: [new issue created](https://github.com/owncloud/ios-app/issues/565)
**- Android:** Users can share with both group and user. OK.

#### https://github.com/owncloud/core/pull/36384

Fixed problem does not affect the mobile clients, since this is a problem in the creation of the guest user. Mobile clients do not have such feature.

_______________

### Smoke tests

#### Android

Test Case | Steps | Expected Result | Result | Related Comment
| :------ | :---- | :-------------- | :----- | :---------
| Login basic | Login in a server with basic auth | It is possible to access  | Passed |
| Login OAuth2 | Login in a server with OAuth2  | It is possible to access  | Passed |
| New folder | Select to create a new folder |The folder is created with the correct name|  Passed |
| Rename | Rename an existing folder|  Folder is renamed with the new name | Passed
| Move | 1. Long press on a folder<br>2. Select Move, and a new location | Folder is moved to the specified location | Passed
| Copy | 1. Long press on a folder<br>2. Select Copy, and a location to copy to | The folder and all its content is copied in the location, and remains too in the original| Passed
| Delete | 1. Long press on a folder<br>2. Select Delete | Item deleted| Passed
| Sync | 1. Create a folder <br> 2. In web app, upload some files in the folder <br> 3. Long press to sync the folder  | The folder is sync with the content on server| Passed
| Upload  | Select several files from Document provider to upload to oC | Files are uploaded  | Passed 
| Download | Tap to download a file | The file is downloaded and marked with green arrow| Passed
| Av Offline | Long press to set as Av Offline a file | The file is downloaded and set as Av Offline with the purple tick | Passed
| Av Offline folder | Long press to unset an Av Offline a folder that contains subfolders<br>Add new content to the folder | The folder and all its content is downloaded and set as Av Offline with the purple tick<br>New content is available offline | Passed
| Share with user  | Share a file and a folder with another user | Both are correctly shared  | Passed
| Link  | Create a link over a file and a folder | Links are correctly created| Passed


#### iOS

Test Case | Steps | Expected Result | Result | Related Comment
| :------ | :---- | :-------------- | :----- | :---------
| Login basic | Login in a server with basic auth | It is possible to access  | Passed |
| Login OAuth2 | Login in a server with OAuth2  | It is possible to access  | Passed |
| New folder | Select to create a new folder |The folder is created with the correct name|  Passed |
| Rename | Rename an existing folder|  Folder is renamed with the new name | Passed
| Move | 1. Open the card of a folder<br>2. Select Move, and a new location | Folder is moved to the specified location | Passed
| Copy | 1. Open the card of a folder<br>2. Select Copy, and a location to copy to | The folder and all its content is copied in the location, and remains too in the original| Passed
| Duplicate | 1. Open the card of a folder<br>2. Select Copy, and a location to copy to | The folder and all its content is copied in the location, and remains too in the original| Passed
| Delete | 1. Open the card of a folder<br>2. Select Delete | Item deleted| Passed 
| Upload  | Select several files from Document provider to upload to oC | Files are uploaded  | Passed
| Download | Tap to download a file | The file is downloaded and marked with green arrow| Passed 
| Av Offline | Open the card of a file to set as Av Offline | The file is downloaded and set as Av Offline with the purple tick | Passed
| Av Offline folder | Open the card of a folder to unset as Av Offline | The folder and all its content is downloaded and set as Av Offline with the purple tick | Passed
| Share with user  | Share a file and a folder with another user | Both are correctly shared  | Passed
| Link  | Create a link over a file and a folder | Links are correctly created| Passed


#### iOS legacy

Test Case | Steps | Expected Result | Result | Related Comment
| :------ | :---- | :-------------- | :----- | :---------
| Login basic | Login in a server with basic auth | It is possible to access  | Passed |
| Login OAuth2 | Login in a server with OAuth2  | It is possible to access  | Passed |
| New folder | Select to create a new folder |The folder is created with the correct name|  Passed |
| Rename | Rename an existing folder|  Folder is renamed with the new name | Passed
| Move | 1. Open the card of a folder<br>2. Select Move, and a new location | Folder is moved to the specified location | Passed
| Delete | 1. Open the card of a folder<br>2. Select Delete | Item deleted| Passed 
| Upload  | Select several files from Document provider to upload to oC | Files are uploaded  | Passed
| Download | Tap to download a file | The file is downloaded and marked with green arrow| Passed 
| Av Offline | Open the card of a file to set as Av Offline | The file is downloaded and set as Av Offline with the purple tick | Passed
| Av Offline folder | Open the card of a folder to unset as Av Offline | The folder and all its content is downloaded and set as Av Offline with the purple tick | Passed
| Share with user  | Share a file and a folder with another user | Both are correctly shared  | Passed |
| Link  | Create a link over a file and a folder | Links are correctly created| Passed

_______________

### Final comments

After testing the 10.3.2RC1 with the mobile clients, there is no inconvenience to move forward this release from my side. The detected issues during the testing process are in the client side and the correspondent tickets were already created.

**Comment by micbar** [comment]
@jesmrec Thank you!

**Comment by HanaGemela** [comment]
Fix #36225:  Client tested for regressions - Passed
Fix #36242:  Out of scope - no test environment
Fix #35488:  Passed
Fix #36384:  Out of scope - client cannot create new guests

**Comment by HanaGemela** [comment]
Server smoke test on a 2.6.0 client Windows 10 passed as well

**Comment by davitol** [comment]
# Smoke test with 10.3.2 RC1 version

## Previous requirements

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

Scenarios to consider:
- [x] OAuth2 and sync + mobile clients ( can be deployed remotely ) @davitol 
- [x] LDAP @davitol 
- [ ] Shibboleth 
- [x] Windows Network Drive @davitol
- [x] Guests @davitol  
- [x] Impersonate @davitol 
- [x] Login with App Token Login @davitol
- [x] TOTP @davitol
- [x] user_external IMAP @davitol 

## Testing setup


TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly |  ✔️    |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | ✔️   |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | ✔️   | 
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | ✔️ |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | ✔️   |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | ✔️ |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | ✔️ |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | ✔️  | To be investigated. WebDAV storage seems to not work https://github.com/owncloud/core/issues/35660
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. |✔️  |
5 | Using webdav upload a 100MiB file.| No errors in this process |✔️ |
