### ISSUE TITLE
Support PHP 7.4

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36509]
PHP 7.4 was released last week. It is now available in `owncloud-ci/php:7.4`

Enable support for PHP 7.4 in core.

- [x] run CI with 7.4 (see WIP PR #37280 )
- [x] investigate and fix the fails that are reported
- [x] think about other QA needed to be confident that core is ready for PHP 7.4 - regular release smoke tests should be enough
- [x] sort out PHP 7.4 support for apps https://github.com/owncloud/QA/issues/645 https://github.com/owncloud/QA/issues/647

**Comment by phil-davis** [comment]
PR #36500 gets various errors/warnings in `phpunit` and in some other test suites. So this is not a completely trivial job. Needs to be scheduled.

**Comment by phil-davis** [comment]
@micbar I am seeing developers mention PHP 7.4 more often - I think some people's Mac's etc have auto-updated to PHP 7.4... and they are trying to work with codebase...

What is the priority for getting this to happen (e.g. immediately that we get 10.4 release done?)

**Comment by jvillafanez** [comment]
* [ ] Need to update google API library for the `implode` order deprecation (https://github.com/owncloud/core/tree/master/apps/files_external/3rdparty/google-api-php-client)

**Comment by Helios07** [comment]
This month' release of Fedora 32 will bring php7.4. Do you see the php7.4 support in 10.5 so that the upgrade will not leave a Fedora based owncloud server unusable?

**Comment by phil-davis** [comment]
- [ ] might need Guzzle6 (some code in #37011 - see my notes there)

**Comment by phil-davis** [comment]
For reference, these are PRs this week that adjusted unit tests and related to get PHP unit tests passing for PHP 7.4:
#37279 
#37281 
#37288 
#37290 
#37292 
#37293 
#37297 
#37298 
#37300

**Comment by micbar** [comment]
@phil-davis Can we close this?

**Comment by phil-davis** [comment]
@jvillafanez you made a couple of checklust items above. Are they still relevant?
If so, should we raise individual issues?

**Comment by jvillafanez** [comment]
There is a PR with the gdrive lib update that should be reviewed and merged.
The other check is just a small detail. We can ignore it for now and make the change on demand.

**Comment by phil-davis** [comment]
PR  #37265 "Gdrive lib update"

**Comment by phil-davis** [comment]
PR #37265 has been merged.
