### ISSUE TITLE
Add CLI acceptance tests for files_external occ commands

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36704]
We have some UI tests for adding local storage in the admin storage settings. But we have very little tests for the files_external occ commands that create/modify/delete storages.

Add test coverage for:

- [x] files_external:applicable     #37012      #36707   
- [x] files_external:backends            #37035   
- [x] files_external:config            #37015     
- [x] files_external:create         #36707        #36689
- [x] files_external:delete         #36756        
- [x] files_external:export       #36794          
- [x] files_external:import #37513 
- [x] files_external:list             #36754             
- [x] files_external:option            #37018     
- [x] files_external:verify       #36806

**Comment by phil-davis** [comment]
See #36689 for the first `files_external:create` test scenario.

**Comment by kiranparajuli589** [comment]
Adding tests for files_external:import is currently blocked due to https://github.com/owncloud/core/issues/37054

**Comment by phil-davis** [comment]
`files_external:export` => `files_external:import` was fixed and test added  in PR #37513
