### ISSUE TITLE
Tracking test results for ownCloud 10.4.1

### ISSUE THREAD

**Issue by davitol** [owncloud/core#37196]
Changelog for 10.4.1
-------

- [x] Bugfix - Show re-share public links to share-owner: [#36865](https://github.com/owncloud/core/pull/36865) @davitol **Test steps: 1) create a reshare public link . 2) it should be visible for original share owner**
- [x] Bugfix - It's not possible to download externally encrypted files: [#36921](https://github.com/owncloud/core/pull/36921) @davitol **1) Setup encryption on a separate instance 2) upload any encrypted file to another ownCloud instance where the encryption is not active 3) Try to download this file and check it is downloaded**
- [x] Bugfix - User:resetpassword with --send-email --password-from-env: [#36925](https://github.com/owncloud/core/issues/36925) @davitol **1) User phil has no email address setup 2) export OC_PASS="pppp" 3) php occ user:resetpassword phil --send-email --password-from-env**
- [x] Bugfix - Avoid unneeded DB connections after a long download: [#36978](https://github.com/owncloud/core/pull/36978) @davitol 
- [x] Bugfix - Remove full-stop from end of reset password message: [#36984](https://github.com/owncloud/core/pull/36984) @davitol **Test steps: run occ user:resetpassword username and check full-stop do not appear**
- [x] Bugfix - Show pending remote shares at the Shared with you tab: [#37022](https://github.com/owncloud/core/pull/37022) @davitol **Test steps A create several federated shares. As a recipient browse to the shared with you tab and accept/decline them**
- [x] Bugfix - Initialize the user before the transfer command: [#37038](https://github.com/owncloud/core/pull/37038) @davitol **Test steps: 1) Create 2 users, user1 and user2 (local users 2) Upload some files to user1 3) Without having logged in once with user2, execute occ files:transfer-ownership user1 user2 4) Files are transferred correctly to the user2**
- [x] Bugfix - Google drive files without extension 404: [#37044](https://github.com/owncloud/core/issues/37044) **Test steps: dangling dot disappears and it is possible to download the file.**
- ❓  Bugfix - Fix public link upload remaining time estimation: [#37053](https://github.com/owncloud/core/pull/37053) @davitol **Test steps: 1) Upload a 5 GB file via a public link 2)  Look at the estimated upload time.**
- [x] Bugfix - Fix OCS Share API response for requests contain "include_tags" parameter: [#37084](https://github.com/owncloud/core/issues/37084) @davitol **Test steps 1) Create a folder "test" 2) Create three link shares with different names for that folder 3) Mark folder as favorite 4) Go to "Shared with link" 5) Observe the network console for "/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json&include_tags=true" check now we have id 1, 2 and 3 instead of only one id**
- [x] Bugfix - Add share type to the verifyExpirationDate hook: [#287](https://github.com/owncloud/password_policy/issues/287) @davitol
- [x] Bugfix - Fix CLI zero exit code on startup errors: [#37098](https://github.com/owncloud/core/issues/37098)@davitol **Test steps: 1) In config.php put some invalid dir in apps_paths 2) Do some occ command and check Non-zero exit status happens**
- [x] Bugfix - Respect sharing.federation.allowHttpFallback config option: [#37153](https://github.com/owncloud/core/pull/37153) @davitol 
- [x] Change - Write crash log in case of parse error in config.php: [#36570](https://github.com/owncloud/core/issues/36570) @jasson99 
- [x] Change - Fix ini_set error spamming the log: [#36749](https://github.com/owncloud/core/pull/36749)  @jasson99 
- [x] Change - Update egulias/email-validator (2.1.15 => 2.1.17): [#36955](https://github.com/owncloud/core/pull/36955) - CI and smoke test @phil-davis 
- [x] Change - Update webmozart/assert (1.6.0 => 1.7.0): [#36955](https://github.com/owncloud/core/pull/36955) - CI and smoke test @phil-davis 
- [x] Change - Update symfony/polyfill (1.13.1 => 1.14.0): [#36955](https://github.com/owncloud/core/pull/36955) - CI and smoke test @phil-davis 
- [x] Change - Don't write potential sensitive data to the log file: [#36961](https://github.com/owncloud/core/pull/36961) @HariBhandari07 
- [x] Change - Update Graffino/Browser-Update from 2.0.2 to 2.0.5: [#36976](https://github.com/owncloud/core/issues/36976) - CI and smoke test @phil-davis 
- [x] Change - Update phpseclib/phpseclib (2.0.23 => 2.0.24): [#37010](https://github.com/owncloud/core/pull/37010) - CI and smoke test @phil-davis 
- [x] Change - Update phpseclib/phpseclib (2.0.24 => 2.0.25): [#37014](https://github.com/owncloud/core/pull/37014) - CI and smoke test @phil-davis 
- [x] Change - Allow dot in database name: [#20381](https://github.com/owncloud/core/issues/20381) @davitol **Test steps: use dots in the database name when installing and check it works**
- [x] Change - Respect default_language when sending email notifications: [#37039](https://github.com/owncloud/core/issues/37039) @jasson99 
- [x] Change - Lookup email subject in correct translation context: [#37040](https://github.com/owncloud/core/issues/37040) @HariBhandari07 
- [x] Change - Update Symfony components to 4.4.5: [#37052](https://github.com/owncloud/core/pull/37052) - CI and smoke test @phil-davis 
- [x] Change - Return correct custom dav properties for folder contents: [#37058](https://github.com/owncloud/core/pull/37058)  @jasson99 
- [ ] Change - Hardening Cache-Control headers for some responses: [#37082](https://github.com/owncloud/core/pull/37082)
- [x] Change - Add menu entry to phoenix if phoenix is configured: [#37083] @jasson99 (https://github.com/owncloud/core/pull/37083)
- [x] Change - Update league/flysystem (1.0.64 => 1.0.65): [#37096](https://github.com/owncloud/core/pull/37096) - CI and smoke test @phil-davis 
- [x] Change - Include reshares in the webdav response when asking for share types: [#37107](https://github.com/owncloud/core/pull/37107) @HariBhandari07 
- [x] Change - Fix UX in files app: [#37116](https://github.com/owncloud/core/pull/37116) @HariBhandari07 
- [x] Change - Update laminas/laminas-validator (2.13.1 => 2.13.2): [#37131](https://github.com/owncloud/core/pull/37131) - CI and smoke test @phil-davis 
- [x] Change - Update league/flysystem (1.0.65 => 1.0.66): [#37136](https://github.com/owncloud/core/pull/37136) - CI and smoke test @phil-davis 
- [x] Change - Update minimist (1.2.2 => 1.2.3): [#37138](https://github.com/owncloud/core/pull/37138) - CI and smoke test @phil-davis 
- [x] Change - Update sabre/dav from version 4.0.3 to 4.1.0: [#37151](https://github.com/owncloud/core/pull/37151) - CI and smoke test @phil-davis 
- [x] Change - Update phpseclib/phpseclib (2.0.25 => 2.0.26): [#37155](https://github.com/owncloud/core/pull/37155) - CI and smoke test @phil-davis 
- [x] Change - Update psr/log (1.1.2 => 1.1.3): [#37161](https://github.com/owncloud/core/pull/37161) - CI and smoke test @phil-davis 
- [x] Change - Query on oc_properties is now always chunked: [#37172](https://github.com/owncloud/core/pull/37172) **live deployed at customer and working**
- [x] Change - Proper error handling on preview endpoint: [#37172](https://github.com/owncloud/core/pull/37172) **live deployed at customer and working**
- [x] Change - Update symfony/polyfill (1.14.1 => 1.15.0): [#37174](https://github.com/owncloud/core/pull/37174) - CI and smoke test @phil-davis 
- [x] Change - Update laminas/laminas-zendframework-bridge (1.0.1 => 1.0.2): [#37174](https://github.com/owncloud/core/pull/37174) - CI and smoke test @phil-davis 
- [x] Change - Update Symfony components to 4.4.6: [#37176](https://github.com/owncloud/core/pull/37176) - CI and smoke test @phil-davis 
- [x] Enhancement - Add new occ command to check the cache for primary storages: [#37067](https://github.com/owncloud/core/pull/37067) @davitol **Test steps: 1) Upload some files into the primary storage through ownCloud 2) Remove one of those files directly from the storage (bypassing ownCloud) 3) Run the command**

Details
-------

* Bugfix - Show re-share public links to share-owner: [#36865](https://github.com/owncloud/core/pull/36865)

   Public links created by share-recipient were not visible to share-owner. This problem has
   been resolved.

   https://github.com/owncloud/core/pull/36865

* Bugfix - It's not possible to download externally encrypted files: [#36921](https://github.com/owncloud/core/pull/36921)

   Downloading was failing with the message "Encryption not ready: Module with id:
   OC_DEFAULT_MODULE does not exist." if the file was encrypted with another ownCloud instance.

   https://github.com/owncloud/core/pull/36921

* Bugfix - User:resetpassword with --send-email --password-from-env: [#36925](https://github.com/owncloud/core/issues/36925)

   When trying to do command: occ user:resetpassword Anne --send-email --password-from-env

   If Anne does not have an email address setup then an error was logged in the ownCloud log.

   This has been corrected. Now the administrator is shown the correct error "Email address is not
   set for the user Anne"

   https://github.com/owncloud/core/issues/36925
   https://github.com/owncloud/core/pull/36926

* Bugfix - Avoid unneeded DB connections after a long download: [#36978](https://github.com/owncloud/core/pull/36978)

   After a long download, we needed to return the filesize, which needed a connection to the DB. The
   DB could have ended the connection due to an inactivity timeout. Now, the filesize is fetched
   before starting the download, so this timeout shouldn't happen any longer. We still need to
   update the checksum after the download is finished. In this case, we just log an error message
   and keep going.

   https://github.com/owncloud/core/pull/36978

* Bugfix - Remove full-stop from end of reset password message: [#36984](https://github.com/owncloud/core/pull/36984)

   When doing occ user:resetpassword username --password-from-env --send-email the message
   "Successfully reset password for username" had a full-stop at the end. Without --send-email
   there was no full-stop. The full-stop has been removed to make the messages consistent.

   https://github.com/owncloud/core/pull/36984

* Bugfix - Show pending remote shares at the Shared with you tab: [#37022](https://github.com/owncloud/core/pull/37022)

   Fixed missing pending remote shares in the file list at the Shared with you tab.

   https://github.com/owncloud/core/pull/37022

* Bugfix - Initialize the user before the transfer command: [#37038](https://github.com/owncloud/core/pull/37038)

   Trying to transfer the ownership of files to a user who hadn't logged in was causing problems
   because the FS of such user wasn't initialized and it wasn't possible to move the files there.
   The command appeared to work, but the files weren't moved.

   Now such user has the FS initialized so the transfer can be completed normally.

   https://github.com/owncloud/core/pull/37038

* Bugfix - Google drive files without extension 404: [#37044](https://github.com/owncloud/core/issues/37044)

   Google Drive files without a file extension (".git/HEAD" for example) would result in a 404
   response from the Web UI or desktop client. The problem has been fixed.

   https://github.com/owncloud/core/issues/37044
   https://github.com/owncloud/core/pull/37045

* Bugfix - Fix public link upload remaining time estimation: [#37053](https://github.com/owncloud/core/pull/37053)

   Public link upload wrong remaining time estimation problem has been resolved. Also, the
   remaining time calculation logic has been changed for smoother performance.

   https://github.com/owncloud/core/issues/25053
   https://github.com/owncloud/core/pull/37053

* Bugfix - Fix OCS Share API response for requests contain "include_tags" parameter: [#37084](https://github.com/owncloud/core/issues/37084)

   Sending "include_tags" request parameter for OCS Share API was led to duplicated share
   entries in API response. This bug has been fixed by using share_id instead of file_id when
   populating tags. Also, the tag generation helper method simplified by customizing it for only
   shares.

   https://github.com/owncloud/core/issues/37084
   https://github.com/owncloud/core/pull/37088

* Bugfix - Add share type to the verifyExpirationDate hook: [#287](https://github.com/owncloud/password_policy/issues/287)

   The verifyExpirationDate hook notifies the password_policy app about proposed expiration
   dates of shares. The share type was not being passed in the hook. This meant that the
   password_policy app incorrectly processed user and group share expiration dates. See the
   linked issue for details. The problem has been corrected.

   https://github.com/owncloud/password_policy/issues/287
   https://github.com/owncloud/core/pull/37135

* Bugfix - Fix CLI zero exit code on startup errors: [#37098](https://github.com/owncloud/core/issues/37098)

   Zero exit code was returned on startup with a missing app directory or a non-writable config
   directory. Now exit code is 1.

   https://github.com/owncloud/core/issues/37098
   https://github.com/owncloud/core/pull/37148

* Bugfix - Respect sharing.federation.allowHttpFallback config option: [#37153](https://github.com/owncloud/core/pull/37153)

   Federated share can be created for server without SSL, by setting config option
   sharing.federation.allowHttpFallback=true.

   https://github.com/owncloud/core/pull/37153

* Change - Write crash log in case of parse error in config.php: [#36570](https://github.com/owncloud/core/issues/36570)

   https://github.com/owncloud/core/issues/36570

* Change - Fix ini_set error spamming the log: [#36749](https://github.com/owncloud/core/pull/36749)

   https://github.com/owncloud/core/pull/36749

* Change - Update egulias/email-validator (2.1.15 => 2.1.17): [#36955](https://github.com/owncloud/core/pull/36955)

   https://github.com/owncloud/core/pull/36955

* Change - Update webmozart/assert (1.6.0 => 1.7.0): [#36955](https://github.com/owncloud/core/pull/36955)

   https://github.com/owncloud/core/pull/36955

* Change - Update symfony/polyfill (1.13.1 => 1.14.0): [#36955](https://github.com/owncloud/core/pull/36955)

   The following symfony/polyfill components have been updated to version 1.14.0:

   Symfony/polyfill-ctype symfony/polyfill-iconv symfony/polyfill-intl-idn
   symfony/polyfill-mbstring symfony/polyfill-php56 symfony/polyfill-php72
   symfony/polyfill-php73 symfony/polyfill-util

   https://github.com/owncloud/core/pull/36955

* Change - Don't write potential sensitive data to the log file: [#36961](https://github.com/owncloud/core/pull/36961)

   Sensitive data like passwords are not written to the log when the exception is thrown from
   within a closure.

   https://github.com/owncloud/core/pull/36961

* Change - Update Graffino/Browser-Update from 2.0.2 to 2.0.5: [#36976](https://github.com/owncloud/core/issues/36976)

   https://github.com/owncloud/core/issues/36976
   https://github.com/owncloud/core/pull/36981

* Change - Update phpseclib/phpseclib (2.0.23 => 2.0.24): [#37010](https://github.com/owncloud/core/pull/37010)

   https://github.com/owncloud/core/pull/37010

* Change - Update phpseclib/phpseclib (2.0.24 => 2.0.25): [#37014](https://github.com/owncloud/core/pull/37014)

   https://github.com/owncloud/core/pull/37014

* Change - Allow dot in database name: [#20381](https://github.com/owncloud/core/issues/20381)

   When installing ownCloud the database name is now allowed to contain a dot.

   https://github.com/owncloud/core/issues/20381
   https://github.com/owncloud/core/pull/37020

* Change - Respect default_language when sending email notifications: [#37039](https://github.com/owncloud/core/issues/37039)

   https://github.com/owncloud/core/issues/37039

* Change - Lookup email subject in correct translation context: [#37040](https://github.com/owncloud/core/issues/37040)

   Use 'lib' instead of 'core' to get the translations.

   https://github.com/owncloud/core/issues/37040

* Change - Update Symfony components to 4.4.5: [#37052](https://github.com/owncloud/core/pull/37052)

   The following Symfony components have been updated to version 4.4.5: - console -
   event-dispatcher - process - routing - translation

   https://github.com/owncloud/core/pull/37052
   https://symfony.com/blog/symfony-4-4-5-released

* Change - Return correct custom dav properties for folder contents: [#37058](https://github.com/owncloud/core/pull/37058)

   https://github.com/owncloud/core/issues/36920
   https://github.com/owncloud/core/pull/37058

* Change - Hardening Cache-Control headers for some responses: [#37082](https://github.com/owncloud/core/pull/37082)

   https://github.com/owncloud/core/pull/37082

* Change - Add menu entry to phoenix if phoenix is configured: [#37083](https://github.com/owncloud/core/pull/37083)

   https://github.com/owncloud/core/pull/37083

* Change - Update league/flysystem (1.0.64 => 1.0.65): [#37096](https://github.com/owncloud/core/pull/37096)

   https://github.com/owncloud/core/pull/37096

* Change - Include reshares in the webdav response when asking for share types: [#37107](https://github.com/owncloud/core/pull/37107)

   Previously, only shares initiated by the user were being returned when asked for the shares.
   Now, reshares are also included in the response

   https://github.com/owncloud/core/pull/37107

* Change - Fix UX in files app: [#37116](https://github.com/owncloud/core/pull/37116)

   Some translations are now properly displayed and in an empty readonly folder a message is
   displayed that no files can be uploaded.

   https://github.com/owncloud/core/pull/37116

* Change - Update laminas/laminas-validator (2.13.1 => 2.13.2): [#37131](https://github.com/owncloud/core/pull/37131)

   https://github.com/owncloud/core/pull/37131

* Change - Update league/flysystem (1.0.65 => 1.0.66): [#37136](https://github.com/owncloud/core/pull/37136)

   https://github.com/owncloud/core/pull/37136

* Change - Update minimist (1.2.2 => 1.2.3): [#37138](https://github.com/owncloud/core/pull/37138)

   https://github.com/owncloud/core/pull/37138

* Change - Update sabre/dav from version 4.0.3 to 4.1.0: [#37151](https://github.com/owncloud/core/pull/37151)

   https://github.com/owncloud/core/pull/37151
   https://github.com/sabre-io/dav/releases/tag/4.1.0

* Change - Update phpseclib/phpseclib (2.0.25 => 2.0.26): [#37155](https://github.com/owncloud/core/pull/37155)

   https://github.com/owncloud/core/pull/37155

* Change - Update psr/log (1.1.2 => 1.1.3): [#37161](https://github.com/owncloud/core/pull/37161)

   https://github.com/owncloud/core/pull/37161

* Change - Query on oc_properties is now always chunked: [#37172](https://github.com/owncloud/core/pull/37172)

   https://github.com/owncloud/core/pull/37172

* Change - Proper error handling on preview endpoint: [#37172](https://github.com/owncloud/core/pull/37172)

   Preview requests for folders now return 400/Bad Request and any false parameters of the
   preview generation now return 400/Bad Request as well.

   https://github.com/owncloud/core/issues/37164
   https://github.com/owncloud/core/issues/37165
   https://github.com/owncloud/core/pull/37172

* Change - Update symfony/polyfill (1.14.1 => 1.15.0): [#37174](https://github.com/owncloud/core/pull/37174)

   The following symfony/polyfill components have been updated to version 1.15.0:

   Symfony/polyfill-ctype symfony/polyfill-iconv symfony/polyfill-intl-idn
   symfony/polyfill-mbstring symfony/polyfill-php56 symfony/polyfill-php72
   symfony/polyfill-php73 symfony/polyfill-util

   https://github.com/owncloud/core/pull/37174

* Change - Update laminas/laminas-zendframework-bridge (1.0.1 => 1.0.2): [#37174](https://github.com/owncloud/core/pull/37174)

   https://github.com/owncloud/core/pull/37174

* Change - Update Symfony components to 4.4.6: [#37176](https://github.com/owncloud/core/pull/37176)

   The following Symfony components have been updated to version 4.4.6: - console -
   event-dispatcher - process - routing - translation

   https://github.com/owncloud/core/pull/37176
   https://symfony.com/blog/symfony-4-4-6-released

* Enhancement - Add new occ command to check the cache for primary storages: [#37067](https://github.com/owncloud/core/pull/37067)

   This is a new occ command mainly for objectstores (objectstore and files_primary_s3 apps) as
   primary storages, but it can be used also for local primary storage.

   The use case is when a file is deleted directly from the primary storage without going through
   ownCloud. This is a scenario that shouldn't happen (modifying the primary storage outside of
   ownCloud isn't supported).

   The command will check if the target file can be accessed, and if not you can delete the
   information that ownCloud has (the command provides an option for this).

   The command will only work for the primary storage. It will ignore files that are accessible
   through a share (they need to be accessed directly), or files that are in an external storage.

   https://github.com/owncloud/core/pull/37067

**Comment by davitol** [comment]
### Issues found during QA process

**Comment by phil-davis** [comment]
I updated all changelog items for dependency bumps to be "done" and say "CI and smoke test". There is no special extra testing to do for those. Acceptance tests in CI plus the general manual smoke testing during the release process reduces the risk of regressions due to some bad dependency change.

**Comment by davitol** [comment]
# Smoke test with 10.4.1 RC1 version

## Previous requirements

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

Scenarios to consider:
- [ ] OAuth2 and sync + mobile clients ( can be deployed remotely ) @davitol 
- [ ] LDAP @davitol 
- [ ] Shibboleth 
- [ ] Windows Network Drive @davitol
- [ ] Guests @davitol  
- [ ] Impersonate @davitol 
- [ ] Login with App Token Login @davitol
- [ ] TOTP @davitol
- [ ] user_external IMAP @davitol 
- [ ] German translations

## Testing setup


TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly |  ✔️    |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | ✔️   |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | ✔️   | 
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | ✔️ |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | ✔️   |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | ✔️ |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | ✔️ |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | ✔️  | To be investigated. WebDAV storage seems to not work https://github.com/owncloud/core/issues/35660
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. |✔️  |
5 | Using webdav upload a 100MiB file.| No errors in this process |✔️ |
