### ISSUE TITLE
Tracking test results for ownCloud 10.5.0

### ISSUE THREAD

**Issue by davitol** [owncloud/core#37593]
## Changelog for ownCloud Core [10.5.0]

- [ ] * Security - Add new system config to enforce strict login check with user backend: [#37569](https://github.com/owncloud/core/pull/37569)
- [ ] * Bugfix - Correct files_external:export output so it can be imported: [#37054](https://github.com/owncloud/core/issues/37054)
- [ ] * Bugfix - Add force option to delete user even if the user doesn't exist: [#37103](https://github.com/owncloud/core/pull/37103)
- [ ] * Bugfix - List data for pending federated share via OCS API correctly: [#34636](https://github.com/owncloud/core/issues/34636)
- [ ] * Bugfix - Ensure ETag changes if a change is detected in a folder: [#37218](https://github.com/owncloud/core/pull/37218)
- [ ] * Bugfix - Stop writing data to the output buffer when the connection is not alive: [#37219](https://github.com/owncloud/core/pull/37219)
- [ ] * Bugfix - Remove unused files and config opt for settings help: [#37225](https://github.com/owncloud/core/pull/37225)
- [ ] * Bugfix - Hide add to your OC at the public page when it's not allowed: [#37232](https://github.com/owncloud/core/pull/37232)
- [ ] * Bugfix - Send max number of steps as integer in RepairUnmergedShares: [#37241](https://github.com/owncloud/core/issues/37241)
- [ ] * Bugfix - Remove console logging of un-escaped data: [#37256](https://github.com/owncloud/core/pull/37256)
- [ ] * Bugfix - Earlier detection of connection status: [#37291](https://github.com/owncloud/core/pull/37291)
- [ ] * Bugfix - Rewrite code to fix some notices under PHP 7.4: [#37311](https://github.com/owncloud/core/pull/37311)
- [ ] * Bugfix - Properly store complex Webdav properties: [#37314](https://github.com/owncloud/core/pull/37314)
- [ ] * Bugfix - Cannot share with user name that has only numbers in the UI: [#37324](https://github.com/owncloud/core/issues/37324)
- [ ] * Bugfix - Fix error messages: [#37338](https://github.com/owncloud/core/issues/37338)
- [ ] * Bugfix - Allow unlimited access to PUT body if content length is 0: [#37394](https://github.com/owncloud/core/pull/37394)
- [ ] * Bugfix - Adjust user:sync --uid to use user backend iterator: [#37398](https://github.com/owncloud/core/pull/37398)
- [ ] * Bugfix - Log failed twofactor authentication: [#37401](https://github.com/owncloud/core/pull/37401)
- [ ] * Bugfix - Allow clearing a user email address or display name: [#37424](https://github.com/owncloud/core/issues/37424)
- [ ] * Bugfix - Allow clearing a user email address with the Provisioning API: [#37424](https://github.com/owncloud/core/issues/37424)
- [ ] * Bugfix - Logging of extra fields when logger does not have a writeExtra method: [#37453](https://github.com/owncloud/core/issues/37453)
- [ ] * Bugfix - Align the cancel button on public uploads: [#37504](https://github.com/owncloud/core/pull/37504)
- [ ] * Bugfix - Do not notify remote if both owner and sharer are local users: [#37534](https://github.com/owncloud/core/pull/37534)
- [ ] * Bugfix - Use relative path in shared_with_email activity: [#37555](https://github.com/owncloud/core/pull/37555)
- [ ] * Bugfix - Show error message at Settings Personal CORS: [#37560](https://github.com/owncloud/core/pull/37560)
- [ ] * Change - Disallow various special usernames: [#32547](https://github.com/owncloud/core/issues/32547)
- [x] * Change - Support PHP 7.4: [#36509](https://github.com/owncloud/core/issues/36509) @davitol 
- [x] * Change - Drop PHP 7.1 support across the platform: [#36510](https://github.com/owncloud/core/issues/36510) @davitol 
- [ ] * Change - Adjust wording displayed for empty additional settings panel: [#36775](https://github.com/owncloud/core/pull/36775)
- [ ] * Change - Add index on addressbookid: [#3625](https://github.com/owncloud/enterprise/issues/3625)
- [ ] * Change - Keep the mtime of files and folders inside the tarball: [#37222](https://github.com/owncloud/core/pull/37222)
- [ ] * Change - Replace jeremeamia/superclosure with opis/closure: [#37238](https://github.com/owncloud/core/pull/37238)
- [ ] * Change - Update icewind/streams from 0.7.1 to 0.7.2 in files_external/3rdparty: [#37249](https://github.com/owncloud/core/pull/37249)
- [ ] * Change - Update icewind/streams from 0.7.1 to 0.7.2: [#37253](https://github.com/owncloud/core/pull/37253)
- [ ] * Change - Update league/flysystem (1.0.66 => 1.0.67): [#37271](https://github.com/owncloud/core/pull/37271)
- [ ] * Change - Update doctrine/dbal (2.10.1 => 2.10.2): [#37283](https://github.com/owncloud/core/pull/37283)
- [ ] * Change - Update Symfony components to 4.4.8: [#37319](https://github.com/owncloud/core/pull/37319)
- [ ] * Change - Update symfony/polyfill (1.15.0 => 1.16.0): [#37367](https://github.com/owncloud/core/pull/37367)
- [ ] * Change - Update sabre/xml (2.2.0 => 2.2.1): [#37369](https://github.com/owncloud/core/pull/37369)
- [ ] * Change - Update icewind/smb from 3.1.2 to 3.2.3 in files_external/3rdparty: [#37370](https://github.com/owncloud/core/pull/37370)
- [ ] * Change - Update react/promise (v2.7.1 => v2.8.0): [#37383](https://github.com/owncloud/core/pull/37383)
- [ ] * Change - Update league/flysystem (1.0.67 => 1.0.68): [#37385](https://github.com/owncloud/core/pull/37385)
- [ ] * Change - Update symfony/polyfill (1.16.0 => 1.17.0): [#37385](https://github.com/owncloud/core/pull/37385)
- [ ] * Change - Added federated shares scan cronjob depreciating incoming-shares:poll: [#37391](https://github.com/owncloud/core/pull/37391)
- [ ] * Change - Update laminas/laminas-zendframework-bridge (1.0.3 => 1.0.4): [#37421](https://github.com/owncloud/core/pull/37421)
- [ ] * Change - Update opis/closure (3.5.1 => 3.5.2): [#37431](https://github.com/owncloud/core/pull/37431)
- [ ] * Change - Use strict samesite cookie: [#37442](https://github.com/owncloud/core/pull/37442)
- [ ] * Change - Update opis/closure (3.5.2 => 3.5.3): [#37443](https://github.com/owncloud/core/pull/37443)
- [ ] * Change - Update doctrine/lexer (1.2.0 => 1.2.1): [#37448](https://github.com/owncloud/core/pull/37448)
- [ ] * Change - Update doctrine/cache (1.10.0 => 1.10.1): [#37458](https://github.com/owncloud/core/pull/37458)
- [ ] * Change - Add file action to lock a file: [#37460](https://github.com/owncloud/core/pull/37460)
- [ ] * Change - Update doctrine/instantiator (1.3.0 => 1.3.1): [#37464](https://github.com/owncloud/core/pull/37464)
- [ ] * Change - Update Symfony components to 4.4.9: [#37465](https://github.com/owncloud/core/pull/37465)
- [ ] * Change - Update nikic/php-parser (4.4.0 => 4.5.0): [#37480](https://github.com/owncloud/core/pull/37480)
- [ ] * Change - Share sheet improvements (internal sharing): [#3979](https://github.com/owncloud/enterprise/issues/3979)
- [ ] * Change - Update opis/closure (3.5.3 => 3.5.4): [#37492](https://github.com/owncloud/core/pull/37492)
- [ ] * Change - Update Symfony components to 4.4.10: [#37522](https://github.com/owncloud/core/pull/37522)
- [ ] * Change - Update egulias/email-validator (2.1.17 => 2.1.18): [#37544](https://github.com/owncloud/core/pull/37544)
- [ ] * Change - Update opis/closure (3.5.4 => 3.5.5): [#37547](https://github.com/owncloud/core/pull/37547)
- [ ] * Change - Share sheet improvements (external sharing): [#37558](https://github.com/owncloud/core/pull/37558)
- [ ] * Change - Update symfony/polyfill (1.17.0 => 1.17.1): [#37385](https://github.com/owncloud/core/pull/37385)
- [ ] * Enhancement - Add new grace period and license management into core: [#36814](https://github.com/owncloud/core/pull/36814)
- [ ] * Enhancement - Add 3 new events (before-fail-after) for share password validations: [#37438](https://github.com/owncloud/core/pull/37438)
- [ ] * Enhancement - Boost performance of external storages: [#37451](https://github.com/owncloud/core/pull/37451)
- [ ] * Enhancement - Change the behavior of the header menus: [#37490](https://github.com/owncloud/core/pull/37490)

**Comment by jnweiger** [comment]
@davitol Can we close here? 
@pmaier1 close the entire https://github.com/orgs/owncloud/projects/139 board then?

**Comment by davitol** [comment]
Closing

**Comment by davitol** [comment]
BTW idk why the checkboxes got unmarked
