### ISSUE TITLE
Add acceptance tests for copying file over folder and vice versa

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37669]
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavProperties1/copyFile.feature has scenarios that copy a file to another file, and scenarios where the copy overwrites an existing file.

Add scenarios to cover combinations of:

- [x] copy a file over the top of an existing folder #37701 
- [x] copy a folder over the top of an existing file #37701 
- [x] copy between different folders at different levels in the user's file system view #37701 
- [ ] do these copy operations in a received user/group share

Note: PR #37660 is adding these type of copy-overwrite tests for public links.
