### ISSUE TITLE
Run acceptance tests with various databases

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38156]
Run acceptance tests with different databases to verify that all is OK.

- [x] mariadb:10.2 - this is the regular database used in CI
- [x] mariadb:10.3 #38157 pass
- [x] mariadb:10.4 #38158 pass
- [x] mariadb:10.5 #38159 pass
- [x] mysql:5.5 #38155 see https://github.com/owncloud/core/pull/38155#issuecomment-735387782 5.5 is not officially supported anyway
- [x] mysql:5.7 #38154 pass (but not officially supported anyway)
- [x] mysql:8.0 #38084 pass
- [x] postgres:9.4 #38153 passes with a couple of `skipOnDbPgsql`
- [x] postgres:10.3 #38086 
- [x] oracle #38082 passes with the `skipOnDbOracle` tags added in #38160 and #38166

**Comment by phil-davis** [comment]
I am re-running these to make sure it is all good:
- [x] postgres:9.4 #38402 
- [ ]

**Comment by phil-davis** [comment]
All good now. It is nice to know that the test suite runs with each database. I raised any issues related to specific databases.
