### ISSUE TITLE
Public API OC6 - what's missing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#4863]
This issue is to be used as a todo list for public apis which are missing as of today.
Please add a comment on what we miss and We will add this to the list below.

For each missing api a pull request is to be opened - once merged we can check the item on the todo list.

**How to implement a public api?**

1. Create an interface in the public namespace within lib/public which acts as the entry point for accessing the functionality e.g. https://github.com/owncloud/core/blob/master/lib/public/ipreview.php#L39
2. Add a getter to the IServerContainer - e.g. https://github.com/owncloud/core/blob/master/lib/public/iservercontainer.php#L64
3. Implement the api within the **private** namespace (core/lib/private) e.g.https://github.com/owncloud/core/blob/master/lib/private/previewmanager.php
4. Add the implementation of the getter to \OC\Server - please use the provided methods registerService() and query() because with this approach only those classes will be created which are going to be used 
https://github.com/owncloud/core/blob/5d4e9e0d25831cbe1b9c2fef52016c6ed1bbcb55/lib/server.php#L88
https://github.com/owncloud/core/blob/5d4e9e0d25831cbe1b9c2fef52016c6ed1bbcb55/lib/server.php#L49

**Mainly important on all public classes, interfaces and methods: add proper PHPDoc comments**

**Missing apis**
- [x] file api - fixed with https://github.com/owncloud/core/pull/4712
- [x] Avatar #5040
- [x] Config - #4928
- [ ] Search
- [ ] OCP\App with getAppWebPath() & loadApps() - #4919
- [ ] OC_FileProxy - see below
- [x] OC_Cache - #4886 
- [x] OC_Appconfig - is done with the config interface
- [ ] OC::getVersionString() - maybe define an interface IUtil?
- [ ] OC_App::disable() OC_App::enable() - coming in #5069
- [x] Session (and kill session from IRequest) - #4888
- [x] user and group managers
- [x] OCS API
- [x] template and related functions like nav menu - nav part in #4928
- [x] response sub classes
- [x] AppFramework - add public api for middleware handling - music app has a nice show case for middleware usage
- [x] Activity api - consumed by activity app
- [x] UserSession for login and logout - #4928
- [ ] ITaskScheduler and ITask
- [ ] IUtil / IHelper
- [ ] IEmitter
- [ ] EventSource. PHP side has been merged. JS side on standby
- [x] ILog
- [x] database - #4928
- [x] l10n
- [x] Middleware registration in app container.
- [x] \OCP\AppFramework\Utility\ControllerMethodReflector

**Comment by DeepDiver1975** [comment]
Time's up on this - please everybody: open individual issue for missing APIs - THX
