### ISSUE TITLE
Sharing overview tasks

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#8816]
- [x] Sharing overview basic work: #8417 
- [x] Add "Shared with link" in sidebar: #8815 
- [x] Important: Add recipients in share action: https://github.com/owncloud/core/pull/8791
- [ ] Performance: Group shares on server instead of client: #8796
- [ ] Performance: "Shared by link" server side filtering: #8863
- [ ] Add "size" and "mtime" column: #8792

**Comment by PVince81** [comment]
Closing. There are tickets already for the different items.
